import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/game';
import {fresh,validateSave} from '../src/save';
import {lifeAwards,validateLife} from '../src/life-data';
import {distance} from '../src/world';
function game(){const g=new Game(fresh(),6477);g.life.p.nextMain=g.life.p.nextSide=1e8;g.profile.tutorialFlags=['done'];return g;}
function step(g:Game,seconds:number){for(let t=0;t<seconds;t+=1/30)g.tick(1/30);}
function prepared(g:Game,kind:any,seed=11){const c=g.life.start(kind,seed);assert.ok(c);for(let t=0;t<80&&g.life.cases.includes(c as any)&&(c as any).stage===0;t+=1/30)g.tick(1/30);assert.equal((c as any).stage,1,JSON.stringify(g.life.p.ledger.slice(-2)));return c as any;}
test('old saves migrate; lifecycle caps and actor reservations reject occupied main/side/student slots',()=>{const g=game();const old:any=fresh();delete old.life;assert.equal(validateSave(old).life.clock,0);assert.ok(g.life.start('milk',1));assert.ok(g.life.start('baseball',2));assert.equal(g.life.start('milk',3),null);assert.equal(g.life.start('assembly',4),null);assert.ok(g.life.cases.flatMap(c=>c.actors).length<=5);assert.throws(()=>validateLife({...g.life.p,stomach:16}));});
test('meal heals once, abnormal slows without HP damage, movement interrupts and reserved result survives reload',()=>{let g=game();Object.assign(g.player,{x:-25.4,z:-19.4,hp:50});assert.ok(g.life.eat(true));g.tick(1/30,{x:1,z:0,run:false});assert.equal(g.player.hp,50);const p=validateSave(structuredClone(g.profile));g=new Game(p);g.life.p.nextMain=g.life.p.nextSide=1e8;Object.assign(g.player,{x:-25.4,z:-19.4,hp:50});assert.equal(g.life.p.pendingMeal?.abnormal,true);assert.ok(g.life.eat(false));step(g,1.1);assert.equal(g.player.hp,70);assert.equal(g.life.p.mealSerial,1);assert.equal(g.life.speed(g.player),.85);assert.equal(g.life.eat(),false);assert.ok(g.life.p.achievements.includes(lifeAwards[0]));step(g,16);assert.equal(g.player.hp,70);assert.equal(g.life.speed(g.player),1);});
test('normal meal caps HP and does not grant abnormal achievement',()=>{const g=game();Object.assign(g.player,{x:-25.4,z:-19.4,hp:95});assert.ok(g.life.eat(false));step(g,1.1);assert.equal(g.player.hp,100);assert.equal(g.life.p.achievements.length,0);});
test('milk passes three stages, nonstack slowdown, clean interrupted versus complete; dogs excluded',()=>{const g=game();const c=prepared(g,'milk');step(g,3);assert.equal(g.life.cases.length,0);assert.equal(g.life.puddles.length,2);const p=g.life.puddles[0];assert.equal(g.life.visuals()[0].type,'milk_fresh');step(g,31);assert.equal(g.life.visuals()[0].type,'milk_sour');step(g,31);assert.equal(g.life.visuals()[0].type,'milk_stinky');Object.assign(g.player,{x:p.x,z:p.z});assert.equal(g.life.speed(g.player),.9);const mop=g.objects.get('life:mop')!;g.take(mop.id);g.life.interact(p.id);g.tick(.1,{x:1,z:0,run:false});assert.equal(g.life.puddles.length,2);Object.assign(g.player,{x:p.x,z:p.z});g.life.interact(p.id);step(g,1.6);assert.equal(g.life.puddles.length,1);assert.ok(g.life.p.achievements.includes(lifeAwards[1]));assert.equal('hp' in g.dogs.actors[0],false);step(g,61);assert.equal(g.life.puddles.length,0);assert.equal(g.life.speed(g.player),1);assert.equal(g.objects.has(c.items[0]),false);});
test('baseball seeded break restores same original broom; picked object interrupts without replacement',()=>{const g=game();const original=g.objects.get('broom:0')!;const c=prepared(g,'baseball',5);Object.assign(g.player,c.points[1]);step(g,4*c.breakAt+1);assert.ok(g.life.p.achievements.includes(lifeAwards[2]));assert.equal(g.objects.get(original.id),original);assert.equal(original.broken,false);assert.equal(original.owner,null);assert.equal(g.life.fragments.length,2);step(g,21);assert.equal(g.life.fragments.length,0);const h=game();const d=prepared(h,'baseball',3);const orange=h.objects.get(d.items[0])!;assert.ok(h.take(orange.id));assert.equal(h.life.cases.length,0);assert.equal(h.held,orange);assert.equal([...h.objects.values()].filter(i=>i.type==='orange').length,1);});
test('baseball never consumes player-held or quest-pinned broom',()=>{const g=game();const broom=g.objects.get('broom:0')!;broom.pins=['quest:original'];const c=prepared(g,'baseball');assert.notEqual(c.items[1],broom.id);assert.deepEqual(broom.pins,['quest:original']);g.life.finish(c,false,'cancel');assert.equal(g.objects.get(broom.id),broom);});
test('theft uses true friend, locked thief; wrong hit never drops top, real hit drops original once and own alert clears only',()=>{const g=game();const c=prepared(g,'theft');const owner=g.npcs.find(n=>n.id===c.owner)!;const thief=g.npcs.find(n=>n.id===c.thief)!;assert.equal(owner.friend,thief.id);const i=g.objects.get(c.items[0])!;assert.equal(i.owner,thief.id);g.alert=48;g.damageNPC(owner,1,'wrong');assert.equal(i.owner,thief.id);const before=g.alert;g.damageNPC(thief,1,'true');assert.equal(i.owner,null);assert.equal(g.objects.get(i.id),i);assert.equal(c.recoveryHit,true);g.damageNPC(thief,1,'again');assert.equal([...g.objects.values()].filter(x=>x.id===i.id).length,1);const other=g.npcs.find(n=>n.type==='dean')!;other.state='Chase';g.alert=67;assert.ok(g.take(i.id));g.life.interact(c.id+':return');assert.equal(g.alert,59);assert.equal(other.state,'Chase');assert.equal(g.npcs.find(n=>n.id===c.parent)?.state,'Leave');assert.ok(g.life.p.achievements.includes(lifeAwards[3]));assert.equal(g.life.cases.length,0);assert.ok(before>=48);});
test('newly attacked event parent retains hostile state after top return',()=>{const g=game();const c=prepared(g,'theft');const p=g.npcs.find(n=>n.id===c.parent)!;g.damageNPC(p,1,'parent-hit');const n=g.npcs.find(n=>n.id===c.thief)!;g.damageNPC(n,1,'recover');g.take(c.items[0]);g.life.interact(c.id+':return');assert.equal(p.state,'Chase');});
test('neutral parent authored recovery never fabricates player combat evidence or creates revenge family',()=>{const g=game();const c=prepared(g,'theft');const before=g.profile.meeting.campusEvents.length;step(g,35);assert.equal(g.life.cases.length,0);assert.equal(g.profile.meeting.campusEvents.length,before);assert.equal(g.familyQueue.length,0);assert.ok(g.life.p.ledger.some(e=>e.sourceActorId===c.parent&&e.resolutionReason==='家長請求歸還並輕碰'));});
test('theft parent slot refuses fourth parent and timeout preserves original player inventory',()=>{const g=game();for(let i=0;i<3;i++)g.addNPC('neat','parent',{x:0,z:24});assert.equal(g.life.start('theft',1),null);const h=game();const c=prepared(h,'theft');const original=h.objects.get('recorder:0')!;h.take(original.id);c.age=90;step(h,.1);assert.equal(h.held,original);assert.equal(h.life.cases.length,0);});
test('both compact areas have real paths and open approaches in all modes',()=>{for(const mode of ['normal','parent_day','anniversary','choir_contest','final_exam']){const g=game();g.reset(mode);for(const p of [{x:-8,z:-18},{x:9,z:-18}]){assert.equal(g.world.blocked(p),false);assert.ok(g.world.path({x:0,z:-11},p).length);}}});
test('patrol report and actual arrival/escort award, instrument only hides and does not resolve',()=>{const g=game();const c=prepared(g,'patrol',11);Object.assign(g.player,c.points[0]);g.life.warn();assert.equal(c.stage,1);assert.equal(g.life.p.achievements.length,0);g.life.interact('life:report');step(g,50);assert.equal(g.life.cases.length,0);assert.ok(g.life.p.achievements.includes(lifeAwards[4]));assert.equal(g.npcs.filter(n=>n.type==='patrol_teacher').length,1);});
test('assembly actual classroom finding, five seeded answers, escort succeeds; phase expiry cancels',()=>{for(let seed=0;seed<5;seed++){const g=game();const c=prepared(g,'assembly',seed);assert.equal(c.responses[3],(seed+3)%5);g.life.interact('life:report');step(g,40);assert.ok(g.life.p.achievements.includes(lifeAwards[5]),JSON.stringify(g.life.p.ledger.slice(-3)));assert.equal(g.life.cases.length,0);}const g=game();g.life.p.clock=36;assert.equal(g.life.start('assembly',1),null);g.life.p.clock=0;const c=g.life.start('assembly',1)!;g.life.p.clock=60;step(g,.1);assert.equal(g.life.cases.length,0);assert.equal(g.life.p.achievements.length,0);});
test('meeting freezes campus events, meal and puddle clocks, same reservations resume; rescue cleans once',()=>{const g=game();const c=prepared(g,'milk');g.life.p.stomach=10;g.life.p.mealCooldown=50;g.life.puddles.push({id:'test',x:0,z:0,age:65});const clock=g.life.p.clock,age=(c as any).age;g.meeting.start(7,['voting','bell']);step(g,5);assert.equal(g.life.p.clock,clock);assert.equal((c as any).age,age);assert.equal(g.life.p.stomach,10);assert.equal(g.life.puddles[0].age,65);g.meeting.end('test');step(g,3);assert.equal(g.meeting.running,false);g.rescue();g.life.reset();assert.equal(g.life.cases.length,0);assert.equal(g.life.puddles.length,0);assert.equal(g.life.alert,0);assert.equal(g.life.p.stomach,0);});
test('all life actor poses retain actual melee and projectile damage; dogs have no human HP',()=>{for(const state of ['LifeWalk','LifeIdle','LifeThrow','LifeSwing','LifeQuestion','LifeSurprise','LifeInspect','LifePhone','LifeHide','LifeEscort','LifePatrol','LifeCover','LifeUrgent','LifeWord','LifeLate','LifePoint'])for(const weapon of ['bare','mop','orange']){const g=game();const n=g.npcs.find(n=>n.type==='patrol_teacher')!;Object.assign(n,{x:0,z:0,state,active:true});Object.assign(g.player,{x:0,z:1,face:{x:0,z:-1}});const before=n.hp;if(weapon==='orange'){const i=g.createItem('orange','test:orange',{x:0,z:1});g.take(i.id);g.throwItem();step(g,.4);}else{if(weapon==='mop')g.take('life:mop');g.attack();step(g,.2);}assert.ok(n.hp<before,state+weapon);for(const d of g.dogs.actors){assert.equal(g.damageNPC(d as any,100,'test'),false);assert.equal('hp' in d,false);}}});
test('actual reserved students and safety teacher lose HP before event cleanup; no callback resurrects cancelled work',()=>{for(const kind of ['milk','baseball','patrol','assembly'] as const)for(const role of ['student','teacher']){if(role==='teacher'&&!['patrol','assembly'].includes(kind))continue;const g=game(),c=prepared(g,kind,2);const n=g.npcs.find(n=>role==='teacher'?n.type==='patrol_teacher':n.id===c.actors[0])!;const hp=n.hp;g.damageNPC(n,10,'actual-event-hit');assert.equal(n.hp,hp-10);assert.equal(g.life.cases.length,0);assert.equal(g.life.p.active.length,0);step(g,3);assert.equal(g.life.cases.length,0);assert.equal(g.life.p.achievements.length,0);}});
test('reload safely ends reservations and meeting-carried event objects; meal reservation and consumed serial stay fixed',()=>{const g=game(),c=prepared(g,'theft');g.damageNPC(g.npcs.find(n=>n.id===c.thief)!,1,'recover');g.take(c.items[0]);g.meeting.start(11,['bell','voting']);step(g,1);const p=validateSave(structuredClone(g.profile));assert.equal(p.life.active[0].thief,c.thief);const h=new Game(p);assert.equal(h.life.cases.length,0);assert.equal(h.life.p.active.length,0);assert.equal([...h.objects.keys()].some(id=>/^life:\d+:/.test(id)),false);assert.equal(h.life.p.achievements.length,0);h.assertOwnership();});
test('alert source isolation holds at saturation and negative decay never consumes unrelated later contributions',()=>{const g=game();g.alert=100;const c=g.life.start('theft',1)!;assert.equal(g.alert,100);g.notice('extra',5,'extra');g.life.finish(c,false,'test');assert.equal(g.alert,100);});
test('sour milk gives legal idle patrol detour without adding blocking colliders or stacked slowdown',()=>{const g=game();const n=g.npcs.find(n=>n.type==='patrol_teacher')!;Object.assign(n,{x:0,z:-11,state:'Walk'});const before=g.world.dynamic.length;g.life.puddles=[{id:'spill',x:1,z:-11,age:40},{id:'spill2',x:1,z:-11,age:70}];const target={x:4,z:-11},detour=g.life.navigation(n,target);assert.notDeepEqual(detour,target);assert.equal(g.world.blocked(detour),false);assert.equal(g.world.dynamic.length,before);Object.assign(g.player,{x:1,z:-11});assert.equal(g.life.speed(g.player),.9);assert.ok(g.world.path(n,detour).length);});
test('starting a mission takes priority, safely retires event items and restores original broom reference',()=>{const g=game(),broom=g.objects.get('broom:0'),c=prepared(g,'baseball');assert.equal(c.originalBroom,broom!.id);assert.ok(g.startMission('q01'));assert.equal(g.life.cases.length,0);assert.equal(g.objects.get(broom!.id),broom);assert.equal(broom!.owner,null);g.assertOwnership();});
