import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../src/game';import {fresh,validateSave} from '../src/save';
function tick(g:Game,t:number){for(let k=0;k<t*30;k++)g.tick(1/30);}
function game(){const g=new Game();g.life.p.nextMain=g.life.p.nextSide=1e8;g.npcs=[];return g;}
test('only actual trouble parent arrivals count: cap, failed spawn, neutral lost-property parent and visitors',()=>{const g=game();assert.ok(g.spawnParent('spatula'));assert.ok(g.spawnParent('spatula'));assert.ok(g.spawnParent('spatula'));assert.equal(g.meeting.troubleParents,3);assert.equal(g.spawnParent('spatula'),false);assert.equal(g.meeting.troubleParents,3);assert.equal(g.parentCount(),3);g.npcs=[];g.addNPC('neat','parent',{x:0,z:24},'life:neutral');g.addNPC('neat','visitor',{x:0,z:15},'visitor:0');assert.equal(g.meeting.troubleParents,3);const h=game();h.spawnParent('duo');assert.equal(h.meeting.troubleParents,2);h.spawnParent('spatula');assert.equal(h.meeting.troubleParents,3);});
test('successful bare or held swing rolls once after three arrivals; cooldown/repeat/hidden attempts do not draw',()=>{const g=game();g.meeting.parentArrived(2);g.attack();assert.equal(g.meeting.gateRolls,0);g.player.attackCooldown=0;g.meeting.parentArrived(1);g.meeting.gateSeed=1000;assert.ok(g.attack());assert.equal(g.meeting.gateRolls,1);assert.equal(g.meeting.summons,0);assert.equal(g.attack(),false);assert.equal(g.meeting.gateRolls,1);g.player.attackCooldown=0;g.profile.meeting.cooldown=60;g.attack();assert.equal(g.meeting.gateRolls,1);g.profile.meeting.cooldown=0;g.player.attackCooldown=0;g.player.hidden=true;assert.equal(g.attack(),false);assert.equal(g.meeting.gateRolls,1);g.player.hidden=false;g.player.attackCooldown=0;g.take('broom:0');g.meeting.gateSeed=0;assert.ok(g.attack());assert.equal(g.meeting.gateRolls,2);assert.ok(g.meeting.summons>0);g.player.attackCooldown=0;g.attack();assert.equal(g.meeting.gateRolls,2);});
test('draw succeeds at 50%, starts after caption at positive HP and safely preserves carried original',()=>{const g=game();g.meeting.parentArrived(3);g.meeting.gateSeed=0;const book=g.objects.get('textbook:0')!;g.take(book.id);const hp=g.player.hp;g.attack();assert.equal(g.meeting.phase,'CAMPUS');tick(g,1);assert.equal(g.meeting.phase,'CAMPUS');tick(g,.3);assert.equal(g.meeting.phase,'ENTERING');assert.equal(g.player.hp,hp);tick(g,.5);assert.equal(g.meeting.running,true);assert.equal(g.objects.get(book.id),book);g.meeting.endReason='自行離席';g.meeting.finish();assert.equal(g.held,book);assert.equal(g.profile.meeting.cooldown,60);assert.equal(g.meeting.troubleParents,0);assert.equal(g.meeting.summons,0);});
test('gate RNG has stable 50% distribution and consumes no frame-dependent draws',()=>{const g=game();g.meeting.parentArrived(3);g.meeting.gateSeed=91;let hits=0;for(let k=0;k<10000;k++){if(g.meeting.considerSwing())hits++;g.meeting.summons=0;}assert.ok(hits>4800&&hits<5200,hits+' / 10000');const h=game();h.meeting.parentArrived(3);h.meeting.gateSeed=1000;tick(h,2);assert.equal(h.meeting.gateRolls,0);assert.equal(h.meeting.gateSeed,1000);});
test('reset cancels summons; HP zero rescues normally; old 300-second cooldown migrates to 60',()=>{const g=game();g.meeting.parentArrived(3);g.meeting.gateSeed=0;g.attack();g.reset();tick(g,2);assert.equal(g.meeting.phase,'CAMPUS');assert.equal(g.meeting.troubleParents,0);g.player.hp=1;const parent=g.addNPC('spatula','parent',g.player);g.damagePlayer(10,parent);assert.equal(g.meeting.running,false);assert.equal(g.player.hp,100);const p=fresh();p.meeting.cooldown=300;assert.equal(validateSave(p).meeting.cooldown,60);});
test('departing old parents free the original three slots for the next round',()=>{const g=game();g.spawnParent('spatula');g.spawnParent('spatula');g.spawnParent('spatula');g.meeting.start(123,['bell','voting']);tick(g,.4);g.meeting.endReason='自行離席';g.meeting.finish();assert.ok(g.npcs.every(n=>n.role!=='parent'||n.state==='Leave'));tick(g,10);assert.equal(g.parentCount(),0);assert.equal(g.meeting.troubleParents,0);});
test('positive dog gains carry matching portrait metadata; capped and duplicate gains do not pop a smile',()=>{const g=game(),messages:any[]=[];g.onToast=(text,dog)=>messages.push({text,dog});g.dogs.gain('dog_lion',2,'test:1');assert.deepEqual(messages.at(-1).dog,{id:'dog_lion',gain:2});g.dogs.p.dogs.dog_mani.affinity=99;g.dogs.gain('dog_mani',5,'test:2');assert.deepEqual(messages.at(-1).dog,{id:'dog_mani',gain:1});g.dogs.gain('dog_mani',5,'test:3');assert.equal(messages.at(-1).dog,undefined);const count=messages.length;assert.equal(g.dogs.gain('dog_mani',5,'test:3'),false);assert.equal(messages.length,count);});
