import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/game';
import {fresh,validateSave} from '../src/save';
import {modules,selectModules,incompatible} from '../src/meeting-data';
import {distance} from '../src/world';
const tick=(g:Game,s:number)=>{for(let k=0;k<Math.ceil(s*30);k++)g.tick(1/30);};
function room(selected=['projector','bell'],guest='shop_aunt'){const g=new Game();g.finishTutorial();g.meeting.start(123,selected,guest);tick(g,.4);g.meeting.activate();g.meeting.testHold=true;return g;}
test('selection: 10000 seeds, deterministic, 2/3 weighted slots, exclusions, complete library, no identical previous set',()=>{const seen=new Set();let triples=0;for(let s=0;s<10000;s++){const ids=selectModules(s,[],[],true);assert.deepEqual(ids,selectModules(s,[],[],true));assert.ok([2,3].includes(ids.length));assert.equal(new Set(ids).size,ids.length);assert.equal(incompatible(ids),false);ids.forEach(id=>seen.add(id));if(ids.length===3)triples++;assert.notDeepEqual(selectModules(s,[ids],[],true),ids);}assert.equal(seen.size,16);assert.ok(triples>2500&&triples<3500);});
const states=['Seated','Standing','Speaking','Voting','Sleeping','Recording','Collect','Drinking','Protecting','Following','FindingChair','Coordinating','Watching','Cold','Hot','Recover'];
for(const [role,guest,index] of [['主席','shop_aunt',0],['家長代表','shop_aunt',1],['紀錄委員','shop_aunt',2],['秩序委員','none',3],['合作社阿姨','shop_aunt',3],['警衛伯伯','guard_uncle',3]] as [string,string,number][]){
 test(`${role}: every state receives bare, held and projectile attacks with visible displacement and recovery`,()=>{for(const state of states)for(const method of ['bare','held','throw']){const g=room(guest==='none'?['bell','projector']:['guest_mediator','bell'],guest);const n=g.npcs[index];n.state=state;n.timer=3;if(state==='Recover'){n.hp=0;(n as any).downAt=0;}const start={x:n.x,z:n.z};const side=n.x>0?1:-1;Object.assign(g.player,{x:n.x+side*.85,z:n.z,face:{x:-side,z:0},inv:99});assert.equal(g.world.blocked(g.player,.32),false,`${role}/${state}/${method} legal attack position`);if(method!=='bare'){const i=[...g.objects.values()].find(i=>i.type==='meeting_gavel')!;g.take(i.id);}if(method==='throw')assert.ok(g.throwItem());else assert.ok(g.attack());tick(g,.23);const hits=g.meeting.events.filter(e=>e.type==='CombatResolved'&&e.data.npc===n.id);assert.equal(hits.length,1,`${state}/${method}`);assert.ok(distance(n,start)>.01,`${state}/${method} must visibly move`);assert.ok((n as any).flashUntil>0);tick(g,5.2);assert.ok(n.hp>0,`${state}/${method} recovers`);assert.notEqual(n.state,'Recover');g.assertOwnership();}});
}
test('same attack duplicate rejected; repeated distinct attacks react while downed, no permanent stun',()=>{const g=room(),n=g.npcs[1];for(let k=0;k<20;k++){g.damageNPC(n,100,'different:'+k);assert.equal(g.damageNPC(n,100,'different:'+k),false);tick(g,.2);}tick(g,1.1);assert.ok(n.hp>0);});
test('only real speaking interruptions score, all voting cards use existing instances and held card becomes absent',()=>{const g=room(['voting','bell']);const bell=[...g.objects.values()].find(i=>(i as any).module==='bell')!;g.take(bell.id);g.meeting.secondary();assert.equal(g.meeting.done.has('bell'),false);g.meeting.elapsed=4;g.meeting.react('Speaking',2,['meeting:0']);g.meeting.secondary();assert.equal(g.meeting.done.has('bell'),true);g.drop();const cards=[...g.objects.values()].filter(i=>i.type==='meeting_vote');cards.forEach(i=>(i as any).vote=2);g.meeting.vote();assert.ok(g.profile.meeting.titles.includes('全票透過離席'));const size=g.objects.size;g.take(cards[0].id);g.meeting.vote();assert.ok(g.meeting.voteResult.includes('找不到表決牌'));assert.equal(g.objects.size,size);});
test('meeting IDs stay unique across reload, rejected transfer data never reaches rendering',()=>{const g=room();g.meeting.endReason='離席';g.meeting.finish();const first=g.profile.meeting.records[0].id;const reload=new Game(validateSave(JSON.parse(JSON.stringify(g.profile))));reload.meeting.start(123,['bell','projector']);assert.notEqual(reload.meeting.id,first);reload.meeting.checkpoint();const bad=JSON.parse(JSON.stringify(reload.profile));bad.meeting.pending.origin.items=[{id:'evil',type:'missing',state:'held',home:{x:0,z:0},hit:[],pins:[]}];assert.throws(()=>validateSave(bad),/移交/);});
test('idle speech respects active musical movement, manual stop is available before ten second cooldown',()=>{const g=room(['musical_chairs','projector']);const remote=[...g.objects.values()].find(i=>(i as any).module==='musical_chairs')!;g.take(remote.id);assert.ok(g.meeting.secondary());tick(g,1);assert.ok(g.npcs.some(n=>n.state==='MusicWalk'));assert.ok(g.meeting.secondary());assert.equal(g.meeting.musicUntil,0);assert.equal(g.meeting.secondary(),false);});
test('summons transition lock and meeting defeat never recurse',()=>{const g=new Game();g.npcs=[];const parent=g.addNPC('spatula','parent',{x:g.player.x,z:g.player.z});g.meeting.parentArrived(3);g.meeting.gateSeed=0;g.attack();tick(g,1.3);assert.equal(g.meeting.phase,'ENTERING');const id=g.meeting.id;g.player.inv=0;g.damagePlayer(8,parent);assert.equal(g.meeting.id,id);tick(g,3);g.player.inv=0;g.damagePlayer(200,g.npcs[1]);tick(g,.1);assert.equal(g.meeting.phase,'ENDING');tick(g,2);assert.equal(g.meeting.phase,'CAMPUS');assert.equal(g.profile.meeting.records.length,1);assert.ok(g.profile.meeting.cooldown>59);g.player.inv=0;g.player.hp=1;g.damagePlayer(8,parent);assert.equal(g.meeting.phase,'CAMPUS');const other=new Game();other.player.hp=1;other.damagePlayer(200,other.npcs.find(n=>n.role==='staff')!);assert.equal(other.meeting.phase,'CAMPUS');assert.ok(other.eventLog.some(e=>e.type==='rescue'));});
test('four exits settle once with defeat > leave > chaos > timeout',()=>{for(const reason of ['再倒地','自行離席','失控值滿','時間到']){const g=room();g.meeting.testHold=false;g.meeting.elapsed=75;if(reason!=='時間到')g.meeting.chaos=100;if(['再倒地','自行離席'].includes(reason))g.meeting.leave();if(reason==='再倒地')g.player.hp=0;tick(g,.1);assert.equal(g.meeting.endReason,reason);g.meeting.end('other');tick(g,2);assert.equal(g.profile.meeting.records.length,1);assert.equal(g.player.hp,100);assert.equal(g.meeting.phase,'CAMPUS');}});
test('campus snapshot and unique carried/worn/pinned identity survive throws and all cleanup',()=>{const g=new Game();g.startMission('q04');g.take('principal_wig:0');g.wear('principal_wig:0');g.take('folder:0');const folder=g.held!,pins=[...folder.pins],npcs=g.npcs,layout=g.layout,objects=g.objects,attempt=g.attempt,time=g.time;g.meeting.start(123,['paper_planes','guest_mediator']);tick(g,.4);g.meeting.activate();g.take(folder.id);g.throwItem();tick(g,1);g.meeting.leave();tick(g,2);assert.equal(g.npcs,npcs);assert.equal(g.layout,layout);assert.equal(g.objects,objects);assert.equal(g.attempt,attempt);assert.ok(g.time-time<.6);assert.equal(g.held,folder);assert.deepEqual(folder.pins,pins);assert.equal(g.player.wig,'principal_wig:0');assert.equal([...g.objects.values()].filter(i=>(i as any).meetingOnly).length,0);assert.equal(g.broadcasts.size,0);g.assertOwnership();});
test('old save compatibility, reload safe return and cooldown preservation',()=>{const old=fresh();delete (old as any).meeting;assert.equal(validateSave(old).meeting.cooldown,0);const g=room();g.meeting.checkpoint();const profile=validateSave(JSON.parse(JSON.stringify(g.profile)));const reload=new Game(profile);assert.equal(reload.meeting.phase,'CAMPUS');assert.equal(reload.profile.meeting.cooldown,60);assert.equal(reload.profile.meeting.pending,null);assert.equal(reload.profile.meeting.records.at(-1)?.reason,'讀檔安全散場');tick(reload,1);assert.ok(reload.profile.meeting.cooldown<60);const count=reload.profile.meeting.records.length;new Game(validateSave(JSON.parse(JSON.stringify(reload.profile))));assert.equal(reload.profile.meeting.records.length,count);});
test('five minute evidence uses persisted playable campus time; pause and meeting do not age campus clock',()=>{const g=new Game();g.profile.meeting.campusClock=500;g.profile.meeting.campusEvents=[{campusTime:100,text:'old'},{campusTime:490,text:'使用課本擊中家長'}];g.meeting.start(123,['projector','bell']);tick(g,3);assert.equal(g.profile.meeting.campusClock,500);assert.deepEqual(g.meeting.cards,['使用課本擊中家長','感謝聆聽，敬請指教']);g.meeting.endReason='離席';g.meeting.finish();const reload=new Game(validateSave(JSON.parse(JSON.stringify(g.profile))));assert.equal(reload.profile.meeting.campusClock,500);tick(reload,1);assert.ok(reload.profile.meeting.campusClock>500);});
test('all seats and props accessible via original navigation, four target budget and substitute remains hittable',()=>{const g=room(['guest_mediator','sleepy_member']);for(const n of g.npcs){const goal=g.world.approach({x:n.x,z:n.z+.85},g.player);assert.ok(g.world.path(g.player,goal).length,n.label);assert.equal(g.world.blocked(n,.32),false);}assert.equal(g.npcs.length,4);g.damageNPC(g.npcs[0],3,'a',true);g.damageNPC(g.npcs[0],3,'b');tick(g,.1);assert.notEqual(g.meeting.host,'meeting:0');assert.ok(g.damageNPC(g.npcs.find(n=>n.id===g.meeting.host)!,1,'sub'));tick(g,4);assert.equal(g.meeting.host,'meeting:0');});
test('every module initializes, characteristic interaction, damage interrupt, recovery and scene cleanup',()=>{for(const module of modules.filter(m=>m.id!=='dog_observer')){const companion=module.id==='projector'?'bell':'projector';const g=room([module.id,companion]);g.meeting.elapsed=18;
 const item=[...g.objects.values()].find(i=>(i as any).module===module.id);if(item){g.take(item.id);Object.assign(g.player,{x:g.npcs[0].x,z:g.npcs[0].z+.85});}
 switch(module.id){case 'projector':g.meeting.secondary();break;case 'reenactment':g.attack();break;case 'bell':g.meeting.react('Speaking',2,['meeting:0']);g.meeting.secondary();break;case 'conducting':case 'stamps':case 'aircon':g.meeting.secondary();break;case 'voting':g.meeting.secondary();g.drop();g.meeting.vote();break;case 'printer':break;case 'cross_talk':if(g.held)g.drop();g.take([...g.objects.values()].find(i=>i.type==='folder')!.id);Object.assign(g.player,{x:g.npcs[0].x,z:g.npcs[0].z+.85,face:{x:0,z:-1}});g.throwItem();tick(g,.3);break;case 'tea_spill':g.throwItem();tick(g,2);break;case 'guest_mediator':g.meeting.react('Coordinating',2,[g.npcs[3].id]);g.damageNPC(g.npcs[3],1,'guest');break;case 'musical_chairs':g.meeting.secondary();const chair=[...g.objects.values()].find(i=>i.id.endsWith('chair:0'))!;chair.x+=1.5;tick(g,5);break;case 'sleepy_member':const n=g.npcs.find(n=>n.id===g.meeting.sleepId)!;n.state='Sleeping';g.damageNPC(n,1,'wake');break;case 'paper_planes':if(g.held)g.drop();g.take([...g.objects.values()].find(i=>i.type==='meeting_report')!.id);g.meeting.secondary();tick(g,.5);g.throwItem();break;case 'whiteboard':Object.assign(g.player,{x:4.5,z:8.8});g.meeting.secondary();break;}
 assert.ok(g.meeting.done.has(module.id),module.id);const n=g.npcs[0];n.state='Watching';assert.ok(g.damageNPC(n,1,'interrupt:'+module.id));assert.ok(['hit','Recover'].includes(n.state));tick(g,4);assert.ok(n.hp>0);const snapshot=g.meeting.snapshot;g.meeting.leave();tick(g,2);assert.equal(g.objects,snapshot.objects);assert.equal(g.meeting.water.length,0);assert.equal(g.meeting.timers.size,0);assert.equal(g.meeting.fold,null);g.assertOwnership();}});
