import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1280,height:900},hasTouch:true});await page.addInitScript('window.__name=v=>v');const errors:string[]=[],violations:any[]=[],checks:any[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.QA_URL||'http://127.0.0.1:5173');await page.locator('[data-action=start]').click();await page.locator('#skip').click();
 async function audit(label:string,selector:string){await page.waitForTimeout(120);const result=await page.evaluate(selector=>{const root=document.querySelector(selector)!,buttons=[...root.querySelectorAll('button')].filter(el=>el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden').map(el=>{const r=el.getBoundingClientRect();return {id:el.id||el.getAttribute('data-action')||'',label:el.textContent?.trim(),x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width}});const bad:any[]=[];let min=Infinity;for(let i=0;i<buttons.length;i++)for(let j=i+1;j<buttons.length;j++){const a=buttons[i],b=buttons[j],dx=Math.max(0,a.x-b.right,b.x-a.right),dy=Math.max(0,a.y-b.bottom,b.y-a.bottom),gap=Math.hypot(dx,dy);min=Math.min(min,gap);if(gap<7.5)bad.push({a,b,gap})}return {count:buttons.length,minGap:Number.isFinite(min)?min:null,bad,overflow:root.scrollWidth>root.clientWidth+1}},selector);checks.push({label,...result});if(result.bad.length||result.overflow)violations.push({label,...result});}
 const menus=['start','pause','missions','calendar','settings','help','actions','shop','map','knockdowns','items','codex','life','collection','report','save','dogs','meetingRecords','timeQuestion','resetConfirm','clearConfirm','mode:anniversary','debug'];
 for(const size of [{width:1280,height:900},{width:844,height:390},{width:390,height:844},{width:320,height:700}]){
  await page.setViewportSize(size);
  await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.startMission('q01')});
  for(const name of menus){await page.evaluate(name=>(window as any).__dongshan.ui.open(name),name);await audit(`${size.width} ${name}`,'.panel');if(size.width===390&&['shop','timeQuestion','resetConfirm','missions'].includes(name))await page.screenshot({path:`artifacts/button-spacing-${name}.png`})}
  await page.evaluate(()=>{const d=(window as any).__dongshan;d.ui.close();d.game.cancelMission();d.game.player.inv=9999});
  for(const state of ['empty','held','held-choir']){await page.evaluate(state=>{const d=(window as any).__dongshan,g=d.game;if(g.held)g.drop();g.choir=null;if(state!=='empty'){const item=[...g.objects.values()].find((i:any)=>i.type==='wireless_microphone');g.player.x=item.x;g.player.z=item.z;g.take(item.id)}if(state==='held-choir')g.startChoir();d.ui.setQuestCollapsed(false);d.ui.update(.2)},state);await audit(`${size.width} HUD ${state}`,'.hud')}
 }
 await page.evaluate(()=>(window as any).__dongshan.ui.open('resetConfirm'));await page.locator('.button-row [data-action=open]').tap();assert.match(await page.locator('.panel-head h2').innerText(),/課間休息/);await page.evaluate(()=>(window as any).__dongshan.ui.open('timeQuestion'));await page.locator('[data-action=answer][data-id="6"]').focus();await page.keyboard.press('Enter');assert.match(await page.locator('#toast').innerText(),/再看一次/);
 await page.goto((process.env.QA_URL||'http://127.0.0.1:5173')+'/soundtest.html');await audit('320 sound test','main');assert.deepEqual(errors,[]);
 fs.writeFileSync('artifacts/button-spacing-qa.json',JSON.stringify({date:'2026-10-09',status:violations.length?'fail':'pass',browser:await browser.version(),method:'Actual button bounding rectangles; all pairs ≥8px target (0.5px rounding tolerance), panel width/overflow check. Modal/gameplay states prepared through existing dev UI, no destructive confirmation clicked.',checks,violations,touchCancel:true,keyboardAnswer:true,errors,limitations:['Chromium desktop/touch viewport emulation, not physical phones or Safari.']},null,2));console.log(JSON.stringify({checks:checks.length,violations}));assert.equal(violations.length,0);
}finally{await browser.close()}
