import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
const site=process.env.SITE_URL||'https://ml-yoyohuang.github.io/teacher-simulator/';
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});await page.addInitScript('window.__name=v=>v');const errors:string[]=[],checks:any[]=[],assets:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(site);const html=await page.content();
 for(const name of ['game-CtQhpnac.js','game-m_FARN0v.css']){assert.ok(html.includes(name));const response=await page.request.get(new URL('assets/'+name,site).href);assert.equal(response.status(),200);assert.equal(createHash('sha256').update(await response.body()).digest('hex'),createHash('sha256').update(fs.readFileSync('dist/assets/'+name)).digest('hex'));assets.push(name)}
 assert.equal(await page.evaluate(()=>typeof(window as any).__dongshan),'undefined');await page.locator('[data-action=start]').tap();await page.locator('#skip').tap();
 async function audit(label:string,selector:string){await page.waitForTimeout(100);const result=await page.evaluate(selector=>{const root=document.querySelector(selector)!,buttons=[...root.querySelectorAll('button')].filter(b=>b.getClientRects().length&&getComputedStyle(b).visibility!=='hidden').map(b=>b.getBoundingClientRect());let min=Infinity;for(let i=0;i<buttons.length;i++)for(let j=i+1;j<buttons.length;j++){const a=buttons[i],b=buttons[j];min=Math.min(min,Math.hypot(Math.max(0,a.x-b.right,b.x-a.right),Math.max(0,a.y-b.bottom,b.y-a.bottom)))}return{count:buttons.length,minGap:Number.isFinite(min)?min:null,overflow:root.scrollWidth>root.clientWidth+1}},selector);assert.ok(result.minGap===null||result.minGap>=7.5,label);assert.equal(result.overflow,false,label);checks.push({label,...result})}
 for(const size of [{width:390,height:844},{width:844,height:390},{width:1280,height:900}]){await page.setViewportSize(size);await audit(`${size.width} HUD`,'.hud');for(const name of ['settings','save','calendar']){await page.locator('#menu').tap();await audit(`${size.width} pause`,'.panel');await page.locator(`[data-action=open][data-id="${name}"]`).tap();await audit(`${size.width} ${name}`,'.panel');await page.locator('.panel-head [data-action=close]').tap()}await page.locator('#menu').tap();await page.locator('[data-action=confirmReset]').tap();await audit(`${size.width} resetConfirm`,'.panel');if(size.width===390)await page.screenshot({path:'artifacts/button-spacing-production-mobile.png'});await page.locator('.button-row [data-action=open]').tap();assert.match(await page.locator('.panel-head h2').innerText(),/課間休息/);await page.locator('.panel-head [data-action=close]').tap()}
 assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/button-spacing-production-qa.json',JSON.stringify({date:'2026-10-09',status:'pass',site,browser:await browser.version(),assets,checks,errors,limitations:['Public smoke test covers empty-hand HUD and non-destructive menus; held/choir and other states tested locally.','Physical phone and Safari not tested.']},null,2));console.log(JSON.stringify({status:'pass',checks:checks.length,assets}));
}finally{await browser.close()}
