import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {dogQuests} from '../src/dogs-data';
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1280,height:800}});await page.addInitScript('window.__name=v=>v');const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5174');await page.locator('[data-action=start]').click();await page.locator('#skip').click();
await page.evaluate(()=>{const {game:g,ui}=(window as any).__dongshan;ui.paused=true;g.player.inv=99;g.dogs.nextFeed=1e9;for(const n of g.npcs)n.timer=-999;});
async function walk(goal:{x:number,z:number},dog=false){const result=await page.evaluate(({goal,dog})=>{const {game:g,render:r}=(window as any).__dongshan;const target=g.world.approach(goal,g.player),path=g.world.path(g.player,target);if(!path.length)return {ok:false,reason:'no path',goal};let ticks=0;for(const next of path){while(Math.hypot(g.player.x-next.x,g.player.z-next.z)>.2&&ticks++<4000){const dx=next.x-g.player.x,dz=next.z-g.player.z,m=Math.hypot(dx,dz);g.tick(1/30,{x:dx/m,z:dz/m,run:!dog});}}if(dog)for(let k=0;k<180;k++)g.tick(1/30);r.target.set(g.player.x,0,g.player.z);r.frame(.1,false,1);return {ok:Math.hypot(g.player.x-target.x,g.player.z-target.z)<.6,ticks,player:{x:g.player.x,z:g.player.z},blocked:g.world.blocked(g.player,.23),dogs:g.dogs.actors.map((d:any)=>({id:d.id,x:d.x,z:d.z,state:d.state,blocked:g.world.blocked(d,.23),route:(d as any).routeDone}))};},{goal,dog});assert.ok(result.ok,JSON.stringify(result));assert.equal(result.blocked,false);assert.ok(result.dogs.every(d=>!d.blocked));return result;}
const results:any[]=[];
for(const q of dogQuests){const teacher=await page.evaluate(()=>{const g=(window as any).__dongshan.game,n=g.npcs.find((n:any)=>n.type==='science_teacher');return {x:n.x,z:n.z};});await walk(teacher);const accepted=await page.evaluate(id=>(window as any).__dongshan.game.dogs.quest(id),q.id);assert.ok(accepted,q.id);
 if('item' in q){await walk(q.home);const taken=await page.evaluate(id=>{const g=(window as any).__dongshan.game;return g.interact(g.targets().find((t:any)=>t.id===id+':unique'))!==false;},q.id);assert.ok(taken);await walk(q.goal);const dropped=await page.evaluate(()=>{const g=(window as any).__dongshan.game;const target=g.nearest();if(!target?.id.startsWith('dog-place:'))return {ok:false,target};g.interact();return {ok:!g.held,target:target.id};});assert.ok(dropped.ok,JSON.stringify(dropped));}
 else {await walk({x:8,z:11});await page.evaluate(id=>{const g=(window as any).__dongshan.game,d=g.dogs.actor(id);g.dogs.cancel(d);d.target=g.world.approach({x:8,z:12},d);for(let k=0;k<900&&Math.hypot(d.x-8,d.z-12)>1;k++)g.tick(1/30);},q.dog);assert.ok(await page.evaluate(id=>(window as any).__dongshan.game.dogs.follow(id),q.dog));await walk(q.goal,true);const done=await page.evaluate(({id,dog})=>{const d=(window as any).__dongshan.game.dogs.actor(dog);return {ok:(d as any).routeDone===id,state:d.state,x:d.x,z:d.z,started:(d as any).routeStarted,route:(d as any).routeDone,stuck:d.stuck,followTime:d.followTime,player:(window as any).__dongshan.game.player};},{id:q.id,dog:q.dog});assert.ok(done.ok,JSON.stringify({quest:q.id,...done}));}
 await page.screenshot({path:'artifacts/dogs-quest-'+q.id+'.png'});const position=await page.evaluate(()=>{const n=(window as any).__dongshan.game.npcs.find((n:any)=>n.type==='science_teacher');return {x:n.x,z:n.z};});await walk(position);assert.ok(await page.evaluate(()=>(window as any).__dongshan.game.dogs.checkDelivery()));results.push({id:q.id,...await page.evaluate(id=>{const g=(window as any).__dongshan.game;return {progress:g.dogs.p.dogs[id],treats:g.dogs.p.treats,items:[...g.objects.values()].filter((i:any)=>i.type.startsWith('dog_')).map((i:any)=>i.id)};},q.dog)});
}
assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/dogs-route-qa.json',JSON.stringify({method:'Original furniture/walls and navigation. Player walks every waypoint via fixed-step movement input, takes original quest item through E interaction, E marker placement and teacher delivery. Task-only dog follows actual courtyard-to-goal path. No player teleport or direct quest awards.',results,errors},null,2));await browser.close();console.log('All six dog quests completed through real campus navigation and interactions.');
