import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1280,height:800}});await context.addInitScript('window.__name = value => value');
const page=await context.newPage(),errors:string[]=[],failed:string[]=[],shots:string[]=[],checks:any[]=[],performance:any[]=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
await page.goto(process.env.QA_URL||'http://127.0.0.1:5174/');assert.match(await page.locator('.welcome .fine').innerText(),/v1.2/);await page.locator('[data-action=start]').click();await page.locator('#skip').click();
const shot=async(name:string)=>{const path='artifacts/dogs-'+name+'.png';await page.screenshot({path});shots.push(path);};
const prep=async()=>page.evaluate(()=>{const {game:g,ui,render:r}=(window as any).__dongshan;if(g.meeting.running){g.meeting.endReason='驗收散場';g.meeting.finish();}g.reset('normal');ui.close();ui.paused=true;g.player.inv=99;Object.assign(g.player,{x:8,z:9,face:{x:0,z:1}});for(const d of g.dogs.actors)Object.assign(d,{x:d.id==='dog_lion'?7:9,z:11,state:'Rest',job:null});const n=g.npcs.find((n:any)=>n.type==='science_teacher');Object.assign(n,{x:8,z:12,active:true,state:'Idle'});r.target.set(8,0,10);r.frame(.1,false,1);});
await prep();await shot('two-friends');
await page.locator('#dogs-entry').click();assert.equal(await page.locator('.dog-status').count(),2);assert.equal(await page.locator('.dog-status img').count(),2);await shot('cards');await page.locator('[data-action=close]').first().click();
await page.evaluate(()=>{const {game:g,ui,r}=(window as any).__dongshan;ui.paused=true;Object.assign(g.player,{x:7,z:10});g.dogs.pet('dog_lion');for(let k=0;k<18;k++)g.tick(1/30);});await shot('pet-lion');
await page.evaluate(()=>{const {game:g,ui,render:r}=(window as any).__dongshan;ui.paused=true;g.dogs.cancelAll();g.dogs.nextFeed=0;const n=g.npcs.find((n:any)=>n.type==='science_teacher');Object.assign(n,{x:8,z:11,state:'Idle',active:true});g.pathBudget=4;g.dogs.teacher(.1);r.frame(.1,false,1);});await shot('teacher-feeding');
const teacherMatrix:any[]=[];
for(const state of ['Idle','ScienceWalk','ScienceFeed','Walk','Investigate'])for(const method of ['bare','held','throw']){
 await prep();await page.evaluate(({state,method})=>{const {game:g,ui,render:r,input}=(window as any).__dongshan;ui.paused=true;input.enabled=true;g.npcs=g.npcs.filter((n:any)=>n.type==='science_teacher');g.props=[];g.layout.furniture=[];g.refreshColliders();const n=g.npcs[0];Object.assign(n,{x:8,z:11,hp:60,state,active:true});Object.assign(g.player,{x:8,z:10,face:{x:0,z:1},item:null,attackCooldown:0,attack:null});if(method!=='bare'){g.createItem('folder','qa:folder',g.player);g.take('qa:folder');}},{state,method});
 await page.keyboard.press(method==='throw'?'KeyQ':'KeyJ');const result=await page.evaluate(()=>{const {game:g,render:r}=(window as any).__dongshan;for(let k=0;k<5;k++)g.tick(1/30);r.frame(.1,false,1);const n=g.npcs[0];return {hp:n.hp,state:n.state,x:n.x,z:n.z,events:g.eventLog.filter((e:any)=>e.type==='CombatResolved').length};});assert.ok(result.hp<60,JSON.stringify({state,method,result}));assert.ok(result.z>11);teacherMatrix.push({initialState:state,method,...result});if(state==='ScienceFeed')await shot('teacher-hit-'+method);
}
for(const id of ['dog_lion','dog_mani']){
 await prep();await page.evaluate(id=>{const {game:g,ui}=(window as any).__dongshan;ui.paused=true;g.npcs=g.npcs.filter((n:any)=>n.type==='science_teacher');g.props=[];g.layout.furniture=[];g.refreshColliders();const d=g.dogs.actor(id);Object.assign(d,{x:8.6,z:11});Object.assign(g.npcs[0],{x:8,z:11.5,state:'Chase',active:true});g.dogs.p.dogs[id].affinity=75;g.dogs.p.assistCooldown=0;g.dogs.select(g.npcs[0].id);g.dogs.assist(id);g.pathBudget=4;g.dogs.tick(.1);},id);const result=await page.evaluate(()=>{const {game:g,render:r,ui}=(window as any).__dongshan;ui.toastUntil=0;r.frame(.1,false,1);return {states:g.dogs.actors.map((d:any)=>d.state),cooldown:g.dogs.p.assistCooldown,hp:g.npcs[0].hp};});assert.ok(result.states.includes('AssistContact'));assert.equal(result.hp,60);assert.equal(result.cooldown,20);await shot('assist-'+id);checks.push({id,...result});
}
await prep();await page.evaluate(()=>{const {game:g,ui}=(window as any).__dongshan;ui.paused=true;g.dogs.p.dogs.dog_lion.affinity=75;g.meeting.start(5,['dog_observer','printer','voting']);g.tick(.4);g.meeting.activate();g.meeting.testHold=true;});await shot('observer');
const humanMatrix:any[]=[];for(const index of [0,1,2,3])for(const method of ['bare','held','throw']){
 await page.evaluate(({index,method})=>{const {game:g,ui,input}=(window as any).__dongshan;ui.paused=true;input.enabled=true;g.meeting.chaos=0;g.meeting.hits.clear();g.meeting.timers.clear();g.meeting.elapsed=0;g.dogs.cancelAll();for(const n of g.npcs)Object.assign(n,{...n.home,hp:3,state:'Seated',timer:99});const n=g.npcs[index];Object.assign(g.player,{x:n.x+(n.x>0?1.05:-1.05),z:n.z,face:{x:n.x>0?-1:1,z:0},attack:null,attackCooldown:0});if(g.held)g.drop();if(method!=='bare'){const i=[...g.objects.values()].find((i:any)=>i.type==='folder');g.detach(i);i.state='settled';g.take(i.id);}},{index,method});await page.keyboard.press(method==='throw'?'KeyQ':'KeyJ');const result=await page.evaluate(index=>{const {game:g,render:r}=(window as any).__dongshan;for(let k=0;k<6;k++)g.tick(1/30);r.frame(.1,false,1);return {hp:g.npcs[index].hp,state:g.npcs[index].state,dogs:g.dogs.visible.length};},index);assert.ok(result.hp<3,JSON.stringify({index,method,result}));assert.equal(result.dogs,1);humanMatrix.push({index,method,...result});}
await page.evaluate(()=>{const {game:g,render:r}=(window as any).__dongshan;Object.assign(g.player,{x:1.3,z:7});g.player.attack=null;g.player.item=null;g.dogs.cancelAll();g.dogs.pet('dog_lion');for(let k=0;k<19;k++)g.tick(1/30);r.target.set(0,0,5);r.frame(.1,false,1);});await shot('observer-pet');
await page.evaluate(()=>{const {game:g,ui}=(window as any).__dongshan;g.meeting.endReason='驗收離席';g.meeting.finish();ui.toastUntil=0;ui.open('codex');});assert.equal(await page.locator('.codex-thumb').count(),41);assert.ok(await page.locator('.codex-thumb').evaluateAll((images:any)=>images.every((i:any)=>i.complete&&i.naturalWidth>0)));await shot('codex');await page.locator('[data-action=close]').first().click();
await prep();await page.evaluate(()=>{const {game:g,render:r}=(window as any).__dongshan;Object.assign(g.player,{x:-12,z:-17});r.target.set(-17,0,-17);r.frame(.1,false,1);});await shot('readable-labels');
await page.setViewportSize({width:390,height:844});await prep();await page.locator('#quest-toggle').click();assert.equal(await page.locator('.quest').evaluate(e=>getComputedStyle(e).width),'172px');assert.equal(await page.locator('.action-cluster small').first().evaluate(e=>getComputedStyle(e).marginTop),'0px');const centered=await page.locator('#quest-chevron').evaluate(e=>{const r=e.getBoundingClientRect(),p=e.parentElement!.getBoundingClientRect();return Math.abs(r.y+r.height/2-p.y-p.height/2)});assert.ok(centered<1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('mobile');await page.locator('#dogs-entry').click();await shot('mobile-cards');await page.locator('[data-action=close]').first().click();await page.setViewportSize({width:1280,height:800});
async function measure(name:string,prepare:string){await prep();await page.evaluate(prepare);await page.evaluate(()=>{const {ui,render:r}=(window as any).__dongshan;r.setDPR();r.frames=[];ui.paused=false;});await page.waitForTimeout(4000);performance.push({name,...await page.evaluate(()=>{const {game:g,render:r,ui}=(window as any).__dongshan;ui.paused=true;return {...r.measure(),dogAI:g.dogs.visible.filter((d:any)=>d.active).length,totalAI:g.npcs.filter((n:any)=>n.active).length+g.dogs.visible.filter((d:any)=>d.active).length};})});}
await measure('普通校園',"const {game:g} = window.__dongshan;g.profile.settings.quality='low';");
await measure('老師餵兩狗',"const {game:g} = window.__dongshan;g.profile.settings.quality='low';g.dogs.nextFeed=0;Object.assign(g.npcs.find(n=>n.type==='science_teacher'),{x:8,z:11});");
await measure('追逐中協助',"const {game:g} = window.__dongshan;g.profile.settings.quality='low';const n=g.npcs.find(n=>n.type==='science_teacher');Object.assign(n,{x:8,z:11.5,state:'Chase',active:true});Object.assign(g.dogs.actor('dog_lion'),{x:8.6,z:11});g.dogs.p.dogs.dog_lion.affinity=75;g.dogs.select(n.id);g.dogs.assist('dog_lion');");
await measure('狗旁聽加列印表決',"const {game:g} = window.__dongshan;g.profile.settings.quality='low';g.dogs.p.dogs.dog_lion.affinity=75;g.meeting.start(5,['dog_observer','printer','voting']);g.tick(.4);g.meeting.activate();g.meeting.testHold=true;");
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);fs.writeFileSync('artifacts/dogs-browser-qa.json',JSON.stringify({date:new Date().toISOString(),browser:browser.version(),viewport:'1280x800 / 390x844',renderer:'Chromium headless SwiftShader',mobileHardware:'未實機驗證',teacherMatrix,humanMatrix,checks,centered,shots,performance,errors,failed},null,2));await browser.close();console.log('Dogs real browser QA passed: teacher15, observer humans12, both assists, mobile, thumbnails and four performance scenes.');
