import {chromium} from '@playwright/test';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:false});
try{
 const page=await browser.newPage({viewport:{width:1440,height:900},hasTouch:true});const errors:string[]=[],layouts:any[]=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript('window.__name=v=>v');await page.goto(process.env.QA_URL||'http://127.0.0.1:5173');await page.locator('[data-action=start]').click();await page.locator('#skip').click();
 async function stable(){await page.waitForTimeout(250)}
 for(const size of [{width:1440,height:900},{width:820,height:1180},{width:390,height:844},{width:844,height:390}]){
  await page.setViewportSize(size);
  for(const hp of [100,25,10]){
   await page.evaluate(hp=>{const d=(window as any).__dongshan;d.game.player.hp=hp;d.game.player.inv=9999;d.game.meeting.troubleParents=3;d.ui.update(.2)},hp);await stable();
   for(const collapse of [false,true]){
    await page.evaluate(v=>(window as any).__dongshan.ui.setQuestCollapsed(v),collapse);await stable();
    const r=await page.evaluate(()=>{const rect=(s:string)=>{const r=document.querySelector(s)!.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,w:r.width,h:r.height}};return {status:rect('.top-left'),quest:rect('.quest'),nav:rect('.side-nav'),joystick:rect('#joystick'),health:document.querySelector('.status-card')!.getAttribute('data-health')}});
    assert.ok(r.nav.y>=r.status.bottom+9,JSON.stringify({size,hp,r}));if(size.width<=900&&size.height>500){assert.ok(r.quest.y>=r.status.bottom+9);assert.ok(r.nav.y>=r.quest.bottom+9)}
    const overlap=(a:any,b:any)=>a.x<b.right&&a.right>b.x&&a.y<b.bottom&&a.bottom>b.y;assert.equal(overlap(r.nav,r.joystick),false,JSON.stringify({size,hp,r}));layouts.push({size,hp,collapse,...r});
   }
  }
  await page.evaluate(()=>{const d=(window as any).__dongshan;d.game.player.hp=100;d.ui.setQuestCollapsed(false);d.ui.update(.2)});await stable();await page.screenshot({path:`artifacts/feedback-hud-${size.width}x${size.height}.png`});
 }
 await page.setViewportSize({width:1440,height:900});
 await page.evaluate(()=>{const d=(window as any).__dongshan,g=d.game;g.reset();g.finishTutorial();g.profile.life.nextMain=g.profile.life.nextSide=1e8;const paper=[...g.objects.values()].find((i:any)=>i.type==='exam_papers');g.player.x=paper.x;g.player.z=paper.z;g.take(paper.id);g.player.x=-19.6;g.player.z=-18;g.player.inv=999;d.render.target.set(g.player.x,0,g.player.z);d.render.frame(.1);d.ui.update(.2)});await stable();
 const goals=await page.evaluate(()=>{const d=(window as any).__dongshan;return {goals:d.render.visibleGoals,meshes:d.render.goalMeshes.map(m=>({count:m.count,depthTest:m.material.depthTest,depthWrite:m.material.depthWrite,order:m.renderOrder})),point:d.render.project({x:-21,z:-19},1.15),nearest:d.game.nearest()?.id,held:d.game.held.id}});
 assert.ok(goals.goals.some(g=>g.label==='放下考卷'));assert.ok(goals.meshes.every(m=>m.count>0&&!m.depthTest&&!m.depthWrite));assert.equal(goals.nearest,'tutorial:podium');
 await page.screenshot({path:'artifacts/feedback-exam-marker-mac.png'});const c={x:Math.max(0,Math.floor(goals.point.x-80)),y:Math.max(0,Math.floor(goals.point.y-80)),width:160,height:160};await page.screenshot({path:'artifacts/feedback-exam-marker-crop.png',clip:c});await page.keyboard.press('e');
 const delivered=await page.evaluate(()=>{const d=(window as any).__dongshan;const item=d.game.objects.get(d.game.eventLog.findLast(e=>e.type==='drop').data.id);return {held:d.game.player.item,id:item.id,x:item.x,z:item.z,y:item.y,ownership:d.game.assertOwnership()}});assert.equal(delivered.held,null);assert.equal(delivered.id,goals.held);assert.equal(delivered.x,-21);assert.ok(delivered.y>=1);
 await page.evaluate(()=>{const d=(window as any).__dongshan,g=d.game;g.reset();g.finishTutorial();g.profile.life.nextMain=g.profile.life.nextSide=1e8;g.player.x=0;g.player.z=8;g.player.inv=999;g.player.face={x:0,z:1};const n=g.npcs.find(n=>n.role==='student');for(const other of g.npcs){other.x=35;other.z=27}Object.assign(n,{x:0,z:9,hp:100,state:'Idle',active:true,timer:30,target:null});d.render.target.set(g.player.x,0,g.player.z);d.render.frame(.1);(window as any).__hitNpc=n.id;(window as any).__shakes=[];const start=performance.now();function sample(){(window as any).__shakes.push({...d.render.shakeOffset});if(performance.now()-start<500)requestAnimationFrame(sample)}requestAnimationFrame(sample);});
 await page.keyboard.press('j');await page.waitForSelector('.hit-label');await page.screenshot({path:'artifacts/feedback-hit.png'});const hit=await page.evaluate(()=>{const d=(window as any).__dongshan;return {events:d.game.eventLog.filter(e=>e.type==='CombatResolved').length,labels:document.querySelector('#hit-feedback').textContent,hp:d.game.npcs.find(n=>n.id===(window as any).__hitNpc).hp}});assert.equal(hit.events,1);assert.match(hit.labels,/命中 −/);await page.waitForTimeout(650);assert.equal(await page.locator('.hit-label').count(),0);assert.ok(await page.evaluate(()=>(window as any).__shakes.some(s=>Math.abs(s.x)+Math.abs(s.z)>0)));
 // Empty swing produces no successful hit labels.
 await page.evaluate(()=>{const d=(window as any).__dongshan;for(const n of d.game.npcs){n.x=35;n.z=27}d.game.player.attackCooldown=0});await page.keyboard.press('j');await page.waitForTimeout(250);assert.equal(await page.locator('.hit-label').count(),0);
 await page.evaluate(()=>{const d=(window as any).__dongshan;d.game.player.hp=10;d.game.profile.settings.lowMotion=true;d.ui.update(.2)});await stable();assert.equal(await page.locator('#health-vignette').isVisible(),true);assert.equal(await page.locator('#health-vignette').evaluate(e=>getComputedStyle(e).animationName),'none');assert.match(await page.locator('#health-warning').innerText(),/危急/);await page.screenshot({path:'artifacts/feedback-low-health.png'});
 await page.evaluate(()=>{const d=(window as any).__dongshan;d.game.player.attackCooldown=0;const n=d.game.npcs.find(n=>n.role==='student');Object.assign(n,{x:d.game.player.x,z:d.game.player.z+.8,hp:100,state:'Idle',active:true});d.game.player.face={x:0,z:1}});await page.keyboard.press('j');await page.waitForSelector('.hit-label');assert.equal(await page.evaluate(()=>{const s=(window as any).__dongshan.render.shakeOffset;return Math.abs(s.x)+Math.abs(s.z)}),0);
 await page.evaluate(()=>{const d=(window as any).__dongshan;d.game.reset();d.ui.update(.2)});await stable();assert.equal(await page.locator('#health-vignette').isVisible(),false);assert.equal(await page.locator('#health-warning').isVisible(),false);assert.equal(await page.locator('.hit-label').count(),0);
 assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/feedback-browser-qa.json',JSON.stringify({date:'2026-10-09',status:'pass',browser:await browser.version(),environment:'macOS native Chromium, desktop and viewport/touch emulation',layouts,goals,delivered,hit,checks:['24 layout combinations, expanded/collapsed, no panel/nav/joystick overlaps','skipped tutorial + held exam shows unobscured podium ring','real E places same paper instance on podium','real J successful hit gives actual damage text and short shake','empty swing has no hit text','lowMotion retains static critical health edge/warning and disables shake','recovery/reset removes warning and hit labels'],errors,limitations:['Physical phones, Safari/macOS Safari and human comfort review not tested.','NPC and paper initial positions prepared using existing dev interface; E/J are real keyboard input.']},null,2));console.log(JSON.stringify({status:'pass',layouts:layouts.length,goals,hit,errors}));
}finally{await browser.close()}
