import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1280,height:800}});await page.addInitScript('window.__name=v=>v');const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.QA_URL||'http://127.0.0.1:5174');await page.locator('[data-action=start]').click();await page.locator('#skip').click();
const receipts:any[]=[];
async function init(){await page.evaluate(()=>{const {game:g,ui,input}=(window as any).__dongshan;g.reset('normal');g.profile.life.clock=0;g.profile.life.nextMain=g.profile.life.nextSide=1e8;g.profile.life.achievements=[];ui.paused=true;input.enabled=true;g.player.inv=99;for(const n of g.npcs)n.timer=-999;});}
async function walk(goal:{x:number,z:number}){const result=await page.evaluate(goal=>{const g=(window as any).__dongshan.game;const target=g.world.approach(goal,g.player),path=g.world.path(g.player,target);let ticks=0;for(const next of path)while(Math.hypot(g.player.x-next.x,g.player.z-next.z)>.2&&ticks++<4000){const dx=next.x-g.player.x,dz=next.z-g.player.z,m=Math.hypot(dx,dz);g.tick(1/30,{x:dx/m,z:dz/m,run:true});}return {ok:path.length>0&&Math.hypot(g.player.x-target.x,g.player.z-target.z)<.6,ticks,blocked:g.world.blocked(g.player,.31),player:{x:g.player.x,z:g.player.z}};},goal);assert.ok(result.ok,JSON.stringify(result));assert.equal(result.blocked,false);receipts.push({walk:result});}
async function advance(seconds:number){await page.evaluate(s=>{const g=(window as any).__dongshan.game;for(let t=0;t<s;t+=1/30)g.tick(1/30);},seconds);}
async function start(kind:string,seed:number){const result=await page.evaluate(({kind,seed})=>{const g=(window as any).__dongshan.game;const c=g.life.start(kind,seed);if(!c)return null;for(let t=0;t<80&&c.stage===0&&g.life.cases.includes(c);t+=1/30)g.tick(1/30);return {id:c.id,stage:c.stage,points:c.points,items:c.items,actors:c.actors,breakAt:c.breakAt,thief:c.thief,owner:c.owner,parent:c.parent};},{kind,seed});assert.ok(result);assert.equal(result.stage,1);return result;}
async function shot(name:string){await page.evaluate(()=>{const {game:g,render:r,ui}=(window as any).__dongshan;r.target.set(g.player.x,0,g.player.z);r.frame(.1,false,1);ui.update(.2);});await page.screenshot({path:`artifacts/life-${name}.png`});}
async function key(key:string){await page.keyboard.press(key);}
await init();await walk({x:-25.4,z:-19.4});await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.player.hp=65;g.life.p.pendingMeal={seed:42,abnormal:true};});await key('e');await advance(1.2);await shot('01-lunch');assert.equal(await page.evaluate(()=>(window as any).__dongshan.game.player.hp),85);receipts.push({lunch:await page.evaluate(()=>(window as any).__dongshan.game.profile.life)});
await init();const milk=await start('milk',11);await advance(3);await walk({x:-10,z:-8.8});await key('e');assert.equal(await page.evaluate(()=>(window as any).__dongshan.game.held?.type),'mop');await walk({x:milk.points[1].x-1.3,z:milk.points[1].z+1.2});await advance(31);await shot('02-milk-sour');await key('e');await advance(1.6);assert.ok(await page.evaluate(()=>(window as any).__dongshan.game.profile.life.achievements.includes('牛奶不是放越久越好')));await shot('02-milk-cleaned');
await init();const baseball=await start('baseball',2);await walk({x:baseball.points[1].x+1.5,z:baseball.points[1].z+1.2});await shot('03-baseball');await advance(4*baseball.breakAt+1);await shot('03-baseball-break');assert.ok(await page.evaluate(()=>(window as any).__dongshan.game.profile.life.achievements.includes('本校棒球隊尚未成立')));
await init();const theft=await start('theft',11);await walk(theft.points[1]);await shot('04-theft-clues');const attack=await page.evaluate(id=>{const g=(window as any).__dongshan.game,n=g.npcs.find((n:any)=>n.id===id);g.player.face={x:n.x-g.player.x,z:n.z-g.player.z};const d=Math.hypot(g.player.face.x,g.player.face.z);g.player.face.x/=d;g.player.face.z/=d;g.player.inv=0;g.alert=48;return {distance:d,before:n.hp};},theft.thief);assert.ok(attack.distance<1.55);await key('j');await advance(.18);const top=await page.evaluate(id=>{const g=(window as any).__dongshan.game,i=g.objects.get(id);return {owner:i.owner,x:i.x,z:i.z};},theft.items[0]);assert.equal(top.owner,null);await shot('04-theft-recovery');await walk(top);await key('e');assert.equal(await page.evaluate(()=>(window as any).__dongshan.game.held?.id),theft.items[0]);const owner=await page.evaluate(id=>{const n=(window as any).__dongshan.game.npcs.find((n:any)=>n.id===id);return {x:n.x,z:n.z};},theft.owner);await walk(owner);await page.evaluate(()=>{const g=(window as any).__dongshan.game,n=g.npcs.find((n:any)=>n.type==='dean');n.state='Chase';g.alert=67;});await key('e');assert.equal(await page.evaluate(()=>(window as any).__dongshan.game.alert),59);assert.equal(await page.evaluate(()=>(window as any).__dongshan.game.npcs.find((n:any)=>n.type==='dean').state),'Chase');await shot('04-theft-alert-isolation');receipts.push({theft:await page.evaluate(()=>(window as any).__dongshan.game.profile.life.ledger.slice(-8))});
await init();const patrol=await start('patrol',11);await walk(patrol.points[0]);await shot('05-patrol');const teacher=await page.evaluate(()=>{const n=(window as any).__dongshan.game.npcs.find((n:any)=>n.type==='patrol_teacher');return {x:n.x,z:n.z};});await walk(teacher);await key('e');assert.ok(await page.evaluate(()=>(window as any).__dongshan.game.life.cases[0]?.reported));await advance(40);assert.ok(await page.evaluate(()=>(window as any).__dongshan.game.profile.life.achievements.includes('科展先暫停一下')));
await init();const assembly=await start('assembly',0);const t=await page.evaluate(()=>{const n=(window as any).__dongshan.game.npcs.find((n:any)=>n.type==='patrol_teacher');return {x:n.x,z:n.z};});await walk(t);await key('e');await walk({x:assembly.points[3].x+2,z:assembly.points[3].z+1.7});await shot('06-assembly-phone');await advance(35);assert.ok(await page.evaluate(()=>(window as any).__dongshan.game.profile.life.achievements.includes('排位不能缺席，升旗也不能')));await walk({x:0,z:5});await shot('06-assembly-return');
await init();await page.evaluate(()=>{const {game:g,ui}=(window as any).__dongshan;ui.open('life');});assert.equal(await page.locator('.panel').getByText('○', {exact:false}).count(),6);await page.screenshot({path:'artifacts/life-menu.png'});
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{const {ui,game:g}=(window as any).__dongshan;ui.close();ui.paused=true;ui.setQuestCollapsed(true);g.player.x=9;g.player.z=-18;});await shot('mobile');
const performance:any[]=[];await page.setViewportSize({width:1280,height:800});for(const scenario of ['baseline','lunch-two-sides','theft-chase','patrol']){await init();await page.evaluate(s=>{const {game:g,ui,render:r}=(window as any).__dongshan;g.profile.settings.quality='low';r.setDPR();if(s==='lunch-two-sides'){g.life.p.clock=245;g.life.start('milk',2);g.life.start('baseball',3);g.player.x=-20;g.player.z=-16;}if(s==='theft-chase'){g.life.start('theft',4);g.npcs.find((n:any)=>n.type==='dean').state='Chase';g.player.x=-18;g.player.z=-19;}if(s==='patrol'){g.life.start('patrol',11);g.player.x=9;g.player.z=-18;}if(s!=='baseline'){for(let k=0;k<2400&&g.life.cases.some((c:any)=>c.stage===0);k++)g.tick(1/30);if(s==='lunch-two-sides'){for(let k=0;k<90;k++)g.tick(1/30);for(const p of g.life.puddles)p.age=65;}}ui.paused=false;r.frames=[];},scenario);await page.waitForTimeout(4000);performance.push({scenario,...await page.evaluate(()=>{const {render:r,game:g}=(window as any).__dongshan;return {...r.measure(),reservedStudents:g.life.cases.flatMap((c:any)=>c.actors).filter((id:string)=>id.startsWith('student:')).length,puddles:g.life.puddles.length,smoke:g.life.visuals().filter((v:any)=>v.type==='life_smoke').length};})});}
await page.evaluate(()=>(window as any).__dongshan.ui.paused=true);assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/life-browser-qa.json',JSON.stringify({browser:await browser.version(),viewport:'1280x800; mobile 390x844',errors,receipts,performance},null,2));await browser.close();console.log(JSON.stringify({screenshots:13,errors,performance},null,2));
