import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1280,height:800}});await page.addInitScript('window.__name=v=>v');const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5175');await page.locator('[data-action=start]').click();await page.locator('#skip').click();
async function init(){await page.evaluate(()=>{const {game:g,ui,input}=(window as any).__dongshan;g.reset('normal');g.profile.life.nextMain=g.profile.life.nextSide=1e8;ui.paused=true;input.enabled=true;g.player.inv=99;});}
async function shot(name:string){await page.evaluate(()=>{const {game:g,render:r,ui}=(window as any).__dongshan;r.target.set(g.player.x,0,g.player.z);r.frame(.1,false,1);ui.update(.2);});await page.waitForTimeout(300);await page.screenshot({path:`artifacts/meeting-ui-${name}.png`});}
await init();await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.player.x=-21;g.player.z=-16;});await shot('classroom');
await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.player.x=-21;g.player.z=-2;});await shot('music');
for(const id of ['dog_lion','dog_mani']){await init();await page.evaluate(id=>{const g=(window as any).__dongshan.game,d=g.dogs.actor(id);g.player.x=d.x+1;g.player.z=d.z;g.dogs.p.dogs[id].affinity=20;g.dogs.p.dogs[id].cooldowns.pet=0;},id);await page.keyboard.press('e');await page.evaluate(()=>{const g=(window as any).__dongshan.game;for(let i=0;i<22;i++)g.tick(1/30);});assert.equal(await page.locator('.toast-dog-face svg').count(),1);await shot(id);await page.waitForTimeout(3100);await page.evaluate(()=>(window as any).__dongshan.ui.update(.2));assert.equal(await page.locator('#toast').evaluate(e=>e.classList.contains('visible')),false);}
await init();await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{const {game:g,ui}=(window as any).__dongshan;ui.setQuestCollapsed(true);const i=[...g.objects.values()].find((i:any)=>i.type==='textbook');g.take(i.id);});await shot('mobile-drop');assert.equal(await page.locator('#drop').isVisible(),true);assert.equal(await page.locator('#quest-chevron').textContent(),'▽');assert.equal(await page.locator('#quest-chevron').evaluate(e=>getComputedStyle(e).fontSize),'12px');assert.equal(await page.locator('.quest-caption').evaluate(e=>getComputedStyle(e).display),'none');
const rects:any={};for(const id of ['drop','throw','interact','attack','dodge'])rects[id]=await page.locator('#'+id).boundingBox();for(const id of ['throw','interact','attack','dodge']){const a=rects.drop,b=rects[id];assert.ok(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y,`drop overlaps ${id}`);}
await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.dogs.p.dogs.dog_mani.affinity=99;g.dogs.gain('dog_mani',5,'qa:mobile');});assert.match(await page.locator('#toast').innerText(),/好感 \+1/);assert.equal(await page.locator('.toast-dog-face').evaluate(e=>e.getBoundingClientRect().width),48);await shot('mobile-smile');await page.evaluate(()=>(window as any).__dongshan.game.dogs.gain('dog_mani',5,'qa:cap'));assert.equal(await page.locator('.toast-dog-face').count(),0);await page.evaluate(()=>(window as any).__dongshan.game.toast('一般訊息'));assert.equal(await page.locator('.toast-dog-face').count(),0);
const held=await page.evaluate(()=>(window as any).__dongshan.game.held.id);await page.locator('#drop').click();assert.equal(await page.evaluate(()=>(window as any).__dongshan.game.held),null);assert.equal(await page.evaluate(id=>(window as any).__dongshan.game.objects.get(id).owner,held),null);
await page.setViewportSize({width:844,height:390});await page.evaluate(()=>{const {game:g,ui}=(window as any).__dongshan;g.take([...g.objects.values()].find((i:any)=>i.type==='textbook').id);ui.update(.2);});await shot('landscape-drop');await page.locator('#drop').click();
await page.setViewportSize({width:1280,height:800});await init();await page.evaluate(()=>{const g=(window as any).__dongshan.game;for(let i=0;i<3;i++)g.spawnParent('spatula');g.meeting.gateSeed=0;});await page.keyboard.press('j');assert.equal(await page.evaluate(()=>(window as any).__dongshan.game.meeting.gateRolls),1);await shot('summons');await page.evaluate(()=>{const g=(window as any).__dongshan.game;for(let i=0;i<110;i++)g.tick(1/30);});assert.equal(await page.evaluate(()=>(window as any).__dongshan.game.meeting.running),true);await shot('meeting');assert.ok(await page.evaluate(()=>(window as any).__dongshan.game.player.hp>0));assert.deepEqual(errors,[]);
fs.writeFileSync('artifacts/meeting-ui-browser-qa.json',JSON.stringify({browser:await browser.version(),errors,mobileRects:rects,screenshots:9,checks:['actual E pet for both dogs; portrait and toast disappear together','mobile portrait is 48px; capped gain shows actual +1; full affinity has no portrait','mobile drop pointer action preserves original item ID','390x844 drop button does not overlap other circles','844x390 landscape drop usable','12px triangle chevron; caption span display none','three actual parent arrivals and real J summons at positive HP']},null,2));await browser.close();console.log('9 screenshots; browser checks passed; no page errors');

