import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {modules} from '../src/meeting-data';
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']}),page=await browser.newPage({viewport:{width:1280,height:800}});await page.addInitScript('window.__name=v=>v');const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5174');await page.locator('[data-action=start]').click();await page.locator('#skip').click();const results:any[]=[];
for(const module of modules){const prep=await page.evaluate(id=>{const {game:g,ui,input,render:r}=(window as any).__dongshan;if(g.meeting.running){g.meeting.endReason='測試離席';g.meeting.finish();}g.profile.meeting.cooldown=0;if(id==='dog_observer')g.dogs.p.dogs.dog_lion.affinity=75;g.meeting.start(2026,[id,id==='projector'?'cross_talk':'projector'],'shop_aunt');g.tick(.4);g.meeting.activate();g.meeting.testHold=true;ui.close();ui.paused=true;input.enabled=true;g.meeting.elapsed=18;g.player.inv=99;const item=[...g.objects.values()].find((i:any)=>i.module===id);if(item)g.take(item.id);Object.assign(g.player,{x:-.85,z:1.3,face:{x:1,z:0}});g.npcs[0].state='Speaking';g.npcs[0].timer=99;if(id==='cross_talk'){g.take([...g.objects.values()].find(i=>i.type==='folder').id);}if(id==='paper_planes')g.take([...g.objects.values()].find(i=>i.type==='meeting_report').id);if(id==='dog_observer')Object.assign(g.player,{x:1.3,z:7});if(id==='whiteboard')Object.assign(g.player,{x:4.5,z:8.8});if(id==='sleepy_member'){const n=g.npcs.find(n=>n.id===g.meeting.sleepId);n.state='Sleeping';n.timer=99;const side=n.x>0?1:-1;Object.assign(g.player,{x:n.x+side*.85,z:n.z,face:{x:-side,z:0}});}if(id==='guest_mediator'){const n=g.npcs[3];n.state='Coordinating';n.timer=99;Object.assign(g.player,{x:n.x+.85,z:n.z,face:{x:-1,z:0}});}if(id==='musical_chairs'){const i=[...g.objects.values()].find(i=>i.id.endsWith('chair:0'));i.x+=1.6;g.refreshColliders();}r.target.set(0,0,5);r.frame(.1,false,1);return {objects:g.objects.size,npcs:g.npcs.length,item:item?.type};},module.id);
 const key=module.id==='dog_observer'?'KeyE':['reenactment','sleepy_member','guest_mediator'].includes(module.id)?'KeyJ':['tea_spill','cross_talk'].includes(module.id)?'KeyQ':module.id==='printer'?'':'KeyF';if(key)await page.keyboard.press(key);
 await page.evaluate(id=>{const {game:g,r,render,ui}=(window as any).__dongshan;for(let k=0;k<(id==='musical_chairs'?170:70);k++)g.tick(1/30);if(id==='voting'){g.drop();g.meeting.vote();}render.frame(.1,false,1);ui.update(.3);},module.id);
 if(module.id==='paper_planes'){await page.keyboard.press('KeyQ');await page.evaluate(()=>{const g=(window as any).__dongshan.game;for(let k=0;k<20;k++)g.tick(1/30);});}
 const result=await page.evaluate(id=>{const {game:g,render:r,ui}=(window as any).__dongshan;r.frame(.1,false,1);ui.update(.3);return {feature:g.meeting.done.has(id),chaos:g.meeting.chaos,states:g.npcs.map(n=>n.state),objects:g.objects.size,npcs:g.npcs.length};},module.id);assert.ok(result.feature,module.id);assert.equal(result.npcs,4);await page.screenshot({path:`artifacts/meeting-module-${module.id}.png`});
 const cleanup=await page.evaluate(()=>{const {game:g,render:r}=(window as any).__dongshan;const n=g.npcs.find(n=>n.hp>0);g.damageNPC(n,1,'module-interrupt');for(let k=0;k<150;k++)g.tick(1/30);const recovered=n.hp>0;const world=g.meeting.snapshot;g.meeting.leave();for(let k=0;k<50&&g.meeting.running;k++)g.tick(1/30);r.frame(.1,false,1);return {recovered,phase:g.meeting.phase,originalObjects:g.objects===world.objects,originalNPCs:g.npcs===world.npcs,temp:[...g.objects.values()].filter((i:any)=>i.meetingOnly).length,timers:g.meeting.timers.size,textures:r.measure().textures,geometries:r.measure().geometry};});assert.ok(cleanup.recovered);assert.equal(cleanup.phase,'CAMPUS');assert.ok(cleanup.originalObjects&&cleanup.originalNPCs);assert.equal(cleanup.temp,0);assert.equal(cleanup.timers,0);results.push({id:module.id,label:module.label,prep,result,cleanup});}
assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/meeting-modules-qa.json',JSON.stringify({date:new Date().toISOString(),browser:browser.version(),method:'Dev preparation selects each module and legal starting positions/states. Real keyboard J/Q/F dispatches gameplay methods; simulation steps run 30Hz. Printer tests actual take. No direct characteristic award calls. Rendering screenshots and sequential cleanup check use real renderer.',results,errors},null,2));await browser.close();console.log('PASS all 16 module keyboard characteristic interactions, interrupt/recovery, sequential cleanup, rendered screenshots');
