import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1280,height:800}});await context.addInitScript('window.__name = value => value');
const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');await page.locator('[data-action=start]').click();await page.locator('#skip').click();
const enter=async(selected:string[],guest='shop_aunt')=>page.evaluate(({selected,guest})=>{const {game:g,ui,render:r}= (window as any).__dongshan;if(g.meeting.running){g.meeting.endReason='測試離席';g.meeting.finish();}g.profile.meeting.cooldown=0;g.meeting.start(123,selected,guest);g.tick(.4);g.meeting.activate();g.meeting.testHold=true;ui.close();g.player.inv=99;r.target.set(0,0,5);r.frame(.1,false,1);},{selected,guest});
const shots:string[]=[];const shot=async(name:string)=>{await page.screenshot({path:`artifacts/meeting-${name}.png`});shots.push(name);};
await enter(['projector','cross_talk','guest_mediator']);await page.waitForTimeout(500);await page.locator('#quest-toggle').click();await shot('room');
const performance:any[]=[];
async function measure(label:string){await page.evaluate(()=>{const {render:r,ui}=(window as any).__dongshan;r.frames=[];ui.pause(false);});await page.waitForTimeout(5000);performance.push({label,...await page.evaluate(()=>{const {render:r,game:g}=(window as any).__dongshan;return {...r.measure(),objects:g.objects.size,water:g.meeting.water.length,papers:g.meeting.papers.length,renderer:r.renderer.getContext().getParameter(r.renderer.getContext().VERSION)};})});}
await page.evaluate(()=>{const {game:g}=(window as any).__dongshan;g.meeting.endReason='測試離席';g.meeting.finish();g.finishTutorial();Object.assign(g.player,{x:0,z:6,inv:99});});await measure('正常校園');
await enter([]);await measure('會議基礎（開發測試零橋段）');
await enter(['tea_spill','printer','cross_talk']);await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.meeting.elapsed=18;const i=[...g.objects.values()].find((i:any)=>i.module==='tea_spill');g.meeting.spill(i);g.meeting.chain();});await measure('三橋段忙碌：茶水／列印／插話');await shot('three-busy');
await enter(['conducting','stamps','whiteboard']);await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.take([...g.objects.values()].find((i:any)=>i.module==='conducting').id);g.meeting.secondary();});await shot('three-music');
await enter(['projector','voting','guest_mediator'],'guard_uncle');await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.meeting.vote();});await shot('three-voting');
const states=['Seated','Standing','Speaking','Voting','Sleeping','Recording','Collect','Drinking','Protecting','Following','FindingChair','Coordinating','Watching','Cold','Hot','Recover'];
const matrix:any[]=[];
for(const [role,guest,index] of [['主席','shop_aunt',0],['家長代表','shop_aunt',1],['紀錄委員','shop_aunt',2],['秩序委員','none',3],['合作社阿姨','shop_aunt',3],['警衛伯伯','guard_uncle',3]] as [string,string,number][]){
 await enter(guest==='none'?['projector','bell']:['guest_mediator','bell'],guest);
 for(const state of states)for(const method of ['bare','held','throw']){
 const before=await page.evaluate(({index,state,method})=>{const {game:g,ui,input,render:r}=(window as any).__dongshan;ui.paused=true;ui.toastUntil=0;input.enabled=true;g.meeting.elapsed=0;g.meeting.chaos=0;g.meeting.hits.clear();g.meeting.queue=[];g.meeting.timers.clear();if(g.held)g.drop();for(const n of g.npcs){Object.assign(n,{...n.home,hp:3,state:'Seated',timer:99});}const n=g.npcs[index];Object.assign(n,{state,timer:3,hp:state==='Recover'?0:3,downAt:0});const side=n.x>0?1:-1;Object.assign(g.player,{x:n.x+side*.85,z:n.z,face:{x:-side,z:0},inv:99,attack:null,attackCooldown:0});if(g.world.blocked(g.player,.32))throw Error('illegal attack position');if(method!=='bare')g.take([...g.objects.values()].find(i=>i.type==='meeting_gavel').id);g.meeting.events=[];r.frame(.1,false,1);return {x:n.x,z:n.z};},{index,state,method});
 await page.keyboard.press(method==='throw'?'KeyQ':'KeyJ');
 const result=await page.evaluate(index=>{const {game:g,render:r,ui}=(window as any).__dongshan;for(let k=0;k<7;k++)g.tick(1/30);r.frame(.1,false,1);ui.update(.2);const n=g.npcs[index];return {x:n.x,z:n.z,state:n.state,hp:n.hp,flash:n.flashUntil,hits:g.meeting.events.filter(e=>e.type==='CombatResolved'&&e.data.npc===n.id).length};},index);
 assert.equal(result.hits,1,`${role}/${state}/${method}`);assert.ok(Math.hypot(result.x-before.x,result.z-before.z)>.01,`${role}/${state}/${method} displacement`);assert.ok(result.flash>0);
 matrix.push({role,state,method,before,result});if(state==='Seated'||index===0&&method==='bare')await shot(`hit-${index}-${guest}-${state}-${method}`);
 await page.evaluate(()=>{const g=(window as any).__dongshan.game;for(let k=0;k<160;k++)g.tick(1/30);});
 }
}
// Live keyboard movement follows the game's actual room navigation, without writing final positions.
await enter(['projector','bell']);const route=await page.evaluate(()=>{const {game:g,ui}=(window as any).__dongshan;ui.pause(false);g.profile.meeting.records=[];return g.world.path(g.player,{x:-2.8,z:2.8});});assert.ok(route.length);
for(const target of route){for(let k=0;k<50;k++){const pos=await page.evaluate(()=>{const p=(window as any).__dongshan.game.player;return {x:p.x,z:p.z};});const dx=target.x-pos.x,dz=target.z-pos.z;if(Math.hypot(dx,dz)<.23)break;const keys=Math.abs(dx)>Math.abs(dz)?dx>0?['KeyS','KeyD']:['KeyW','KeyA']:dz>0?['KeyS','KeyA']:['KeyW','KeyD'];for(const key of keys)await page.keyboard.down(key);await page.waitForTimeout(45);for(const key of keys)await page.keyboard.up(key);if(k===49)throw Error('keyboard route stuck '+JSON.stringify(target));}}
await shot('route');
await page.locator('#meeting-leave').click();await page.waitForTimeout(1900);assert.equal(await page.evaluate(()=>(window as any).__dongshan.game.meeting.phase),'CAMPUS');await page.locator('#menu').click();await page.locator('[data-action=open][data-id=meetingRecords]').click();await shot('records');assert.equal(await page.locator('h2').textContent(),'會議紀錄冊');
await context.close();
const mobile=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});await mobile.addInitScript('window.__name = value => value');const phone=await mobile.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto('http://127.0.0.1:5173');await phone.locator('[data-action=start]').tap();await phone.locator('#skip').tap();await phone.evaluate(()=>{const {game:g,render:r}=(window as any).__dongshan;g.meeting.start(42,['projector','guest_mediator']);g.tick(.4);g.meeting.activate();g.meeting.testHold=true;g.player.inv=99;r.target.set(0,0,5);});await phone.waitForTimeout(500);await phone.locator('#quest-toggle').tap();await phone.screenshot({path:'artifacts/meeting-mobile.png'});assert.equal(await phone.evaluate(()=>document.body.scrollWidth>innerWidth),false);for(const id of ['attack','interact','meeting-leave','meeting-use']){const b=await phone.locator('#'+id).boundingBox();assert.ok(b&&b.x>=0&&b.y>=0&&b.x+b.width<=390&&b.y+b.height<=844,id);}await phone.locator('#attack').tap();await phone.locator('#meeting-leave').tap();await phone.waitForTimeout(1900);assert.equal(await phone.evaluate(()=>(window as any).__dongshan.game.meeting.phase),'CAMPUS');await mobile.close();
assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/meeting-browser-qa.json',JSON.stringify({date:new Date().toISOString(),browser:browser.version(),platform:'Windows desktop, headless Chromium / SwiftShader allowed',viewport:[1280,800],method:'Real keyboard J/Q events with dev-prepared roles and states. The matrix steps the original 30Hz combat while real-time simulation is frozen, then renders and checks hit events and visible displacement. Live keyboard navigation and touch leave use real-time simulation. Screenshot evidence samples every role/method and every state on the chair.',matrix,shots,route,performance,mobile:'390x844 touch emulation; physical phone NOT tested',errors},null,2));await browser.close();console.log(`PASS ${matrix.length} keyboard attack/state combinations, ${shots.length} screenshots, live navigation, mobile controls, performance scenarios`);
