import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs';
const browser=await chromium.launch({headless:true});const errors:string[]=[];const results:any={date:'2026-10-08',method:'Chromium with emulated touch viewports; real HUD/menu/pointer inputs. Dev scene API only prepares combat targets and advances quest content; does not synthesize discovery records. Physical phones not tested.',cameras:[]};
for(const [width,height,mobile] of [[390,844,true],[844,390,true],[1440,900,false]] as const){
 const context=await browser.newContext({viewport:{width,height},hasTouch:mobile,isMobile:mobile});await context.addInitScript('window.__name = (value) => value');const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173');await page.locator('[data-action=start]').click();await page.locator('#skip').click();await page.waitForTimeout(300);
 const measured=await page.evaluate(()=>{const {render:r,game:g}=(window as any).__dongshan;const old=r.camera.clone(),h=r.canvas.clientHeight;old.top=r.canvas.clientWidth/h<1?13:11.5;old.bottom=-old.top;old.updateProjectionMatrix();const size=(camera:any)=>{const a=r.target.clone().set(g.player.x,0,g.player.z).project(camera),b=r.target.clone().set(g.player.x,1.75,g.player.z).project(camera);return Math.abs(a.y-b.y)*h/2};return {currentPixels:size(r.camera),previousPixels:size(old),ratio:size(r.camera)/size(old),span:r.camera.top,drawCalls:r.calls,geometryCount:r.geometryCount,pixelRatio:r.renderer.getPixelRatio(),overflow:document.body.scrollWidth>innerWidth}});assert.ok(Math.abs(measured.ratio-(mobile?2.2:1))<.001);assert.equal(measured.overflow,false);results.cameras.push({width,height,mobile,...measured});
 await page.locator('#quest-toggle').click();assert.equal(await page.locator('#quest-toggle').getAttribute('aria-expanded'),'false');assert.equal(await page.locator('#quest-body').isVisible(),false);await page.waitForTimeout(500);assert.equal(await page.locator('#quest-toggle').getAttribute('aria-expanded'),'false');
 await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.player.x=0;g.player.z=4});await page.waitForTimeout(200);assert.equal(await page.locator('#quest-toggle').getAttribute('aria-expanded'),'false');
 await page.locator('#quest-toggle').click();assert.equal(await page.locator('#quest-body').isVisible(),true);await page.locator('#quest-detail').click();assert.equal(await page.locator('#quest-body').isVisible(),false);
 await page.evaluate(()=>{(window as any).__dongshan.game.startMission('q11')});await page.waitForTimeout(200);assert.equal(await page.locator('#quest-body').isVisible(),true);await page.locator('#quest-toggle').click();await page.evaluate(()=>{(window as any).__dongshan.game.useItem([...((window as any).__dongshan.game.objects.values())].find((i:any)=>i.type==='coffee_machine'))});await page.waitForTimeout(200);assert.equal(await page.locator('#quest-body').isVisible(),true);
 // Native button keyboard activation must not trigger combat/conduct.
 await page.locator('#quest-toggle').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#quest-body').isVisible(),false);await page.keyboard.press('Space');assert.equal(await page.locator('#quest-body').isVisible(),true);
 if(width===390){
  await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.cancelMission();if(g.held)g.drop();g.player.x=0;g.player.z=4;g.player.inv=100;g.player.face={x:1,z:0};g.npcs.forEach((n:any)=>{n.active=false});const n=g.npcs.find((n:any)=>n.type==='timid');Object.assign(n,{x:1,z:4,hp:1,active:true,state:'Idle'});g.props.forEach((p:any)=>{p.x=25;p.z=20});g.refreshColliders()});
  await page.locator('#attack').tap();await page.waitForTimeout(300);
  const first=await page.evaluate(()=>(window as any).__dongshan.game.profile.knockdownCodex);assert.equal(first.students.timid,1);
  await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.npcs.forEach((n:any)=>n.active=false);g.spawnParent('courier');const n=g.npcs.find((n:any)=>n.type==='courier');Object.assign(n,{x:1,z:4,hp:1,active:true,state:'Attack',intro:0});g.player.face={x:1,z:0};g.player.attack=null;g.player.attackCooldown=0});await page.locator('#attack').tap();await page.waitForTimeout(250);
  await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.npcs.forEach((n:any)=>n.active=false);g.player.face={x:1,z:0};g.player.attack=null;g.player.attackCooldown=0;const p=g.props.find((p:any)=>p.type==='table');Object.assign(p,{x:1,z:4,hp:1});g.refreshColliders()});await page.locator('#attack').tap();await page.waitForTimeout(250);
  await page.evaluate(()=>{const g=(window as any).__dongshan.game;g.player.face={x:0,z:1};const i=[...g.objects.values()].find((i:any)=>i.type==='chalk_eraser');g.take(i.id)});await page.locator('#throw').tap();await page.waitForTimeout(1600);
  const saved=await page.evaluate(()=>(window as any).__dongshan.game.profile.knockdownCodex);assert.equal(saved.parents.courier,1);assert.equal(saved.objects['prop:table'],1);assert.equal(saved.objects['item:chalk_eraser'],1);results.discoveries=saved;
  await page.locator('#menu').tap();await page.locator('[data-id=knockdowns]').tap();assert.match(await page.locator('[data-codex-id=timid]').innerText(),/暈眩 1 次/);assert.match(await page.locator('[data-codex-id=fighter]').innerText(),/未解鎖/);await page.locator('[data-action=codexTab][data-id=parents]').tap();assert.match(await page.locator('[data-codex-id=courier]').innerText(),/暈眩 1 次/);await page.locator('[data-action=codexTab][data-id=objects]').tap();assert.equal(await page.locator('.incident-codex article').count(),2);await page.screenshot({path:'artifacts/mobile-knockdown-codex.png'});
  await page.reload();await page.locator('[data-action=start]').tap();await page.locator('#menu').tap();await page.locator('[data-id=knockdowns]').tap();const restored=await page.evaluate(()=>(window as any).__dongshan.game.profile.knockdownCodex);assert.deepEqual(restored,saved);results.persistence='passed reload and saved profile roundtrip';await page.locator('[data-action=close]').tap();
 }
 await page.locator('#quest-toggle').click();await page.screenshot({path:`artifacts/mobile-camera-${width}x${height}.png`});if(width===390){await page.setViewportSize({width:844,height:390});await page.waitForTimeout(250);const rotated=await page.evaluate(()=>(window as any).__dongshan.render.camera.top);assert.equal(rotated,11.5/2.2);assert.equal(await page.locator('#quest-body').isVisible(),false);results.rotation='same-page portrait to landscape keeps mobile zoom and collapsed state'}await context.close();
}
assert.deepEqual(errors,[]);results.errors=errors;results.status='pass';fs.writeFileSync('artifacts/mobile-codex-qa.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));await browser.close();
