import {SOUND_EFFECTS,MUSIC_TRACKS} from '../src/audio';
import {chromium} from '@playwright/test';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const site=process.env.SITE_URL||'https://ml-yoyohuang.github.io/teacher-simulator/';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors:string[]=[];const failed:string[]=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400)failed.push(`${r.status()} ${r.url()}`)});
await page.goto(site,{waitUntil:'networkidle'});
assert.equal(await page.evaluate(()=>typeof (window as any).__dongshan),'undefined');
const image=await page.locator('meta[property="og:image"]').getAttribute('content');
assert.equal(image,new URL('og-image.png',site).href);
const dimensions=await page.evaluate(async src=>{const im=new Image();im.src=src!;await im.decode();return [im.naturalWidth,im.naturalHeight]},image);
assert.deepEqual(dimensions,[1200,630]);
await page.screenshot({path:'artifacts/pages-live-start.png'});
await page.locator('[data-action=start]').click();await page.locator('#skip').click();
assert.match(await page.locator('.hp-line').innerText(),/開心導師/);
await page.keyboard.down('KeyW');await page.waitForTimeout(600);await page.keyboard.up('KeyW');
await page.locator('#tasks').click();assert.equal(await page.locator('.task-card').count(),24);
await page.locator('[data-action=close]').first().click();
await page.screenshot({path:'artifacts/pages-live-game.png'});
await page.goto(new URL('soundtest.html',site).href,{waitUntil:'networkidle'});
assert.equal(await page.locator('[data-sfx]').count(),SOUND_EFFECTS.length);assert.equal(await page.locator('[data-music]').count(),MUSIC_TRACKS.length);
await page.locator('[data-sfx="missionComplete"]').click();await page.waitForTimeout(100);
assert.match(await page.locator('#status').innerText(),/任務完成/);
await page.locator('[data-music="chase"]').click();await page.waitForTimeout(100);
assert.match(await page.locator('#status').innerText(),/正在播放：追逐/);
await page.locator('#stop').click();assert.equal(await page.locator('#status').innerText(),'已停止播放');
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
const result={date:'2026-10-08',site,status:'pass',browser:await browser.version(),dimensions,tasks:24,sounds:SOUND_EFFECTS.length,music:MUSIC_TRACKS.length,debugExcluded:true,errors,failed,note:'公開 GitHub Pages 真實瀏覽器載入、鍵盤輸入、選單與試聽觸發；不代表人工聽感或實體手機效能。'};
fs.writeFileSync('artifacts/pages-live-qa.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
await browser.close();
