import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:390,height:844}});await page.addInitScript('window.__name=v=>v');const errors:string[]=[],shots:any[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.QA_URL||'http://127.0.0.1:5173');await page.locator('[data-action=start]').click();await page.locator('#skip').click();await page.waitForTimeout(3300);
 async function prepare(){await page.evaluate(()=>{const d=(window as any).__dongshan;d.ui.close();d.game.reset('normal');d.game.profile.life.nextMain=d.game.profile.life.nextSide=1e8;d.ui.pause(true)})}
 async function capture(name:string,root:string){await page.evaluate(()=>{const {game:g,render:r,ui}=(window as any).__dongshan;r.target.set(g.player.x,0,g.player.z);r.frame(.1,false,1);ui.update(.2)});await page.waitForTimeout(350);await page.evaluate(()=>document.fonts.ready);const audit=await page.evaluate(selector=>{const root=document.querySelector(selector)!,buttons=[...root.querySelectorAll('button')].filter(b=>b.getClientRects().length&&getComputedStyle(b).visibility!=='hidden').map(b=>b.getBoundingClientRect());let min=Infinity;for(let i=0;i<buttons.length;i++)for(let j=i+1;j<buttons.length;j++){const a=buttons[i],b=buttons[j];min=Math.min(min,Math.hypot(Math.max(0,a.x-b.right,b.x-a.right),Math.max(0,a.y-b.bottom,b.y-a.bottom)))}return{minGap:min,overflow:root.scrollWidth>root.clientWidth+1}},root);assert.ok(audit.minGap>=7.5);assert.equal(audit.overflow,false);assert.equal(await page.locator('#toast').evaluate(e=>e.classList.contains('visible')),false);await page.screenshot({path:`tutorial-assets/${name}.png`});shots.push({name,size:page.viewportSize(),...audit})}
 await prepare();await page.evaluate(()=>{const {game:g,ui}=(window as any).__dongshan,i=[...g.objects.values()].find((i:any)=>i.type==='textbook');Object.assign(g.player,{x:i.x,z:i.z+1});g.take(i.id);ui.setQuestCollapsed(true)});assert.equal(await page.locator('#drop').count(),1);await capture('hud-mobile','.hud');assert.equal(await page.locator('#drop').isVisible(),true);assert.match(await page.locator('#held').innerText(),/課本/);const layout=await page.evaluate(()=>{const a=document.querySelector('.top-left')!.getBoundingClientRect(),b=document.querySelector('.quest')!.getBoundingClientRect(),c=document.querySelector('.side-nav')!.getBoundingClientRect();return{statusBottom:a.bottom,questTop:b.top,questBottom:b.bottom,navTop:c.top}});assert.ok(layout.questTop>=layout.statusBottom+9);assert.ok(layout.navTop>=layout.questBottom+9);
 await page.setViewportSize({width:1280,height:800});await prepare();await page.evaluate(()=>{const {game:g,ui}=(window as any).__dongshan;g.player.x=0;g.player.z=4;ui.setQuestCollapsed(false)});await page.locator('#dogs-entry').click();for(const img of await page.locator('.codex-thumb').all())await img.evaluate(img=>(img as HTMLImageElement).decode());assert.equal(await page.locator('.dog-status').count(),2);await capture('dog-card','.panel');
 await prepare();await page.evaluate(()=>{const {game:g,ui}=(window as any).__dongshan;g.meeting.start(208,['bell','sleepy_member']);for(let i=0;i<12;i++)g.tick(1/30,{x:0,z:0,run:false});g.meeting.activate();ui.setQuestCollapsed(false)});await capture('meeting','.hud');assert.equal(await page.locator('#meeting-controls').isVisible(),true);assert.match(await page.locator('#quest-title').innerText(),/失控.*剩餘/);assert.deepEqual(errors,[]);
 fs.writeFileSync('artifacts/tutorial-screenshots-qa.json',JSON.stringify({date:'2026-10-09',sourceCommit:execFileSync('git',['rev-parse','--short','HEAD'],{encoding:'utf8'}).trim(),browser:await browser.version(),status:'pass',shots,mobileLayout:layout,errors,method:'Actual current game rendering and UI; existing development scene API positions teacher/takes textbook and starts meeting. No screenshot compositing or CSS/DOM substitutions. Dog card opened with actual button.',limitations:['Prepared local scenes, not a manual playthrough of meeting trigger. Chromium only.']},null,2));console.log(JSON.stringify({status:'pass',shots}));
}finally{await browser.close()}
