import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const site=process.env.QA_URL||'http://127.0.0.1:4173/';
const browser=await chromium.launch({headless:true,ignoreDefaultArgs:['--disable-back-forward-cache']});
const results:any[]=[];
try{
 for(const size of [{width:1280,height:900},{width:844,height:390},{width:390,height:844},{width:320,height:700}]){
  const context=await browser.newContext({viewport:size,hasTouch:true}),page=await context.newPage(),errors:string[]=[],failed:any[]=[];await page.addInitScript('window.__historyRestored=false;addEventListener("pageshow",e=>{window.__historyRestored=e.persisted})');page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push({url:r.url(),status:r.status()})});
  await page.goto(site);await page.locator('[data-action=start]').tap();await page.locator('#skip').tap();await page.locator('#menu').tap();await page.locator('[data-action=open][data-id=save]').tap();await page.locator('[data-action=saveNow]').tap();const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('dongshan-campus-v1')!));assert.ok(before.tutorialFlags.includes('done'));
  await page.goto(site);const guide=page.locator('[data-action=tutorialGuide]');if(size.width===1280){await guide.focus();await page.keyboard.press('Enter')}else await guide.tap();await page.waitForURL('**/tutorial.html');assert.equal(context.pages().length,1);assert.equal(await page.evaluate(()=>localStorage.getItem('dongshan-campus-writer')),null);assert.ok(await page.getByText('背景音樂包含原曲與場景改編版',{exact:false}).count());assert.ok(await page.getByText('電腦版也會顯示搖桿與操作按鈕',{exact:false}).count());
  for(const img of await page.locator('img').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(img=>(img as HTMLImageElement).decode());assert.ok(await img.evaluate(img=>(img as HTMLImageElement).naturalWidth>0))}
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.goBack();await page.locator('[data-action=tutorialGuide]').waitFor();const historyRestored=await page.evaluate(()=>(window as any).__historyRestored);await page.locator('[data-action=tutorialGuide]').tap();await page.waitForURL('**/tutorial.html');assert.equal(await page.evaluate(()=>localStorage.getItem('dongshan-campus-writer')),null);await page.locator('nav a[href="#controls"]').tap();assert.equal(new URL(page.url()).hash,'#controls');if(size.width===390)await page.screenshot({path:process.env.QA_SCREENSHOT||'artifacts/tutorial-navigation-mobile.png'});
  await page.locator('.cta').tap();await page.waitForURL('**/index.html');await page.locator('[data-action=start]').tap();assert.equal(context.pages().length,1);await page.locator('#menu').tap();await page.locator('[data-action=open][data-id=save]').tap();await page.locator('[data-action=saveNow]').tap();const message=await page.locator('.fine').innerText(),after=await page.evaluate(()=>JSON.parse(localStorage.getItem('dongshan-campus-v1')!));assert.ok(!message.includes('另一分頁'));assert.ok(after.revision>before.revision);for(const k of ['points','tutorialFlags','completedMissionIds','ownedCosmetics','settings','rewardLedger'])assert.deepEqual(after[k],before[k],k);
  await page.locator('.panel-head [data-action=close]').tap();await page.locator('#menu').tap();await page.locator('[data-action=open][data-id=help]').tap();assert.match(await page.locator('.panel-head h2').innerText(),/操作/);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);results.push({size,historyRestored,pages:context.pages().length,saveRevisionBefore:before.revision,saveRevisionAfter:after.revision,message,errors,failed});await context.close();
 }
 fs.writeFileSync(process.env.QA_REPORT||'artifacts/tutorial-navigation-qa.json',JSON.stringify({date:'2026-10-09',site,status:'pass',browser:await browser.version(),results,method:'Real keyboard/touch navigation and save buttons; same tab, writer lease released, saved records preserved, guide images/layout/anchor and in-game help checked.',limitations:['Chromium viewport/touch emulation; physical phones and Safari not tested.','History navigation reloaded in this run; BFcache restoration is not verified unless historyRestored is true.']},null,2));console.log(JSON.stringify({status:'pass',site,viewports:results.length}));
}finally{await browser.close()}
