import {Game,Event} from './game';
export class AudioEngine{
 ctx:AudioContext|null=null;master:GainNode|null=null;musicGain:GainNode|null=null;sfxGain:GainNode|null=null;voices=new Set<OscillatorNode>();musicVoices=new Set<OscillatorNode>();paused=true;timer:any;nextTime=0;beat=0;theme='';songOffset=0;fail='';lastSfx=new Map<string,number>();
 constructor(public game:Game){game.listeners.push(e=>this.event(e))}
 async unlock(){try{if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();let compressor=this.ctx.createDynamicsCompressor();compressor.threshold.value=-16;compressor.ratio.value=8;this.master.gain.value=.3;this.master.connect(compressor);compressor.connect(this.ctx.destination);this.musicGain=this.ctx.createGain();this.sfxGain=this.ctx.createGain();this.musicGain.connect(this.master);this.sfxGain.connect(this.master);this.timer=setInterval(()=>this.schedule(),25)}await this.ctx.resume();this.configure();this.paused=false;this.nextTime=this.ctx.currentTime+.03;return true}catch(e){this.fail='音訊未啟用，靜音仍可遊玩';return false}}
 configure(){if(!this.ctx)return;let s=this.game.profile.settings;this.musicGain.gain.setTargetAtTime(s.mute?0:s.music,this.ctx.currentTime,.2);this.sfxGain.gain.setTargetAtTime(s.mute?0:s.sfx,this.ctx.currentTime,.05)}
 note(freq:number,time:number,length=.12,music=false,type:OscillatorType='sine',gain=.25){if(!this.ctx||this.paused)return;let pool=music?this.musicVoices:this.voices,limit=music?6:12;if(pool.size>=limit)return;let o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,time);g.gain.setValueAtTime(0,time);g.gain.linearRampToValueAtTime(gain,time+.012);g.gain.exponentialRampToValueAtTime(.001,time+length);o.connect(g);g.connect(music?this.musicGain:this.sfxGain);pool.add(o);o.start(time);o.stop(time+length+.02);o.onended=()=>{pool.delete(o);o.disconnect();g.disconnect()}}
 event(e:Event){if(!this.ctx||this.paused)return;let t=this.ctx.currentTime,key=e.type;let frequencies={move:120,swing:240,CombatResolved:180,playerHit:110,throw:360,land:150,take:580,drop:300,propDamaged:90,notice:440,alertFall:330,contactComplete:680,familyArrived:220,NPCDowned:160,recover:520,npcRecovered:520,missionComplete:784,rollCall:650,dodge:420,coffee:260,purchase:800,drink:540,raceStart:900,reflect:1200,conduct:660};let f=frequencies[key];if(key==='instrument')f=({piano:440,recorder:587,triangle:1320,castanets:320,drumstick:180})[e.data.item];if(!f)return;let last=this.lastSfx.get(key)||-100;if(t-last<(key==='move'?.125:.08))return;this.lastSfx.set(key,t);this.note(f,t,key==='missionComplete'?.35:.12,false,['propDamaged','swing'].includes(key)?'triangle':'sine',key==='move'?.05:.3);if(key==='missionComplete'){this.note(f*1.25,t+.12,.3);this.note(f*1.5,t+.24,.35)}}
 schedule(){if(!this.ctx||this.paused)return;const theme=this.game.choir?'choir':this.game.chase.some(n=>n.state==='Chase'||n.state==='Attack')?'chase':'explore';if(theme!==this.theme){this.theme=theme;this.musicGain.gain.setTargetAtTime(this.game.profile.settings.mute?0:this.game.profile.settings.music,this.ctx.currentTime,.8);this.nextTime=this.ctx.currentTime+.03;this.beat=0}let bpm=theme==='choir'?80:theme==='chase'?120:90,step=60/bpm;
 if(theme==='choir'){let song=this.game.time-this.game.choir.start;let index=Math.ceil(song/step);if(index!==this.beat&&index<32){let delay=index*step-song;if(delay<.11){this.beat=index;let sequence=[261.63,329.63,392,329.63,293.66,349.23,440,392];this.note(sequence[index%8],this.ctx.currentTime+delay,.35,true,'triangle',.17)}}return}
 while(this.nextTime<this.ctx.currentTime+.1){let sequence=[261.63,329.63,392,329.63,293.66,349.23,440,392,261.63,392,493.88,440,349.23,329.63,293.66,392];let f=sequence[this.beat%16]*(this.game.mode==='anniversary'?1.25:1);this.note(f,this.nextTime,.24,true,'triangle',.18);if(this.beat%2===0)this.note(f/2,this.nextTime,.3,true,'sine',.22);this.beat++;this.nextTime+=step;}}
 pause(){this.paused=true;for(let o of [...this.voices,...this.musicVoices]){try{o.stop()}catch{}}this.voices.clear();this.musicVoices.clear();this.songOffset=this.beat;}
 resume(){if(!this.ctx)return;this.paused=false;this.nextTime=this.ctx.currentTime+.03;this.beat=this.songOffset;this.configure()}
}
