import type {Game,NPC} from './game';
import {Vec,zoneAt} from './data';
import {distance,norm} from './world';
import {DogId,dogIds,dogNames,dogQuests,stage,dogCapabilities} from './dogs-data';
export const dogStates=['Idle','Roam','Greet','Rest','Feeding','Petting','Fetching','Following','AssistApproach','AssistContact','Returning','Relocating'];
export type Dog={id:DogId,label:string,capabilities:typeof dogCapabilities,x:number,z:number,face:Vec,state:string,home:Vec,target:Vec,path:Vec[],repath:number,timer:number,active:boolean,job:string|null,targetId:string|null,stuck:number,last:Vec,walk:number,walkCells:Set<string>,followTime:number,ballReturning:boolean};
const homes={dog_lion:{x:8,z:12},dog_mani:{x:10,z:10}};
const stops={dog_lion:[homes.dog_lion,{x:6,z:20},{x:-10,z:13},{x:7,z:5}],dog_mani:[homes.dog_mani,{x:18,z:10},{x:-12,z:0},{x:9,z:3}]};
export class Dogs{
 actors:Dog[]=[];observer:DogId|null=null;selectedTarget:string|null=null;petJob:{dog:DogId,age:number,event:string,start:Vec}|null=null;teacherPhase=0;teacherUntil=0;nextFeed=180;feedInterrupted=false;heart:{id:DogId,until:number,gain:number}|null=null;
 constructor(public g:Game){}
 get p(){return this.g.profile.dogs}
 get visible(){return this.g.meeting.running?this.actors.filter(d=>d.id===this.observer):this.actors}
 get busyAssist(){return this.actors.some(d=>['AssistApproach','AssistContact'].includes(d.state))}
 resetQuest(){const q=dogQuests.find(q=>q.id===this.p.activeQuest);if(!q)return false;if('item' in q){const i=this.g.objects.get(q.id+':unique');if(i){this.g.detach(i);Object.assign(i,{...i.home,y:0,state:'home',flight:undefined,vx:0,vz:0,vy:0});}}else{const d=this.actor(q.dog);this.cancel(d);delete (d as any).routeDone;}this.g.toast('校狗任務物件已按原 ID 歸位。');return true;}
 reset(){this.cancelAll();if(!this.actors.length)this.actors=dogIds.map(id=>({id,label:dogNames[id],capabilities:dogCapabilities,...homes[id],home:{...homes[id]},face:{x:0,z:1},state:'Rest',target:{...homes[id]},path:[],repath:0,timer:0,active:false,job:null,targetId:null,stuck:0,last:{...homes[id]},walk:0,walkCells:new Set(),followTime:0,ballReturning:false}));for(const d of this.actors){Object.assign(d,this.g.world.approach(homes[d.id]),{state:'Rest',job:null,path:[],timer:0});}this.p.transfer=null;this.p.companion=null;this.observer=null;this.teacherPhase=0;this.teacherUntil=0;this.nextFeed=this.p.clock+180;
 this.g.createItem('dog_soft_ball','dog_soft_ball:unique',{x:10,z:11}).pins=['dog:soft_ball'];for(const q of dogQuests)if('item' in q&&!this.p.dogs[q.dog].completed.includes(q.id)){const i=this.g.createItem(q.item,q.id+':unique',q.home);i.pins=['dog:'+q.id];} }
 actor(id:string){return this.actors.find(d=>d.id===id)}
 fail(text:string){this.g.toast(text);return false}
 gain(id:DogId,value:number,event:string){if(this.p.ledger.includes(event))return false;this.p.ledger.push(event);this.p.ledger=this.p.ledger.slice(-100);const d=this.p.dogs[id],before=d.affinity;d.affinity=Math.min(100,d.affinity+value);d.collected=d.affinity===100;this.heart={id,until:this.p.clock+1.5,gain:d.affinity-before};this.g.emit('dogHeart',{dog:id,gain:d.affinity-before});this.g.toast(dogNames[id]+' ♥ +'+(d.affinity-before)+' · '+stage(d.affinity));this.collect();this.g.onSave();return true}
 collect(){const p=this.p,a=p.dogs.dog_lion.affinity,b=p.dogs.dog_mani.affinity;const award=(i:number,ok:boolean)=>{const names=['校園有兩位新朋友','巡邏隊長批准了','馬尼認為你應該停下來摸牠','理化老師其實很溫柔'];if(ok&&!p.achievements.includes(names[i]))p.achievements.push(names[i]);};award(0,a>=20&&b>=20);award(1,a>=75);award(2,b>=75);award(3,p.feedingSeen&&dogIds.some(id=>p.dogs[id].completed.length>0));}
 achievement(name:string){if(!this.p.achievements.includes(name)){this.p.achievements.push(name);this.g.onSave();}}
 release(d:Dog){if(d.targetId){const n=this.g.npcs.find(n=>n.id===d.targetId);if(n&&(n as any).dogControl?.owner===d.id)delete (n as any).dogControl;}d.targetId=null;d.job=null;d.path=[];d.repath=0;d.stuck=0;}
 cancel(d:Dog){this.release(d);if(this.petJob?.dog===d.id)this.petJob=null;if(d.state==='Fetching'&&this.g.objects.get('dog_soft_ball:unique')?.owner!==this.g.player.id)this.recoverBall();if(this.p.companion===d.id)this.p.companion=null;d.state='Returning';d.target=this.observer===d.id?{x:1.3,z:8}:this.g.world.approach(d.home,d);}
 cancelAll(){for(const d of this.actors)this.cancel(d);this.petJob=null;this.selectedTarget=null;this.p.companion=null;}
 recoverBall(){const b=this.g.objects.get('dog_soft_ball:unique');if(b){this.g.detach(b);Object.assign(b,{...b.home,y:0,state:'home',vx:0,vz:0,vy:0,flight:undefined});}}
 canInteract(d:Dog){return this.visible.includes(d)&&distance(d,this.g.player)<2.3&&this.g.world.visible(d,this.g.player)}
 pet(id:DogId){const d=this.actor(id);if(!d||!this.canInteract(d))return this.fail('靠近'+dogNames[id]+'，再摸摸牠。');if(this.petJob||['AssistApproach','AssistContact','Fetching'].includes(d.state))return this.fail('牠正在忙，等一下再摸摸。');this.release(d);d.state='Petting';d.job='pet';this.petJob={dog:id,age:0,event:'pet:'+id+':'+(++this.p.serial),start:{x:this.g.player.x,z:this.g.player.z}};this.g.player.action='pet';this.g.player.actionTime=.8;return true}
 treat(id:DogId){const d=this.actor(id);if(!d||!this.canInteract(d)||d.job)return this.fail('請靠近空閒的'+dogNames[id]);const p=this.p.dogs[id];if(p.cooldowns.treat>0)return this.fail('零食冷卻 '+Math.ceil(p.cooldowns.treat)+' 秒，不消耗零食。');if(!this.p.treats)return this.fail('零食用完了，可以向老師接任務或到合作社買。');this.p.treats--;p.cooldowns.treat=180;this.gain(id,6,'treat:'+id+':'+(++this.p.serial));d.state='Feeding';d.timer=2;d.job='treat';return true}
 buyTreat(){if(!this.g.shopAvailable()||this.g.profile.points<5||this.p.treats>=20)return this.fail('需要在合作社、5 點且零食未滿20份。');this.g.profile.points-=5;this.p.treats++;this.g.onSave();return true}
 introduce(){const n=this.g.npcs.find(n=>n.type==='science_teacher');if(!n||n.hp<=0||['Recover','ScienceHit','Chase','Attack'].includes(n.state)||distance(n,this.g.player)>3||!this.g.world.visible(n,this.g.player))return this.fail('等理化老師恢復，靠近他再交談。');if(!this.p.introduced){this.p.introduced=true;this.p.treats=Math.min(20,this.p.treats+4);this.g.onSave();this.g.toast('理化老師：棕色的是 LION，白色的是馬尼。碗不要放反。');}return true}
 quest(id:string){const q=dogQuests.find(q=>q.id===id);if(!q||!this.introduce())return false;const list=dogQuests.filter(x=>x.dog===q.dog),index=list.findIndex(x=>x.id===q.id);if(this.p.dogs[q.dog].completed.includes(q.id)||index>0&&!this.p.dogs[q.dog].completed.includes(list[index-1].id))return this.fail('請先完成前一個校狗任務。');this.p.activeQuest=q.id;this.g.onSave();this.g.toast(q.label+'：'+('item' in q?'取回標記物品，放到餵狗角對應位置，再找老師交付。':'從餵狗角邀請牠，陪走到指定地點，再找老師交付。'));return true}
 checkDelivery(){const q=dogQuests.find(q=>q.id===this.p.activeQuest);if(!q||!this.introduce())return false;const d=this.actor(q.dog),i='item' in q?this.g.objects.get(q.id+':unique'):null;const done=i?!i.owner&&['home','settled'].includes(i.state)&&distance(i,q.goal)<=1:!!d&&(d as any).routeDone===q.id;if(!done)return this.fail('任務尚未完成，請確認標記物品或指定陪走路線。');if(this.p.dogs[q.dog].completed.includes(q.id))return false;this.p.dogs[q.dog].completed.push(q.id);this.p.treats=Math.min(20,this.p.treats+q.treats);this.gain(q.dog,q.gain,'quest:'+q.id);if(i){this.g.detach(i);i.state='reserved';}this.p.activeQuest=null;if(d){delete (d as any).routeDone;this.cancel(d);}this.collect();this.g.onSave();return true}
 follow(id:DogId){if(this.g.meeting.running)return this.fail('旁聽席就在這裡，散場後再散步。');const d=this.actor(id),q=dogQuests.find(q=>q.id===this.p.activeQuest&&q.dog===id&&!('item' in q));if(!d||!this.canInteract(d))return this.fail('先走到'+dogNames[id]+'旁邊。');if(this.p.dogs[id].affinity<45&&!q)return this.fail('正式跟隨需要45好感。');if(d.job&&d.job!=='follow')return this.fail('牠正在忙。');for(const other of this.actors)if(other!==d&&other.state==='Following')this.cancel(other);this.release(d);d.state='Following';d.job='follow';d.followTime=0;d.walk=0;d.walkCells.clear();delete (d as any).lastCell;delete (d as any).freshCell;(d as any).routeStarted=!!q&&distance(this.g.player,{x:8,z:11})<4;(d as any).routeDone=null;this.p.companion=id;this.g.onSave();return true}
 play(id:DogId){const d=this.actor(id),g=this.g;if(g.meeting.running)return this.fail('會議室先摸摸，軟球留在校園。');if(!d||!this.canInteract(d)||d.job||this.actors.some(x=>x.state==='Fetching'))return this.fail('請選擇附近空閒的校狗。');if(this.p.dogs[id].cooldowns.ball>0)return this.fail('玩球冷卻 '+Math.ceil(this.p.dogs[id].cooldowns.ball)+' 秒。');const ball=g.objects.get('dog_soft_ball:unique');if(!ball||g.held&&g.held!==ball)return this.fail('請先放下手中物品，再玩球。');g.detach(ball);ball.state='settled';g.take(ball.id);d.state='Fetching';d.job='ball';d.timer=0;d.ballReturning=false;d.path=[];d.repath=0;g.throwItem();return true}
 validTarget(n:NPC|undefined){if(!n||!this.g.npcs.includes(n)||n.hp<=0||!n.active||['Recover','Leave','hit','ScienceHit'].includes(n.state)||!['parent','staff','visitor'].includes(n.role))return false;return this.g.meeting.running?!!(n as any).dogHostile:['Chase','Attack','Search'].includes(n.state)}
 select(id:string){const n=this.g.npcs.find(n=>n.id===id);if(!this.validTarget(n))return this.fail('只可選正在敵對反應的成人。');this.selectedTarget=id;this.g.toast('協助目標：'+n.label);return true}
 assist(id:DogId){const d=this.actor(id),n=this.g.npcs.find(n=>n.id===this.selectedTarget);if(this.p.dogs[id].affinity<75)return this.fail('協助需要75好感。');if(!d||!this.visible.includes(d))return this.fail('這隻狗目前不在同一場景。');if(this.busyAssist)return this.fail('已經有一隻狗正在幫忙。');if(this.p.assistCooldown>0)return this.fail('兩狗共享協助冷卻 '+Math.ceil(this.p.assistCooldown)+' 秒。');if(!this.validTarget(n))return this.fail('請先點選一位有效的敵對成人。');if(distance(n,d)>8||distance(n,this.g.player)>8||!this.g.world.visible(d,n))return this.fail('目標太遠或隔著牆。');const target=this.g.world.approach({x:n.x+.55,z:n.z},d),path=this.g.world.path(d,target);if(!path.length)return this.fail('沒有可達的腿側路線。');this.cancel(d);d.state='AssistApproach';d.job='assist';d.targetId=n.id;d.target=target;d.path=path;d.repath=.4;d.timer=0;d.stuck=0;return true}
 move(d:Dog,target:Vec,dt:number,speed=2.5){const g=this.g;if(g.world.blocked(target,.32))target=g.world.approach(target,d);if(d.repath<=0&&g.pathBudget>0){g.pathBudget--;d.path=g.world.path(d,target);d.repath=.7;}d.repath-=dt;if(!d.path.length)return false;const p=d.path[0];if(distance(d,p)<.23){d.path.shift();return true;}const f=norm(p.x-d.x,p.z-d.z);d.face=f;let moved=g.world.move(d,f.x*speed*dt,f.z*speed*dt,.25);const near=[g.player,...g.npcs.filter(n=>n.active)];if(d.state!=='AssistApproach'&&d.state!=='AssistContact')for(const n of near)if(distance(moved,n)<.55){const away=norm(moved.x-n.x,moved.z-n.z);moved=g.world.move(moved,away.x*dt,away.z*dt,.25);}d.stuck=distance(d,moved)<.003?d.stuck+dt:0;d.x=moved.x;d.z=moved.z;return true}
 transfer(id:DogId|null){this.cancelAll();this.observer=id;this.p.transfer=id;if(id){const d=this.actor(id);Object.assign(d,{x:1.3,z:8,state:'Rest',job:null,path:[]});}this.g.onSave()}
 returnCampus(){this.cancelAll();this.observer=null;this.p.transfer=null;for(const d of this.actors)Object.assign(d,this.g.world.approach(d.home),{state:'Rest',path:[],job:null});}
 observerEvent(){if(!this.observer)return;this.g.meeting.award('dog_observer');this.achievement('本次會議有旁聽席');}
 tick(dt:number,input={x:0,z:0}){const g=this.g,p=this.p;p.clock+=dt;p.assistCooldown=Math.max(0,p.assistCooldown-dt);for(const id of dogIds)for(const k of ['pet','treat','ball','walk'])p.dogs[id].cooldowns[k]=Math.max(0,p.dogs[id].cooldowns[k]-dt);
 if(this.petJob){const job=this.petJob,d=this.actor(job.dog);if(!d||Math.hypot(input.x,input.z)>.08||g.player.action==='hit'||g.player.hp<=0||g.player.attack||distance(g.player,job.start)>.15){if(d)this.cancel(d);this.petJob=null;}else{job.age+=dt;if(job.age>=.6&&job.age-dt<.6){const progress=p.dogs[job.dog];if(progress.cooldowns.pet<=0){progress.cooldowns.pet=60;this.gain(job.dog,2,job.event);}else g.toast(d.label+'開心搖尾巴 · 收益冷卻中');if(g.meeting.running)this.observerEvent();g.emit('dogPet',{dog:job.dog});}if(job.age>=.8){d.state='Rest';d.job=null;this.petJob=null;}}}
 for(const d of this.visible){d.active=distance(d,g.player)<24||!!d.job||g.meeting.running;d.timer+=dt;if(!d.active&&Math.floor(p.clock)!==Math.floor(p.clock-dt))d.repath=0;else if(!d.active)continue;
 if(g.world.blocked(d,.23)){const safe=g.world.approach(d,d);if(!g.cameraVisible(d))Object.assign(d,g.world.blocked(safe,.23)?g.world.approach(d.home):safe);else{if(d.state!=='Relocating'){d.timer=0;d.state='Relocating';}d.target=g.world.blocked(safe,.23)?g.world.approach(d.home):safe;if(d.timer>2.2){Object.assign(d,d.target);d.state='Rest';d.timer=0;}}}
 if(['AssistApproach','AssistContact'].includes(d.state)){const n=g.npcs.find(n=>n.id===d.targetId);if(!this.validTarget(n)){this.cancel(d);continue;}if(d.state==='AssistApproach'){d.target=g.world.approach({x:n.x+.55,z:n.z},d);this.move(d,d.target,dt,3.5);if(distance(d,n)<.9&&g.world.visible(d,n)){d.state='AssistContact';d.timer=0;p.assistCooldown=20;(n as any).dogControl={owner:d.id,remaining:d.id==='dog_lion'?2.5:2};n.attack=null;g.emit('dogAssist',{dog:d.id,npc:n.id});if(n.role==='parent')this.achievement('我們可以坐下來談');if(g.meeting.running)this.observerEvent();g.onSave();}else if(d.timer>3||d.stuck>2)this.cancel(d);}else{const c=(n as any).dogControl;if(!c||c.owner!==d.id||d.timer>=(d.id==='dog_lion'?2.5:2)||d.timer>3){this.cancel(d);g.toast(d.id==='dog_lion'?'LION 認為本次處理非常專業。':'馬尼回來討摸摸。');}else{c.remaining=Math.max(0,c.remaining-dt);d.face=norm(n.x-d.x,n.z-d.z);if(d.id==='dog_mani')n.face=norm(d.x-n.x,d.z-n.z);}}continue;}
 if(d.state==='Petting')continue;
 if(d.state==='Fetching'){const b=g.objects.get('dog_soft_ball:unique');if(!b||b.owner||d.timer>20){this.cancel(d);continue;}if(b.state==='airborne')continue;if(!d.ballReturning){if(g.world.blocked(b,.3)||Math.abs(b.x)>30||b.z>24||b.z<-24||b.y>.7){this.cancel(d);continue;}this.move(d,b,dt,3.3);if(d.stuck>2||d.timer>12){this.cancel(d);continue;}if(distance(d,b)<.65){d.ballReturning=true;d.path=[];d.repath=0;}}else{this.move(d,g.world.approach({x:g.player.x+1,z:g.player.z},d),dt,3);Object.assign(b,{x:d.x+d.face.x*.3,z:d.z+d.face.z*.3,y:.45});if(distance(d,g.player)<1.7){b.y=0;d.state='Rest';d.job=null;if(p.dogs[d.id].cooldowns.ball<=0){p.dogs[d.id].cooldowns.ball=90;this.gain(d.id,4,'ball:'+d.id+':'+(++p.serial));}g.emit('dogFetch',{dog:d.id});}}continue;}
 if(d.state==='Following'){d.followTime+=dt;const before={x:d.x,z:d.z},target={x:g.player.x-g.player.face.x*1.7+g.player.face.z*.65,z:g.player.z-g.player.face.z*1.7-g.player.face.x*.65};const route=dogQuests.find(q=>q.id===p.activeQuest&&q.dog===d.id&&!('item' in q));if(route&&(d as any).routeStarted&&distance(g.player,route.goal)<2)Object.assign(target,route.goal);if(distance(d,target)>.7)this.move(d,target,dt,3.8);const cell=Math.floor(d.x)+','+Math.floor(d.z);if((d as any).lastCell!==cell&&!d.walkCells.has(cell)){const previousCell=(d as any).lastCell?.split(',').map(Number),currentCell=cell.split(',').map(Number);if(previousCell){const segment=Math.hypot(currentCell[0]-previousCell[0],currentCell[1]-previousCell[1]);if(segment<=1.5)d.walk+=segment;}d.walkCells.add(cell);}(d as any).lastCell=cell;const q=dogQuests.find(q=>q.id===p.activeQuest&&q.dog===d.id&&!('item' in q));if(q&&(d as any).routeStarted&&distance(d,q.goal)<2&&distance(g.player,q.goal)<2){(d as any).routeDone=q.id;this.cancel(d);g.toast('指定陪走路線完成，請找理化老師交付。');}else if(d.walk>=20&&p.dogs[d.id].cooldowns.walk<=0){p.dogs[d.id].cooldowns.walk=180;this.gain(d.id,5,'walk:'+d.id+':'+(++p.serial));d.walk=0;}if(d.followTime>=45&&!q||distance(d,g.player)>12||d.stuck>2){this.cancel(d);p.companion=null;g.toast(d.label+'先回休息點，靠近後可以再次邀請。');}continue;}
 if(d.state==='Returning'||d.state==='Relocating'){this.move(d,d.target,dt,2.5);if(distance(d,d.target)<.5){d.state='Rest';d.timer=0;}continue;}
 if(d.state==='Feeding'){if(d.job==='treat'){if(d.timer>2){d.state='Rest';d.job=null;}}else{this.move(d,d.target,dt,2);if(distance(d,d.target)<.7&&d.timer>8){d.state='Rest';d.job=null;}}continue;}
 if(g.meeting.running){d.state='Rest';continue;}
 if(!d.job&&p.dogs[d.id].affinity>=20&&distance(d,g.player)<5&&distance(d,g.player)>2&&g.world.visible(d,g.player)&&d.timer>10){d.state='Greet';d.target=g.world.approach({x:g.player.x+1.3,z:g.player.z},d);d.timer=0;}
 if(['Roam','Greet'].includes(d.state)){this.move(d,d.target,dt,d.state==='Greet'?2.3:1.1);if(distance(d,d.target)<.5||d.timer>14||d.stuck>2){d.state='Rest';d.timer=0;}}else if(d.timer>8){d.state='Roam';d.target=g.world.approach(stops[d.id][Math.floor(g.rng.next()*stops[d.id].length)],d);d.path=[];d.repath=0;d.timer=0;}
 }
 if(!g.meeting.running)this.teacher(dt);if(Math.floor(p.clock/5)!==Math.floor((p.clock-dt)/5))g.onSave();}
 teacher(dt:number){const g=this.g,n=g.npcs.find(n=>n.type==='science_teacher');if(!n)return;const hostile=['Chase','Attack','Search','Recover','hit','ScienceHit','Investigate'].includes(n.state);if(hostile){if(this.teacherPhase===1||this.teacherPhase===2){this.teacherPhase=0;this.nextFeed=this.p.clock+15;for(const d of this.actors)if(d.state==='Feeding'&&!d.job)this.cancel(d);}return;}const route=[{x:23,z:-16},{x:8,z:11},{x:-12,z:13},{x:23,z:-16}];if(this.p.clock>=this.nextFeed&&this.teacherPhase===0){this.teacherPhase=1;n.path=[];n.repath=0;}if(this.teacherPhase===1){n.state='ScienceWalk';g.moveNPC(n,g.world.approach(route[1],n),dt,1.6);if(distance(n,route[1])<1.3){this.teacherPhase=2;this.teacherUntil=this.p.clock+8;n.state='ScienceFeed';for(const d of this.actors)if(!d.job&&!['AssistApproach','AssistContact'].includes(d.state)){d.state='Feeding';d.target={x:d.id==='dog_lion'?7:9,z:11};d.timer=0;d.path=[];d.repath=0;}}}else if(this.teacherPhase===2){n.state='ScienceFeed';if(distance(n,g.player)<12&&g.world.visible(n,g.player)){this.p.feedingSeen=true;this.collect();}if(this.p.clock>=this.teacherUntil){this.teacherPhase=3;n.state='ScienceWalk';n.path=[];n.repath=0;}}else if(this.teacherPhase===3||this.teacherPhase===4){const goal=this.teacherPhase===3?route[2]:route[3];n.state='ScienceWalk';g.moveNPC(n,g.world.approach(goal,n),dt,1.6);if(distance(n,goal)<1.3){if(this.teacherPhase===3){this.teacherPhase=4;n.path=[];n.repath=0;}else{this.teacherPhase=0;this.nextFeed=this.p.clock+180;n.state='Idle';n.timer=0;}}}}
}
