import {Life} from './life';
import {Dogs} from './dogs';
import {dogQuests,humanCapabilities} from './dogs-data';
import {Meeting} from './meeting';
import {campusLayout,CampusLayout,entrances} from './scene';
import {recordKnockdown,CodexGroup} from './knockdowns';
import {balance,Vec,items,itemDefs,students,staff,parentDefs,parents,missions,missionDefs,chapters,center,zoneAt,destination,locations,Step,microphoneRules} from './data';
import {World,distance,norm} from './world';
import {Profile,fresh,reward,purchase} from './save';
export type ItemState='home'|'held'|'worn'|'airborne'|'settled'|'damaged'|'reserved';
export type Item={id:string,type:string,x:number,z:number,y:number,home:Vec,homeY?:number,homeAngle?:number,angle?:number,zone:string,state:ItemState,owner:string|null,pins:string[],broken:boolean,full?:boolean,vx?:number,vz?:number,vy?:number,flight?:string,microphoneThrow?:{flight:string,knownBy:Set<string>},hit:Set<string>,hits:number,age:number,rest:number,papers?:{x:number,z:number,taken:boolean}[]};
export type NPC={id:string,type:string,role:string,label:string,x:number,z:number,home:Vec,hp:number,maxHp:number,state:string,timer:number,cooldown:number,face:Vec,target:Vec,path:Vec[],repath:number,lastSeen:Vec,lost:number,item:string|null,incident:string,called:boolean,retries:number,callEligible:boolean,contactCooldown:number,active:boolean,capabilities?:typeof humanCapabilities,friend?:string,treasure?:string,film:number,lastFilmEscape:number,attack?:any,group?:string,ability?:string,turns:number,cleaned:Set<string>,intro:number,soundInvestigation?:SoundInvestigation};
export type Event={eventId:string,sessionId:number,actorId:string,targetId?:string,sourceId?:string,zoneId:string,timestamp:number,causeId?:string,type:string,data:any};
export type SoundInvestigation={broadcastId:string,itemId:string,resumeState:string,resumeTarget:Vec,resumeTimer:number,started:number,stuck:number,last:Vec};
export type MicrophoneBroadcast={id:string,itemId:string,position:Vec,start:number,until:number,nextPulse:number,knownBy:Set<string>};
export type Attempt={id:string,mission:string,step:number,count:number,seen:Set<string>,started:number,meta:any};
export class RNG{constructor(public seed=6477){}next(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296}pick<T>(a:T[]):T{return a[Math.floor(this.next()*a.length)]}}
export const alertLevel=(score:number)=>score<15?0:score<35?1:score<60?2:score<85?3:4;
export class Game{
 meeting=new Meeting(this);dogs=new Dogs(this);life=new Life(this);
 world=new World();layout:CampusLayout=campusLayout();previous=new Map<string,Vec>();rng:RNG;time=0;session=0;seq=0;mode='normal';player={id:'player_music_teacher',x:21,z:-14,y:0,face:{x:-1,z:0},hp:100,item:null as string|null,wig:null as string|null,glasses:null as string|null,inv:0,dodge:0,dodgeCooldown:0,attack:null as any,attackCooldown:0,slow:0,hidden:false,hideWitness:false,action:'idle',actionTime:0};
 broadcasts=new Map<string,MicrophoneBroadcast>();microphoneCall:{itemId:string,start:number,until:number,text:string}|null=null;
 objects=new Map<string,Item>();npcs:NPC[]=[];props:any[]=[];private baseAlert=0;get alert(){return Math.min(100,this.baseAlert+(this.meeting.running?0:this.life.alert))}set alert(v:number){this.baseAlert=Math.max(0,Math.min(100,this.baseAlert+v-this.alert))}reason='校園一切正常';lastTrouble=-100;eventLog:Event[]=[];listeners:((e:Event)=>void)[]=[];attempt:Attempt|null=null;familyQueue:any[]=[];recentParents:string[]=[];pending:any[]=[];cooldowns=new Map<string,number>();report={damage:0,downed:0,parents:0,maxAlert:0};lastReport:any=null;profile:Profile;onSave=()=>{};onToast=(s:string,dog?:{id:string,gain:number})=>{};tutorial=-1;race:any=null;choir:any=null;notes:string[]=[];serviceReady=0;movement=0;pathBudget=0;cameraVisible:(p:Vec)=>boolean=()=>false;rosterSeed:number;tickMs=0;aiMs=0;stats={ticks:0,events:0};zoneAway=new Map<string,number>();
 constructor(profile=fresh(),seed=6477){this.profile=profile;this.rng=new RNG(seed);this.rosterSeed=seed;this.reset('normal');this.recoverInterruptedMeeting();this.life.recover()}
 recoverInterruptedMeeting(){const pending=this.profile.meeting.pending;if(!pending)return;for(const old of pending.origin?.items||[]){const i=this.objects.get(old.id)||this.createItem(old.type,old.id,old.home);Object.assign(i,old,{hit:new Set(old.hit||[])});}Object.assign(this.player,{item:pending.origin?.item||null,wig:pending.origin?.wig||null,glasses:pending.origin?.glasses||null,x:0,z:-19,hp:100,inv:8});this.profile.meeting.records.push({id:pending.id,seed:pending.seed,modules:pending.selected,cast:pending.cast||[],seconds:Math.round(pending.elapsed||0),reason:'讀檔安全散場',chaos:pending.chaos||0,interruptions:pending.interruptions||0,downed:pending.downed||0,lines:['會議中斷，已安全返回保健室。','原物品與永久進度已保留。']});this.profile.meeting.records=this.profile.meeting.records.slice(-20);this.profile.meeting.cooldown=60;this.profile.meeting.pending=null;this.dogs.returnCampus();}
 get level(){return alertLevel(this.alert)}get step(){return this.attempt?missionDefs[this.attempt.mission].steps[this.attempt.step]:null}get held(){return this.player.item?this.objects.get(this.player.item):null}get chase(){return this.npcs.filter(n=>(['Chase','Attack','Search'].includes(n.state)||n.soundInvestigation?.resumeState==='Search')&&n.role!=='student')}
 emit(type:string,data:any={},actor='player_music_teacher',target?:string,source?:string){const e:Event={eventId:`${this.session}:${++this.seq}`,sessionId:this.session,actorId:actor,targetId:target,sourceId:source,zoneId:zoneAt(this.player),timestamp:this.time,type,data};if(this.meeting.running){e.zoneId='meeting_room';this.meeting.capture(e);this.listeners.forEach(f=>f(e));return e;}if(['CombatResolved','throw','push','propDamaged'].includes(type)&&actor===this.player.id){const item=data.item||this.held?.type;const n=this.npcs.find(n=>n.id===data.npc);this.profile.meeting.campusEvents.push({...e,campusTime:this.profile.meeting.campusClock,kind:type,sourceActorId:actor,targetType:n?.role||'item',itemTypeId:item,gameTime:this.time,activityDay:this.mode,text:type==='CombatResolved'?`使用${itemDefs[item]?.label||'徒手'}擊中${n?.label||'校園人物'}`:type==='throw'?`投擲${itemDefs[item]?.label||'物品'}`:type==='push'?`推動${itemDefs[item]?.label||'椅子'}`:'校園家具受到波及'});this.profile.meeting.campusEvents=this.profile.meeting.campusEvents.slice(-40);}this.eventLog.push(e);if(this.eventLog.length>350)this.eventLog.shift();this.stats.events++;if(['propDamaged','coneDown','spill'].includes(type)&&actor===this.player.id)this.report.damage++;if(actor===this.player.id||['familyArrived','choirDone'].includes(type)){this.profile.statistics[type]=(this.profile.statistics[type]||0)+1;}this.recordCodex(e);this.objective(e);this.tutorialEvent(e);if(type==='lifeEvent'&&actor===this.player.id&&data.eventType!=='lunch'){this.profile.meeting.campusEvents.push({...e,...data,campusTime:this.profile.meeting.campusClock,text:data.resolutionReason});this.profile.meeting.campusEvents=this.profile.meeting.campusEvents.slice(-40);}this.life.capture(e);this.listeners.forEach(f=>f(e));return e}
 recordCodex(e:Event){
 if(e.actorId!==this.player.id)return;
 let group:CodexGroup,id:string;
 if(e.type==='NPCDowned'){
  const n=this.npcs.find(n=>n.id===e.data.npc);if(!n||n.hp!==0)return;
  group=n.role==='student'?'students':'parents';id=n.type;
 }else if(e.type==='propDamaged'){
  const p=this.props.find(p=>p.id===e.data.id);if(!p?.broken)return;
  group='objects';id='prop:'+p.type;
 }else if(['coneDown','spill','itemBroken'].includes(e.type)){
  const i=this.objects.get(e.data.id);if(!i?.broken)return;
  group='objects';id='item:'+i.type;
 }else return;
 if(recordKnockdown(this.profile.knockdownCodex,group,id))this.onSave();
 }
 toast(s:string,dog?:{id:string,gain:number}){this.onToast(s,dog)}
 reset(mode=this.mode,preserveHeld=false){this.meeting.resetTrigger();this.life.resetting=true;for(const c of [...this.life.cases])this.life.finish(c,false,'場景切換');this.life.resetting=false;const carried=preserveHeld?[...this.objects.values()].filter(i=>i.owner===this.player.id):[];this.stopAllBroadcasts();this.microphoneCall=null;this.previous.clear();this.session++;this.pending=[];this.familyQueue=[];this.cancelMission();this.mode=mode;this.layout=campusLayout(mode);this.profile.lastMode=mode;this.objects.clear();this.npcs=[];this.props=[];this.cooldowns.clear();this.zoneAway.clear();this.alert=0;this.lastTrouble=-100;this.reason='校園一切正常';this.report={damage:0,downed:0,parents:0,maxAlert:0};Object.assign(this.player,{x:21,z:-14,hp:100,item:null,wig:null,glasses:null,attack:null,attackCooldown:0,dodge:0,dodgeCooldown:0,hidden:false,inv:0});this.race=null;this.choir=null;
 for(const def of items)this.createItem(def.id,def.id+':0',this.layout.placements[def.id+':0']||center(def.zone));
 for(let i=1;i<3;i++){this.createItem('office_chair','office_chair:'+i,this.layout.placements['office_chair:'+i]);this.createItem('traffic_cone','traffic_cone:'+i,this.layout.placements['traffic_cone:'+i]);}this.createItem('music_stand','music_stand:1',this.layout.placements['music_stand:1']);
 for(const zone of ['classroom','staff_room','music_room','principal_room','courtyard','playground','gate','co_op','infirmary','corridor'])for(let i=0;i<3;i++){const type=zone==='classroom'?(i===2?'chair':'desk'):zone==='infirmary'?(i===0?'bed':i===1?'cabinet':'bench'):(i===0?'table':i===1?'planter':'bench');const id='prop:'+zone+':'+i,p=this.layout.propPositions[id];this.props.push({id,type,zone,...p,home:{...p},w:type==='planter'?.7:type==='bed'?1.5:1.6,d:type==='planter'?.7:type==='bed'?2.6:.8,broken:false,hp:20,hit:0});}
 this.props.push({id:'dummy',type:'dummy',zone:'playground',x:-16,z:18,w:.8,d:.8,hp:10000,broken:false},{id:'podium',type:'podium',zone:'classroom',...locations.podium,w:1.4,d:.8,hp:30,broken:false},{id:'hideTool',type:'shelter',zone:'corridor',...locations.hideTool,w:1.3,d:1.5,hp:50,broken:false});
 if(mode==='anniversary')for(let i=0;i<2;i++)this.props.push({id:'stall:'+i,type:'stall',zone:'courtyard',x:-6+i*12,z:8,w:2.8,d:1.5,hp:35,broken:false});
 this.refreshColliders();
 for(let i=0;i<(mode==='normal'?24:36);i++){let type=students[i%12].id;let zone=['classroom','music_room','courtyard','playground'][Math.floor(i/6)%4];let c=center(zone);this.addNPC(type,'student',{x:c.x-4+(i%6)*1.5,z:c.z+(Math.floor(i/3)%2)*2},'student:'+i)}
 for(let st of staff){let c=center(st.zone);this.addNPC(st.id,'staff',{x:c.x+3,z:c.z},st.id)}
 if(['parent_day','anniversary'].includes(mode))for(let i=0;i<3;i++)this.addNPC(parents[i].id,'visitor',{x:-3+i*3,z:15},'visitor:'+i);
 for(const n of this.npcs){const p=this.world.approach(n,n);Object.assign(n,p);n.home={...p};n.target={...p};}for(const [type,p]of Object.entries({shop_aunt:{x:20.5,z:11.4},nurse:{x:-2,z:-17.2},guard_uncle:{x:5.8,z:20.5},principal:{x:22,z:-3.6}})){const n=this.npcs.find(n=>n.type===type);if(n){Object.assign(n,this.world.approach(p,n));n.home={x:n.x,z:n.z};n.target={...n.home};}}
 for(const old of carried){const fresh=this.objects.get(old.id);if(fresh){old.home={...fresh.home};old.homeY=fresh.homeY;old.homeAngle=fresh.homeAngle;old.zone=fresh.zone;}old.pins=[];old.microphoneThrow=undefined;old.flight=undefined;this.objects.set(old.id,old);if(old.state==='worn')this.player[old.type==='principal_wig'?'wig':'glasses']=old.id;else this.player.item=old.id;}
 for(let n of this.npcs.filter(n=>n.role==='student')){n.friend='student:'+((+n.id.split(':')[1]+1)%24);n.treasure=[...this.objects.values()].find(i=>i.zone===zoneAt(n))?.id;}this.refreshColliders();this.dogs.reset();this.life.reset();this.onSave();this.emit('reset',{mode},'system');}
 createItem(type:string,id:string,p:Vec&{y?:number,angle?:number}){if(this.objects.has(id))return this.objects.get(id)!;const item:Item={id,type,x:p.x,z:p.z,y:p.y||0,homeY:p.y||0,homeAngle:p.angle||0,angle:p.angle||0,home:{x:p.x,z:p.z},zone:zoneAt(p),state:'home',owner:null,pins:[],broken:false,full:type==='trash_bin',hit:new Set(),hits:0,age:0,rest:this.time};this.objects.set(id,item);return item}
 addNPC(type:string,role:string,p:Vec,id=`${role}:${this.session}:${++this.seq}`){let pd=parentDefs[type];let hp=role==='parent'?pd.hp:role==='student'?25+students.findIndex(x=>x.id===type)%4*5:60;const n:NPC={id,type,role,capabilities:humanCapabilities,label:role==='student'?students.find(s=>s.id===type).label+'學生':role==='staff'?staff.find(s=>s.id===type)?.label||type:pd.label+'家長',x:p.x,z:p.z,home:{x:p.x,z:p.z},hp,maxHp:hp,state:role==='parent'?'Chase':'Idle',timer:0,cooldown:0,face:{x:0,z:1},target:{...p},path:[],repath:0,lastSeen:{...this.player},lost:0,item:null,incident:'',called:false,retries:0,callEligible:false,contactCooldown:0,active:false,film:0,lastFilmEscape:-100,turns:0,cleaned:new Set(),intro:0,ability:pd?.ability};this.npcs.push(n);return n}
 supportHeight(p:Vec){let h=0;for(const f of this.layout.furniture)if(f.top!==undefined&&Math.abs(p.x-f.x)<=f.w/2&&Math.abs(p.z-f.z)<=f.d/2)h=Math.max(h,f.top+.03);for(const prop of this.props)if(!prop.broken&&['podium','table','desk'].includes(prop.type)&&Math.abs(p.x-prop.x)<=prop.w/2&&Math.abs(p.z-prop.z)<=prop.d/2)h=Math.max(h,prop.type==='podium'?1.06:.89);if(this.mode!=='normal'&&Math.abs(p.x)<5&&Math.abs(p.z-4)<3)h=Math.max(h,.24);return h;}
 refreshColliders(){this.world.dynamic=[...this.layout.furniture.filter(f=>f.solid).map(f=>({id:f.id,x:f.x,z:f.z,w:f.w,d:f.d})),...this.props.filter(p=>p.type!=='dummy').map(p=>({id:p.id,x:p.x,z:p.z,w:p.w,d:p.d})),...Array.from(this.objects.values()).filter(i=>itemDefs[i.type].category.some(x=>['fixed','pushable'].includes(x))&&!['held','worn','airborne'].includes(i.state)).map(i=>({id:i.id,x:i.x,z:i.z,w:i.type==='piano'?2: .7,d:i.type==='piano'?1.1:.7}))]}
 take(id:string,who='player_music_teacher'){let i=this.objects.get(id);if(!i||!itemDefs[i.type].category.includes('portable')||itemDefs[i.type].category.includes('fixed')||i.full||i.papers?.some(p=>!p.taken))return false;let holder=who===this.player.id?this.player:this.npcs.find(n=>n.id===who);if(!holder||holder.item||['held','worn','reserved'].includes(i.state))return false;this.stopBroadcast(i.id);i.microphoneThrow=undefined;holder.item=id;i.owner=who;i.state='held';i.vx=i.vz=i.vy=0;i.flight=undefined;i.hit.clear();if(who===this.player.id){this.player.action='pickup';this.player.actionTime=.35;this.emit('take',{item:i.type,id},who,id);if(['principal_wig','principal_glasses','trophy','laptop'].includes(i.type))this.notice('重要物品被搬走',10,'take:'+id,who,8)}this.refreshColliders();return true}
 detach(i:Item){if(i.owner===this.player.id){if(this.player.item===i.id)this.player.item=null;if(this.player.wig===i.id)this.player.wig=null;if(this.player.glasses===i.id)this.player.glasses=null}else{let n=this.npcs.find(n=>n.id===i.owner);if(n?.item===i.id)n.item=null}i.owner=null}
 drop(id=this.player.item,p?:Vec){let i=this.objects.get(id);if(!i||i.owner!==this.player.id)return false;this.detach(i);let pos=p||this.world.move(this.player,this.player.face.x*.85,this.player.face.z*.85,.15);Object.assign(i,{x:pos.x,z:pos.z,y:this.supportHeight(pos),angle:0,state:'settled',rest:this.time});this.player.action='drop';this.player.actionTime=.3;this.emit('drop',{item:i.type,id:i.id},this.player.id,i.id);this.refreshColliders();this.checkDelivery(i);if(i.type==='exam_papers'&&distance(this.player,locations.podium)<2.5&&distance(i,locations.podium)<2&&this.world.visible(this.player,locations.podium)){i.x=locations.podium.x;i.z=locations.podium.z;i.y=1.06;if(this.tutorial===2)this.emit('deliverTutorial',{id:i.id});}return true}
 wear(id:string){let i=this.objects.get(id);if(!i||i.owner!==this.player.id||!itemDefs[i.type].category.includes('wearable'))return false;let slot=i.type==='principal_wig'?'wig':'glasses';if(this.player[slot])return false;this.player.item=null;this.player[slot]=id;i.state='worn';this.player.action='wear';this.player.actionTime=.7;this.emit('wear',{item:i.type,id});return true}
 returnItem(id:string){let i=this.objects.get(id);if(!i||i.owner!==this.player.id||distance(this.player,i.home)>2.7){this.toast('請帶到原掛點／原位置，再歸還');return false}this.stopBroadcast(i.id);i.microphoneThrow=undefined;this.detach(i);Object.assign(i,{...i.home,y:i.homeY||0,angle:i.homeAngle||0,state:'home',broken:false,full:i.type==='trash_bin',rest:this.time});this.emit('return',{item:i.type,id});this.refreshColliders();return true}
 resetObjectiveItems(){if(!this.attempt)return;for(let i of this.objects.values())if(i.pins.includes(this.attempt.id)){this.stopBroadcast(i.id);i.microphoneThrow=undefined;this.detach(i);Object.assign(i,{...i.home,state:'home',y:i.homeY||0,angle:i.homeAngle||0,vx:0,vz:0,vy:0,flight:undefined,papers:undefined});}this.refreshColliders();this.toast('任務物件已按原 ID 歸位')}
 throwItem(){if(this.meeting.phase==='OPENING')this.meeting.activate();if(this.meeting.running&&this.meeting.phase!=='ACTIVE')return false;let i=this.held;if(!i||this.player.hidden)return false;let projectiles=[...this.objects.values()].filter(i=>i.state==='airborne').length;if(projectiles>=(this.profile.settings.quality==='low'?6:8)){this.toast('先等飛行物落地');return false}let target=this.npcs.filter(n=>n.active&&n.hp>0&&distance(n,this.player)<8&&this.world.visible(this.player,n)&&['Chase','Attack'].includes(n.state)).sort((a,b)=>distance(a,this.player)-distance(b,this.player)).find(n=>{let d=norm(n.x-this.player.x,n.z-this.player.z);return d.x*this.player.face.x+d.z*this.player.face.z>.82});let f=target&&!i.type.startsWith('dog_')?norm(target.x-this.player.x,target.z-this.player.z):this.player.face;this.detach(i);Object.assign(i,{x:this.player.x+f.x*.6,z:this.player.z+f.z*.6,y:1.25,state:'airborne',vx:f.x*9,vz:f.z*9,vy:3.4,age:0,flight:`projectile:${this.session}:${++this.seq}`,hits:0});if(i.type==='wireless_microphone')i.microphoneThrow={flight:i.flight,knownBy:new Set(this.npcs.filter(n=>n.hp>0&&['Chase','Attack','Search'].includes(n.state)&&this.sees(n)).map(n=>n.id))};i.hit.clear();this.player.action='throw';this.player.actionTime=.4;this.emit('throw',{item:i.type,id:i.id});if(this.attempt&&i.type==='basketball')this.attempt.meta.throws=(this.attempt.meta.throws||0)+1;if(i.type==='exam_papers'){i.papers=undefined;this.emit('scatter',{id:i.id});this.notice('紙張散了一地',4,'scatter:'+i.flight,this.player.id,6)}return true}
 attack(){if(this.meeting.phase==='OPENING')this.meeting.activate();if(this.meeting.running&&this.meeting.phase!=='ACTIVE')return false;if(!this.meeting.running&&this.player.inv>1)this.player.inv=0;if(this.player.hidden||this.player.attackCooldown>0)return false;let def=this.held?itemDefs[this.held.type]:null;this.player.attack={id:`attack:${++this.seq}`,age:0,hit:new Set(),resolved:false,damage:def?def.damage:10,reach:def?.reach||1.2,item:this.held?.type};this.player.attackCooldown=def?.cooldown||.45;this.player.action='attack';this.player.actionTime=this.player.attackCooldown;this.emit('swing',{item:def?.id});this.meeting.considerSwing();return true}
 dodge(){if(this.player.hidden||this.player.dodgeCooldown>0)return false;this.player.dodge=.25;this.player.dodgeCooldown=1.4;this.player.inv=Math.max(this.player.inv,.15);this.player.action='dodge';this.player.actionTime=.25;this.emit('dodge');return true}
 rollCall(){if(this.meeting.running)return this.meeting.secondary();
 if((this.cooldowns.get('roll')||0)>this.time){this.toast('點名還在冷卻');return false}
 this.cooldowns.set('roll',this.time+microphoneRules.callCooldown);
 const amplified=this.held?.type==='wireless_microphone',radius=amplified?microphoneRules.callRadius:6,names:string[]=[];
 for(const n of this.npcs)if((n.role==='student'||!amplified&&n.role==='visitor')&&n.hp>0&&distance(n,this.player)<radius&&this.world.visible(this.player,n)&&['Idle','Walk','Spectate','Mediate'].includes(n.state)){
  n.face=norm(this.player.x-n.x,this.player.z-n.z);n.state='CallTurn';n.timer=0;
  n.target={x:this.player.x+(names.length%3-1)*1.1,z:this.player.z+1.5+Math.floor(names.length/3)};n.path=[];n.repath=0;names.push(n.id);
 }
 this.player.action='roll';this.player.actionTime=1;
 if(amplified)this.microphoneCall={itemId:this.held.id,start:this.time,until:this.time+1,text:this.seq%2?'請同學靠近一點。':'這是集合，不是逃難。'};
 this.emit('rollCall',{names,amplified,radius});if(!amplified)this.toast('各位同學，請到老師這裡集合。');return true;
 }
 startBroadcast(i:Item){
 const thrown=i.microphoneThrow;i.microphoneThrow=undefined;
 if(!thrown||thrown.flight!==i.flight||!i.flight?.startsWith('projectile:')||i.state!=='settled'||i.owner||this.broadcasts.size>=microphoneRules.maxBroadcasts)return false;
 const b:MicrophoneBroadcast={id:thrown.flight,itemId:i.id,position:{x:i.x,z:i.z},start:this.time,until:this.time+microphoneRules.broadcastSeconds,nextPulse:this.time+microphoneRules.pulseSeconds,knownBy:thrown.knownBy};
 this.broadcasts.set(i.id,b);this.emit('microphoneBroadcast',{id:i.id,broadcastId:b.id,x:i.x,z:i.z,duration:microphoneRules.broadcastSeconds});return true;
 }
 finishSoundInvestigation(n:NPC){
 const investigation=n.soundInvestigation;if(!investigation)return;
 if(n.state==='SoundInvestigate'){n.state=investigation.resumeState;n.target={...investigation.resumeTarget};n.timer=investigation.resumeTimer+this.time-investigation.started;n.path=[];n.repath=0;}
 n.soundInvestigation=undefined;
 }
 stopBroadcast(itemId:string){
 const b=this.broadcasts.get(itemId);if(!b)return;
 this.broadcasts.delete(itemId);for(const n of this.npcs)if(n.soundInvestigation?.broadcastId===b.id)this.finishSoundInvestigation(n);
 this.emit('microphoneBroadcastStop',{id:itemId,broadcastId:b.id},'system');
 }
 stopAllBroadcasts(){for(const id of [...this.broadcasts.keys()])this.stopBroadcast(id)}
 removeItem(id:string){const i=this.objects.get(id);if(!i)return false;this.stopBroadcast(id);if(this.microphoneCall?.itemId===id)this.microphoneCall=null;this.detach(i);this.previous.delete(id);this.objects.delete(id);this.refreshColliders();return true}
 updateMicrophones(){
 if(this.microphoneCall&&(this.time>=this.microphoneCall.until||this.held?.id!==this.microphoneCall.itemId))this.microphoneCall=null;
 for(const b of [...this.broadcasts.values()]){
  const i=this.objects.get(b.itemId);
  if(!i||i.owner||i.state!=='settled'||this.time>=b.until){this.stopBroadcast(b.itemId);continue}
  if(this.time>=b.nextPulse){b.nextPulse+=microphoneRules.pulseSeconds;this.emit('microphonePulse',{id:i.id,broadcastId:b.id},'system')}
 }
 }
 considerBroadcast(n:NPC){
 if(this.choir&&n.role==='student'||this.attempt?.meta.choristers?.includes(n.id)&&['gather','choir'].includes(this.step?.kind)||n.role==='visitor'&&this.step?.kind==='seat'||n.type==='principal'&&this.pending.some(e=>e.type==='speechDone'))return;
 if(n.hp<=0||n.soundInvestigation||n.type==='nurse'||n.type==='protective'||!['Idle','Walk','Spectate','Investigate','Search'].includes(n.state))return;
 // Chase/Attack, calls, task seats, guarding and item return retain priority.
 for(const b of this.broadcasts.values()){
  if(b.knownBy.has(n.id)||distance(n,b.position)>microphoneRules.hearingRadius||distance(n,b.position)<.8||!this.world.visible(n,b.position)||(this.cooldowns.get('mic:'+n.id+':'+b.itemId)||0)>this.time)continue;
  if(n.state==='Search'&&this.sees(n))continue;
  if(this.pathBudget<=0)return;
  this.pathBudget--;const approach=this.world.approach(b.position,n);if(this.world.blocked(approach,.32))continue;
  const target=approach,path=this.world.path(n,target);if(!path.length)continue;
  n.soundInvestigation={broadcastId:b.id,itemId:b.itemId,resumeState:n.state,resumeTarget:{...n.target},resumeTimer:n.timer,started:this.time,stuck:0,last:{x:n.x,z:n.z}};
  n.state='SoundInvestigate';n.timer=0;n.target={...target};n.path=path;n.repath=.5;
  this.cooldowns.set('mic:'+n.id+':'+b.itemId,this.time+microphoneRules.investigationCooldown);
  this.emit('soundInvestigated',{npc:n.id,id:b.itemId,broadcastId:b.id},n.id);break;
 }
 }
 microphoneSignals(){
 const signals=[...this.broadcasts.values()].map(b=>({id:b.itemId,x:b.position.x,z:b.position.z,start:b.start,text:this.time-b.start<1.5?'請不要在走廊奔跑。':'物品使用完畢，請歸位。',kind:'broadcast'}));
 if(this.microphoneCall)signals.push({id:this.microphoneCall.itemId,x:this.player.x,z:this.player.z,start:this.microphoneCall.start,text:this.microphoneCall.text,kind:'call'});
 return signals;
 }
 hide(which:string){if(this.player.hidden){this.player.hidden=false;this.player.action='leaveHide';this.player.actionTime=.4;return}let seen=this.npcs.some(n=>n.active&&['Chase','Search','Attack'].includes(n.state)&&this.sees(n));this.player.hidden=true;this.player.hideWitness=seen;this.emit('hide',{witnessed:seen});this.toast(seen?'有人看見妳躲進去，會過來查看。':'屏住呼吸，等動靜過去。')}
 sees(n:NPC){if(distance(n,this.player)>10||!this.world.visible(n,this.player))return false;if(this.player.hidden&&!this.player.hideWitness)return false;let f=norm(this.player.x-n.x,this.player.z-n.z);return distance(n,this.player)<2||f.x*n.face.x+f.z*n.face.z>-.5}
 notice(reason:string,points:number,key:string,actor=this.player.id,radius=10){if(this.meeting.running)return;if(actor!==this.player.id)return;let witnesses=this.npcs.filter(n=>n.hp>0&&distance(n,this.player)<radius&&this.world.visible(n,this.player)&&n.role!=='parent');this.lastTrouble=this.time;this.player.hidden=false;if(!witnesses.length){this.reason='附近傳來動靜';for(let n of this.npcs)if(n.role==='staff'&&distance(n,this.player)<radius+5){n.state='Investigate';n.target={...this.player};}return}if((this.cooldowns.get(key)||0)>this.time)return;this.cooldowns.set(key,this.time+1);this.alert=Math.min(100,this.alert+points*(this.mode==='final_exam'?1.5:1));this.reason=reason;this.report.maxAlert=Math.max(this.report.maxAlert,this.level);this.emit('notice',{reason,points,witnesses:witnesses.map(x=>x.id)},actor);
 for(let n of witnesses){if(n.role==='student')this.reactStudent(n);else if(!['nurse'].includes(n.type)&&!['Chase','Attack','Recover'].includes(n.state)){n.state=this.level>=2?'Chase':'Investigate';n.target={...this.player};n.lastSeen={...this.player}}} }
 reactStudent(n:NPC){if(['Recover','Attack','Call','Chase','Flee'].includes(n.state))return;switch(n.type){case 'timid':n.state='Flee';break;case 'fighter':case 'athlete':n.state='Chase';break;case 'tattletale':n.state='Tattle';n.target=center('staff_room');break;case 'filmer':n.state='Film';n.film=0;break;case 'friend':n.state='Help';n.target={...this.player};break;case 'mediator':n.state='Mediate';this.toast('同學：老師，請先冷靜。');break;case 'scavenger':n.state='PickUp';break;case 'guardian':n.state='Chase';break;case 'prankster':n.state='Prank';break;case 'reader':if(distance(n,this.player)<2)n.state='Flee';break;default:n.state='Spectate';break}n.timer=0;}
 damageNPC(n:NPC,damage:number,source:string,projectile=false){if(!this.npcs.includes(n)||(n as any).capabilities?.damageable===false||damage<=0)return false;delete (n as any).dogControl;if(n.type==='science_teacher')(n as any).flashUntil=this.time+.22;if(this.meeting.running)return this.meeting.hit(n,source,projectile);if(n.hp<=0||n.type==='nurse'||zoneAt(n)==='infirmary')return false;if(n.role==='parent'&&['briefcase','umbrella'].includes(n.type)&&n.state!=='Attack'&&n.cooldown<.5){let f=norm(this.player.x-n.x,this.player.z-n.z);if(f.x*n.face.x+f.z*n.face.z>.65&&(n.type==='briefcase'||projectile)){this.emit('block',{npc:n.id});return false}}
 if(n.state==='Call'){n.retries++;n.contactCooldown=this.time+8;n.callEligible=n.retries<=1;}n.hp=Math.max(0,n.hp-damage);n.cooldown=Math.max(n.cooldown,.3);n.attack=null;const recoveryHit=this.life.hit(n);this.emit('CombatResolved',{damage,npc:n.id,projectile,recoveryHit},this.player.id,n.id,source);if(!recoveryHit)this.notice('有人受到波及',5,'hit:'+n.id);if(n.role==='student'){if(!n.incident){n.incident=`incident:${this.session}:${++this.seq}`;n.callEligible=this.time>=n.contactCooldown&&this.rng.next()<(this.level>=2?.5:.35);}if(n.callEligible&&!n.called&&n.hp>0){n.state='Flee';n.timer=0}else this.reactStudent(n)}else if(n.role==='visitor'){if(this.parentCount()<3){n.role='parent';n.state='Chase';this.report.parents++;this.emit('visitorChase',{id:n.id})}else n.state='Spectate'}else n.state='Chase';if(n.type==='science_teacher'&&n.hp>0){n.state='ScienceHit';n.timer=0;}
 if(n.hp===0){n.state='Recover';n.timer=8;n.attack=null;this.report.downed++;this.notice('人物跌坐暈眩',8,'down:'+n.id);this.emit('NPCDowned',{npc:n.id},this.player.id,n.id,source);if(n.item){let i=this.objects.get(n.item);this.detach(i);Object.assign(i,{x:n.x,z:n.z,state:'settled',y:0,rest:this.time});}}
 else{let f=norm(n.x-this.player.x,n.z-this.player.z);let p=this.world.move(n,f.x*(n.type==='armored'?.15:.65),f.z*(n.type==='armored'?.15:.65));n.x=p.x;n.z=p.z;}return true}
 damagePlayer(amount:number,n:NPC){if(this.meeting.running&&this.meeting.phase!=='ACTIVE')return;if(this.player.inv>0||this.player.hidden&&!this.player.hideWitness)return;this.player.hp=Math.max(0,this.player.hp-amount);this.player.inv=.65;this.player.action='hit';this.player.actionTime=.3;if(this.dogs.petJob)this.dogs.cancel(this.dogs.actor(this.dogs.petJob.dog));let f=norm(this.player.x-n.x,this.player.z-n.z);let p=this.world.move(this.player,f.x*.6,f.z*.6);this.player.x=p.x;this.player.z=p.z;this.emit('playerHit',{amount,npc:n.id},n.id);if(this.meeting.running)this.meeting.fold=null;if(this.player.hp===0){if(this.meeting.running){this.meeting.requested='再倒地';}else this.rescue();}}
 rescue(){if(this.meeting.running){this.meeting.end('再倒地');return;}let report={...this.report,mode:this.mode,time:Math.round(this.time),session:this.session};this.lastReport=report;let mode=this.mode;this.reset(mode);Object.assign(this.player,{x:0,z:-19,hp:100});this.emit('rescue',{report},'system');this.toast(`事件報告：翻倒 ${report.damage}、暈眩 ${report.downed}、家長 ${report.parents}、最高警戒 ${report.maxAlert}`)}
 parentCount(){return this.npcs.filter(n=>n.role==='parent').length}
 queueParent(incident:string,type?:string){if(this.familyQueue.some(q=>q.incident===incident)||this.familyQueue.length>=3)return false;this.alert=Math.max(35,this.alert);let pool=parents.filter(p=>this.level>=4||p.tier!=='special'&&(this.level>=3||p.tier==='normal'));let weighted=pool.flatMap(p=>Array(this.recentParents.includes(p.id)?1:3).fill(p));let selected=type||this.rng.pick(weighted).id;this.familyQueue.push({incident,type:selected,at:this.time+6});let guard=this.npcs.find(n=>n.type==='guard_uncle');if(guard){guard.state='Gate';guard.timer=0;}this.toast(`${parentDefs[selected].label}家長六秒後到校門`);this.emit('familyScheduled',{incident,type:selected},'system');return true}
 spawnParent(type:string){let def=parentDefs[type];if(!def||this.parentCount()+def.slotCost>3)return false;let group=`group:${++this.seq}`;for(let i=0;i<def.slotCost;i++){let subtype=i===0?type:type==='duo'?'duo':i===1?'sports':'spatula';let n=this.addNPC(subtype,'parent',{x:-1.5+i*1.5,z:24});n.group=group;n.intro=1;n.state='Enter';n.lastSeen={...this.player};if(type==='protective'){let child=this.npcs.filter(x=>x.role==='student').sort((a,b)=>distance(a,this.player)-distance(b,this.player))[0];n.home={x:child.x,z:child.z};n.lastSeen={...n.home};}if(type==='duo')n.turns=i;if(type==='camper'){let chair=this.createItem('office_chair','camp-chair:'+group,{x:0,z:15});n.home={x:0,z:15};this.refreshColliders()}}this.report.parents+=def.slotCost;this.recentParents=[...this.recentParents.slice(-1),type];this.meeting.parentArrived(def.slotCost);this.emit('familyArrived',{type,count:def.slotCost},'system');return true}
 startMission(id:string){let m=missionDefs[id];if(!m||m.mode!==this.mode)return false;for(const c of [...this.life.cases])this.life.finish(c,false,'任務優先');this.cancelMission();this.attempt={id:`attempt:${this.session}:${++this.seq}`,mission:id,step:0,count:0,seen:new Set(),started:this.time,meta:{throws:0,placed:{},maxParents:0,startLevel:this.level,searchSeen:false,cleanSeen:false,stealth:true}};
 // Stage existing identities and additional explicitly-required instances, never clone owned IDs.
 const needs:Record<string,number>={};for(let s of m.steps)if(s.item&&itemDefs[s.item])needs[s.item]=Math.max(needs[s.item]||0,s.count||1);for(let [type,count]of Object.entries(needs)){if(type==='coffee_cup')continue;let list=[...this.objects.values()].filter(i=>i.type===type);for(let k=list.length;k<count;k++){const home=type==='cardboard_box'?{x:20.5+(k-1)*.8,z:12.8,y:1}:type==='stage_score'?{x:-26.8+k*.6,z:-4,y:.92}:['exam_a','exam_b','envelope','script'].includes(type)?{x:18+k*.35,z:-18,y:1}:center(itemDefs[type].zone);list.push(this.createItem(type,`${type}:task:${k}`,home))}for(let i of list.slice(0,count))i.pins.push(this.attempt.id)}
 if(['q02','cc03'].includes(id)){let type=id==='q02'?'recorder':'spinning_top',i=[...this.objects.values()].find(i=>i.type===type),n=this.npcs.find(n=>n.type===(id==='q02'?'guardian':'prankster'));this.detach(i);i.state='settled';this.take(i.id,n.id)}
 if(['q10','fe02'].includes(id)){let i=[...this.objects.values()].find(i=>i.type==='wall_clock');if(!i.owner)Object.assign(i,{x:-9,z:-10,state:'settled'})}
 if(['q06','an04'].includes(id)){for(let [k,i]of [...this.objects.values()].filter(i=>i.type==='traffic_cone').slice(0,3).entries()){this.detach(i);Object.assign(i,{x:-24+k*1.8,z:18,y:0,state:'home',broken:false});i.pins.push(this.attempt.id)}}
 if(id==='q09'){this.alert=Math.max(65,this.alert);this.lastTrouble=this.time;this.attempt.meta.startLevel=3;this.reason='練習：請讓校園自然安靜下來'}
 if(['q07','q18','q19','q21'].includes(id)){if(id==='q07'){this.queueParent('task:'+this.attempt.id+':1','spatula');this.queueParent('task:'+this.attempt.id+':2','sports')}else this.queueParent('task:'+this.attempt.id,id==='q18'?'shopping_bag':id==='q19'?'neat':'sports')}
 if(['cc02','cc03'].includes(id)){this.attempt.meta.choristers=Array.from({length:6},(_,k)=>'student:'+(12+k));if(id==='cc03')this.attempt.meta.choristers[5]=this.npcs.find(n=>n.type==='prankster').id;}
 if(id==='q20'){let n=this.npcs.find(n=>n.type==='filmer');this.notes.push(`拍片學生常在${zoneAt(n)==='classroom'?'一般教室':'中庭'}，接近互動可讓他開始舉機。`)}
 if(id==='q22')for(let p of this.props.filter(p=>p.zone==='classroom'&&p.type!=='podium'))p.broken=true;
 if(id==='q23'){let i=[...this.objects.values()].find(i=>i.type==='laptop');let route=this.rng.pick([['scavenger','guardian','reader'],['guardian','friend','scavenger'],['reader','mediator','guardian']]);this.attempt.meta.route=route;this.attempt.meta.routeIndex=0;this.detach(i);i.state='settled';let n=this.npcs.find(n=>n.type===route[0]);this.take(i.id,n.id);this.notes=[`主任：${students.find(s=>s.id===route[0]).label}學生拿了筆電。請和同學談話追蹤。`]}
 if(id==='an01')this.props.find(p=>p.zone==='courtyard'&&p.type==='table').pins=this.attempt.id;
 this.refreshColliders();this.emit('missionStart',{id});this.toast(m.label+'：'+m.steps[0].text);return true}
 cancelMission(){if(this.attempt){for(let i of this.objects.values())i.pins=i.pins.filter(x=>x!==this.attempt.id);this.attempt=null;}for(let p of this.props)p.pins=undefined;this.race=null;this.choir=null}
 increment(e:Event,key?:string){let a=this.attempt;if(!a)return;if(key){if(a.seen.has(key))return;a.seen.add(key)}a.count++;this.emitProgress();if(a.count>=(this.step.count||1))this.advance()}
 emitProgress(){this.toast(`${missionDefs[this.attempt.mission].label}：${this.attempt.count}/${this.step.count||1}`)}
 advance(){let a=this.attempt,m=missionDefs[a.mission];a.step++;a.count=0;a.seen.clear();a.meta.placed={};if(a.step<m.steps.length){this.toast(m.steps[a.step].text);return}let rating=a.meta.throws>5?'練習':a.meta.stealth===false?'完成':'金牌';let first=reward(this.profile,m.id,m.reward);if(!this.profile.completedMissionIds.includes(m.id))this.profile.completedMissionIds.push(m.id);this.profile.bestRatings[m.id]=rating;if(m.title&&!this.profile.titleIds.includes(m.title))this.profile.titleIds.push(m.title);if(m.mode!=='normal'){let all=missions.filter(x=>x.mode===m.mode);if(all.every(x=>this.profile.completedMissionIds.includes(x.id))){reward(this.profile,'chapter:'+m.mode,80);if(!this.profile.completedChapters.includes(m.mode))this.profile.completedChapters.push(m.mode)}}this.cancelMission();this.onSave();this.emit('missionComplete',{id:m.id,rating,first});this.toast(`${m.label}完成 · ${rating}${first?' +'+m.reward+'點':'（重玩不重複給點）'}`)}
 objective(e:Event){let a=this.attempt,s=this.step;if(!a||!s||e.actorId!=='player_music_teacher'&& !['naturalCalm','search','speechDone','gathered','wigFound','escape','raceDone','choirDone','familyArrived','filmEscape'].includes(e.type))return;
 if(e.type==='notice'&&s.params?.stealth)a.meta.stealth=false;
 if(['swing','throw'].includes(e.type)&&s.kind==='calm'){a.meta.startLevel=0;this.toast('安靜練習需重試：此次有搗亂')}
 let match=false,key=e.data.id||e.data.npc||e.eventId;
 switch(s.kind){case 'brew':match=e.type==='coffee';break;case 'deliver':match=e.type==='deliver'&&e.data.item===s.item&&e.data.zone===s.zone;break;case 'return':match=e.type==='return'&&e.data.item===s.item;break;case 'wearVisit':match=e.type==='wearVisit'&&e.data.item===s.item&&e.data.zone===s.zone;break;case 'strikeProps':match=e.type==='strikeProp'&&e.data.item===s.item;key=e.data.propType;break;case 'audience':match=e.type==='audience';key=e.data.npc;break;case 'bowl':match=e.type==='coneDown'&&e.data.item==='basketball';if(s.params?.safeStalls&&this.props.some(p=>p.type==='stall'&&p.broken)){match=false;this.toast('攤位受損，請重試保齡球')};break;case 'escape':match=e.type==='escape'&&a.meta.maxParents>=(s.params?.parents||1)&&e.data.level<a.meta.peakLevel;break;case 'calm':match=e.type==='naturalCalm'&&a.meta.startLevel>=3;break;case 'wigTrophy':match=e.type==='wigFound';break;case 'performance':match=e.type==='performance'&&e.data.item===s.item&&e.data.audience>=2;key=e.data.zone;break;case 'race':match=e.type==='raceDone';break;case 'reflect':match=e.type==='reflect';break;case 'cleanEscape':match=e.type==='search'&&a.meta.cleanSeen;break;case 'cameraEscape':match=e.type==='filmEscape';key=e.eventId;break;case 'searchShop':match=e.type==='drink'&&a.meta.searchSeen&&this.level<=1&&!this.chase.some(n=>n.state==='Chase'||n.state==='Attack');break;case 'drink':match=e.type==='drink';break;case 'restore':match=e.type==='restore'&&e.data.zone===s.zone;break;case 'teach':match=e.type==='teach'&&e.data.zone===s.zone&&this.level===0&&!this.chase.length;break;case 'seat':match=e.type==='seat';break;case 'respond':match=e.type==='respond';key=e.data.personality;break;case 'photo':match=e.type==='photo'&&e.data.students>=3&&e.data.visitors>=1;break;case 'speech':match=e.type==='speechDone';break;case 'gather':match=e.type==='gathered'&&e.data.count>=6;break;case 'choir':match=e.type==='choirDone';break;case 'answerTime':match=e.type==='answerTime'&&e.data.correct;break;case 'invigilate':match=e.type==='invigilate';break;case 'collect':match=e.type==='collect';break;case 'dummy':match=e.type==='dummy'&&['badminton_racket','table_tennis_racket'].includes(e.data.item);key=e.eventId;break;}
 if(match)this.increment(e,key)}
 targets():any[]{let out:any[]=this.life.targets();out.push(...this.dogs.visible.map(d=>({...d,type:'dog'})));if(this.meeting.running){out.push({id:'meeting-exit',type:'meeting-exit',label:'離席',x:0,z:9.4});if(this.meeting.selected.includes('whiteboard'))out.push({id:'meeting-board',type:'meeting-board',label:'翻白板／調整議程',x:4.5,z:7.8});}let s=this.step;const dogQuest=dogQuests.find(q=>q.id===this.profile.dogs.activeQuest);if(!this.meeting.running&&dogQuest&&'item' in dogQuest&&this.held?.id===dogQuest.id+':unique')out.push({id:'dog-place:'+dogQuest.id,type:'marker',label:'定位 '+itemDefs[dogQuest.item].label+'（E）',...dogQuest.goal});if(this.held?.type==='exam_papers')out.push({id:'tutorial:podium',type:'marker',label:'放下考卷到教室講臺（E）',...locations.podium});if(s?.kind==='return'){let i=[...this.objects.values()].find(i=>i.type===s.item&&i.pins.includes(this.attempt.id));if(i?.owner===this.player.id)out.push({id:'return:'+i.id,type:'marker',label:'歸還 '+itemDefs[i.type].label,...i.home,itemId:i.id})}
 if(s&&['deliver','place'].includes(s.kind)&&this.held?.type===s.item){for(let k=0;k<(s.count||1);k++)out.push({id:'destination:'+k,type:'marker',label:s.kind==='place'?'定位 '+(k+1):'交付 '+itemDefs[s.item]?.label,...destination(s,k),index:k})}
 for(let i of this.objects.values())if(!['held','worn','reserved'].includes(i.state)&&!(i.state==='airborne'&&i.y>1.4)){if(i.papers?.some(p=>!p.taken)){for(let [k,p]of i.papers.entries())if(!p.taken)out.push({id:i.id+':paper:'+k,parentId:i.id,index:k,type:'paper',label:'拾回考卷 '+(k+1),x:p.x,z:p.z});}else out.push({...i,id:i.id,type:'item',itemType:i.type,label:itemDefs[i.type].label});}
 for(let n of this.npcs)if(n.hp>0)out.push({...n,type:'npc',label:n.label});for(let p of this.props)out.push({...p,type:'prop',propType:p.type,label:({table:'桌子',desk:'課桌',chair:'椅子',planter:'花盆',bench:'長椅',dummy:'練習假人',bed:'休息床',cabinet:'藥櫃',shelter:'工具間藏點',podium:'教室講臺',stall:'活動攤位'})[p.type]||p.type});
 if(!this.meeting.running)out.push({id:'board',type:'board',label:'今日待辦',x:23,z:-15},{id:'stage',type:'stage',label:this.mode==='choir_contest'?'合唱舞臺':'活動舞臺',...locations.stage},{id:'hidePodium',type:'hide',label:'講臺後藏點',...locations.hidePodium});return out}
 nearest(){let step=this.step;let priority=(t:any)=>{if(t.type==='marker'&&this.held)return 0;if(t.type==='prop'&&(step?.item==='scene_table'&&t.propType==='table'||step?.kind==='restore'&&t.broken))return 0;if(t.id==='podium'&&['answerTime','invigilate','collect','teach'].includes(step?.kind))return 0;if(t.id==='stage'&&['choir','photo','speech','gather'].includes(step?.kind))return 0;if(t.itemType==='coffee_machine'&&(step?.item==='coffee_cup'||step?.kind==='brew'))return 0;if(t.type==='item'&&!this.player.item){if(t.itemType===step?.item)return 0;const category=itemDefs[t.itemType].category;return category.includes('portable')?1:category.includes('fixed')?2:3;}if(t.type==='life')return t.priority??0;if(t.type==='dog')return 1;if(t.type==='npc')return 2;return 3};return this.targets().filter(t=>distance(t,this.player)<2.5&&this.world.visible(t,this.player)).sort((a,b)=>priority(a)-priority(b)||distance(a,this.player)-distance(b,this.player))[0]}
 checkDelivery(i:Item){let s=this.step;if(!s||s.kind!=='deliver'||i.type!==s.item||!i.pins.includes(this.attempt.id))return false;let targets=Array.from({length:s.count||1},(_,k)=>destination(s,k));if(!targets.some(t=>distance(i,t)<2))return false;const dest=targets.find(t=>distance(i,t)<2)!;Object.assign(i,{x:dest.x,z:dest.z,y:this.supportHeight(dest),angle:0});i.state='settled';i.rest=this.time;this.emit('deliver',{item:i.type,id:i.id,zone:s.zone});return true}
 interact(target=this.nearest(),action='default'):any{if(!this.meeting.running&&target?.type==='life'&&action==='default')return this.life.interact(target.id);if(target?.type==='dog')return this.dogs.pet(target.id);if(target?.id==='science_teacher'){if(this.dogs.introduce())return 'dogs';return;}if(this.meeting.running){if(this.meeting.phase==='OPENING')this.meeting.activate();if(this.meeting.phase!=='ACTIVE')return;if(action==='useHeld'||action==='roll')return this.meeting.secondary();if(target?.id==='meeting-exit')return this.meeting.leave();if(target?.type==='npc')return this.toast(target.label+'：請依照議程進行。');if(target?.type==='meeting-board')return this.meeting.secondary();}if(this.player.hidden){this.hide('');return}let s=this.step;
 if(action==='roll'){this.rollCall();return}if(action==='useHeld'){this.useItem();return}if(action==='drop'){this.drop();return}if(action==='wear'&&this.held){this.wear(this.held.id);return}if(action==='unwear'){let id=this.player.wig||this.player.glasses;let i=this.objects.get(id);if(i&&!this.player.item){this.detach(i);this.player.item=id;i.owner=this.player.id;i.state='held'}return}if(action==='returnHeld'){let id=this.player.item||this.player.wig||this.player.glasses;if(id)this.returnItem(id);return}
 if(!target)return this.toast('請靠近人物或物品');
 if(target.type==='paper'){let i=this.objects.get(target.parentId);i.papers[target.index].taken=true;this.emit('paperCollected',{id:i.id,index:target.index});if(i.papers.every(p=>p.taken)){i.papers=undefined;i.state='settled';if(!this.player.item)this.take(i.id);this.toast('三份考卷已收齊');}else this.toast('繼續拾回同一包剩餘考卷');return}
 if(target.type==='marker'){if(target.id.startsWith('return:'))this.returnItem(target.itemId);else if(this.held)this.drop(this.held.id,{x:target.x,z:target.z});return}
 if(target.type==='board')return 'missions';
 if(target.type==='npc'){let n=this.npcs.find(n=>n.id===target.id);if(n.type==='nurse'){if(this.level===0&&!this.chase.length){this.player.hp=100;this.life.p.stomach=0;this.emit('recover');return 'report'}return this.toast('先甩開追逐再來；平靜時可恢復體力')}
 if(n.type==='shop_aunt'){if(['Chase','Attack','Recover'].includes(n.state))return this.toast('阿姨忙著處理騷動，稍後再來');return 'shop'}
 if(n.type==='guard_uncle')return this.toast('警衛：失物請放這裡。家長由校門進場。');
 if(n.role==='student'){if(s?.kind==='respond')return {dialog:n.id};if(n.type==='filmer'){n.state='Film';n.film=0;this.toast('同學舉起手機：老師，妳在做什麼？');return}
 if(n.item){let i=this.objects.get(n.item);if(this.attempt?.mission==='q23'&&i.type==='laptop'){let a=this.attempt,route=a.meta.route;if(a.meta.routeIndex<route.length-1){a.meta.routeIndex++;let next=this.npcs.find(x=>x.type===route[a.meta.routeIndex]);this.detach(i);i.state='settled';this.take(i.id,next.id);this.notes.push(`${n.label}：我交給${next.label}了。`);this.toast(this.notes.at(-1));return}}
 this.detach(i);Object.assign(i,{x:n.x+.7,z:n.z,y:0,state:'settled'});if(!this.player.item)this.take(i.id);this.toast(n.label+'：老師，物品在這裡。');return}
 if(s?.kind==='gather'||s?.kind==='photo'){n.state='Gather';n.target={x:locations.stage.x+(this.npcs.indexOf(n)%3-1)*1.3,z:locations.stage.z+1.5+Math.floor(this.npcs.indexOf(n)%6/3)*1.2};n.path=[];return}this.toast(n.label+'：'+(n.type==='reader'?'老師，我在看書。':'請不要在走廊奔跑。'));return}
 if(n.role==='visitor'){if(s?.kind==='seat'){let k=this.attempt.count;n.state='Seat';n.timer=0;n.target={x:-4+k*3,z:4};n.path=[];this.toast('家長：好的，我到座位等。')}else{n.state='Gather';n.target={x:0,z:5.5};n.path=[];}return}
 if(n.type==='dean'&&this.held?.type==='folder'){n.cooldown=5;n.state='Idle';this.toast('主任開始整理資料夾');this.returnItem(this.held.id)}else this.toast(n.label+'：'+(n.type==='principal'?'我的假髮在哪裡？':'物品使用完畢，請歸位。'));return}
 if(target.type==='item'){let i=this.objects.get(target.id);if(i.type==='trophy'&&this.held?.type==='principal_wig'){let wig=this.held;this.drop(wig.id,{x:i.x,z:i.z});wig.y=.65;this.toast('假髮放在獎盃上；離開房間等校長發現。');return}let def=itemDefs[i.type];if(action==='restore'&&i.broken){i.broken=false;i.state='settled';this.emit('restore',{id:i.id,zone:zoneAt(i)});return}if(def.category.includes('fixed')){if(action==='mess'){this.notice(i.type==='piano'?'亂按鋼琴':'咖啡泡沫噴出',6,'mess:'+i.id+':'+Math.floor(this.time/4));this.emit('mess',{item:i.type,id:i.id,x:i.x,z:i.z});this.player.action=i.type==='piano'?'piano':'play';this.player.actionTime=2;}else this.useItem(i);return}if(action==='push'||def.category.includes('pushable')&&!def.category.includes('portable')){this.pushItem(i);return}if(i.full){i.full=false;i.broken=true;this.notice('垃圾桶翻倒',6,'damage:'+i.id);this.emit('spill',{id:i.id});return}if(!this.player.item)this.take(i.id);else if(this.held.id===i.id)this.drop();else this.toast('一次只能拿一件物品；R 放下');return}
 if(target.type==='hide'||target.id==='hideTool'){this.hide(target.id);return}
 if(target.type==='stage'){if(s?.kind==='choir'){this.startChoir();return}if(s?.kind==='speech'){this.player.action='teach';this.pending.push({at:this.time+5,type:'speechDone',data:{},session:this.session});this.emit('speech');return}if(s?.kind==='photo'){this.photo();return}this.rollCall();return}
 if(target.type==='prop'){let p=this.props.find(p=>p.id===target.id);if(target.id==='podium'){if(s?.kind==='answerTime')return 'timeQuestion';if(s?.kind==='invigilate'){this.emit('invigilate');return}if(s?.kind==='collect'){this.emit('collect',{id:'paper:'+this.attempt.count});return}this.teach();return}if(p?.broken){p.broken=false;p.hp=20;this.emit('restore',{id:p.id,zone:p.zone});return}if(['table','chair','bench','desk'].includes(p?.type)){let f=this.player.face;let move=this.world.move(p,f.x*1.8,f.z*1.8,.4,p.id);p.x=move.x;p.z=move.z;this.refreshColliders();this.emit('push',{id:p.id});return}this.toast('這是節奏練習。可以敲打，破損後可扶好。')}
 }
 pushItem(i:Item){if(this.meeting.running)i.hit.clear();let f=norm(i.x-this.player.x,i.z-this.player.z);let p=this.world.move(i,f.x*1.8,f.z*1.8,.4,i.id);i.x=p.x;i.z=p.z;i.state='settled';i.full=false;i.rest=this.time;this.refreshColliders();for(let n of this.npcs)if(n.hp>0&&distance(n,i)<.85&&!i.hit.has(n.id)){i.hit.add(n.id);this.damageNPC(n,6,'chair:'+i.id+(this.meeting.running?':'+(++this.seq):''))}this.emit('push',{id:i.id,item:i.type});}
 useItem(i=this.held){if(!this.meeting.running&&i&&['recorder','triangle','castanets'].includes(i.type))this.life.warn();if(this.meeting.running)return this.meeting.secondary();if(!i)return this.toast('拿起樂器、碼錶、掃把，或靠近鋼琴／咖啡機');let type=i.type;if(type==='wireless_microphone'){if(i.owner===this.player.id)return this.rollCall();return this.toast('先拿起麥克風，再使用擴音點名')}if(type==='coffee_machine'){let cup=this.objects.get('coffee_cup:0')||this.createItem('coffee_cup','coffee_cup:0',{x:i.x+1,z:i.z});if(cup.owner)return this.toast('先送回或放下上一杯');cup.state='settled';cup.broken=false;if(this.attempt&&missionDefs[this.attempt.mission].steps.some(s=>s.item==='coffee_cup')&&!cup.pins.includes(this.attempt.id))cup.pins.push(this.attempt.id);if(!this.player.item)this.take(cup.id);this.emit('coffee');this.toast('咖啡好了。杯子在咖啡機旁');return}
 if(type==='stopwatch'){this.race={checkpoint:0,started:this.time,walkStart:null};this.emit('raceStart');this.toast('四個路點：(-25,15) → (-25,21) → (-18,21) → (-18,15)，最後走到(-21,15)');return}
 if(type==='broom'){for(let ob of this.objects.values())if(ob.type==='trash_bin'&&distance(ob,this.player)<3)ob.full=false;this.emit('clean');this.toast('掃好了');return}
 if(['recorder','piano','triangle','castanets','drumstick'].includes(type)){this.player.action=type==='piano'?'piano':'play';this.player.actionTime=2;let crowd=this.npcs.filter(n=>n.hp>0&&distance(n,this.player)<6&&this.world.visible(n,this.player));for(let n of crowd){n.face=norm(this.player.x-n.x,this.player.z-n.z);if(n.role==='student'){n.state='Spectate';this.emit('audience',{npc:n.id})}}this.emit('instrument',{item:type});this.emit('performance',{item:type,zone:zoneAt(this.player),audience:crowd.length});this.notice('音樂練習的聲音',type==='piano'?3:1,'music:'+type+':'+Math.floor(this.time/2),this.player.id,6);return}this.toast('此物品可揮打、投擲、放下或歸還')}
 teach(){if(this.level>1||this.chase.some(n=>this.sees(n)))return this.toast('有人仍在追逐，無法假裝上課');this.player.action='teach';this.player.actionTime=5;this.pending.push({at:this.time+5,type:'teach',data:{zone:zoneAt(this.player)},session:this.session});this.emit('teaching');this.toast('我們正在進行跨領域教學。')}
 photo(){let crowd=this.npcs.filter(n=>distance(n,locations.stage)<6&&n.hp>0&&['Gather','Idle','Seat'].includes(n.state));let data={students:crowd.filter(n=>n.role==='student').length,visitors:crowd.filter(n=>n.role==='visitor').length,wig:!!this.player.wig,glasses:!!this.player.glasses,broom:this.held?.type==='broom',mode:this.mode,time:Math.round(this.time)};if(data.students<3||data.visitors<1)return this.toast('先點名集合三位學生與一位訪客');this.profile.photoCards.push(data);this.profile.photoCards=this.profile.photoCards.slice(-12);this.emit('photo',data);this.onSave();this.toast('合照紀念卡已儲存（程式構圖）')}
 respond(id:string,choice:number){let n=this.npcs.find(n=>n.id===id);if(!n||distance(n,this.player)>3)return;let replies=['說明事實：請一起歸還物品。','一本正經：這是跨領域節奏研究。','結束談話：我們稍後再談。'];this.toast(n.label+'：'+['了解，我來幫忙。','老師，這聽起來好奇怪。','好，我先回座位。'][choice]);if(choice===1)this.alert=Math.min(100,this.alert+2);if(choice===0)this.alert=Math.max(0,this.alert-2);n.state=choice===2?'Walk':'Idle';this.emit('respond',{npc:id,personality:n.type,choice,reply:replies[choice]})}
 shopAvailable(){let aunt=this.npcs.find(n=>n.type==='shop_aunt');return !!aunt&&aunt.hp>0&&!['Chase','Attack','Recover'].includes(aunt.state)&&distance(aunt,this.player)<4;}
 buyDrink(){if(!this.shopAvailable())return false;let free=this.attempt?.mission==='q21'&&this.profile.points<10&&!this.attempt.meta.couponUsed;if(this.player.hp<=0||(this.cooldowns.get('drink')||0)>this.time||this.profile.points<10&&!free)return false;if(!free)this.profile.points-=10;else this.attempt.meta.couponUsed=true;this.player.hp=Math.min(100,this.player.hp+30);this.cooldowns.set('drink',this.time+5);this.emit('drink');this.onSave();return true}
 buyCosmetic(id:string){if(!this.shopAvailable())return false;if(purchase(this.profile,id)){this.onSave();this.emit('purchase',{id});return true}return false}
 service(){if(!this.shopAvailable())return false;if(this.level!==0||this.chase.length||this.profile.serviceCooldown>0)return false;this.profile.points+=10;this.profile.serviceCooldown=600;this.emit('service');this.onSave();return true}
 startChoir(){if(this.choir)return;this.choir={start:this.time,beat:0,hits:0,judged:new Set(),offset:0};this.emit('choirStart');this.toast('32拍，8次指揮提示。靜音也可完成。')}
 conduct(){if(this.meeting.running)return this.meeting.secondary();if(!this.choir)return;let song=this.time-this.choir.start;let prompt=[3,7,11,15,19,23,27,31].find(b=>Math.abs(song-b*.75)<(this.profile.settings.assist?.35:.22));if(prompt!==undefined&&!this.choir.judged.has(prompt)){this.choir.judged.add(prompt);this.choir.hits++;this.player.action='conduct';this.player.actionTime=.4;this.emit('conduct',{beat:prompt});this.toast('拍子正確')}else this.toast('跟著收圈提示，再試一次')}
 tutorialEvent(e:Event){if(this.tutorial<0)return;let types=['move','take','deliverTutorial','visitMusic','dummy','throw','dodge','hide','openTasks'];if(e.type===types[this.tutorial]){this.tutorial++;if(this.tutorial>=types.length)this.finishTutorial();else this.toast(this.tutorialText())}}
 tutorialText(){return ['移動：WASD 或左下搖桿。','拿考卷：靠近辦公室考卷，E／互動。','把考卷送到教室講臺黃色圈，按 E 交付（R 也可放下）。','回到音樂教室。','到操場練習假人，J 揮打（不需攻擊人物）。','拿一件物品，Q 投擲。','K／空白鍵閃避。','到走廊工具間，互動藏入。','開今日待辦與行事曆。'][this.tutorial]||''}
 startTutorial(){this.tutorial=0;this.toast(this.tutorialText())}
 finishTutorial(){this.tutorial=-1;if(!this.profile.tutorialFlags.includes('done')){this.profile.tutorialFlags.push('done');reward(this.profile,'tutorial',20);this.onSave()}this.toast('教學完成／跳過，所有任務與活動都已開放')}
 tick(dt:number,input={x:0,z:0,run:false}){if(this.meeting.running){const start=performance.now();this.meeting.tick(dt,input);this.tickMs=performance.now()-start;return;}if(this.meeting.advanceSummons(dt))return;this.profile.meeting.campusClock+=dt;this.profile.meeting.cooldown=Math.max(0,this.profile.meeting.cooldown-dt);let begin=performance.now();this.previous.set(this.player.id,{x:this.player.x,z:this.player.z});for(let n of this.npcs)this.previous.set(n.id,{x:n.x,z:n.z});for(let i of this.objects.values())this.previous.set(i.id,{x:i.x,z:i.z});this.time+=dt;this.stats.ticks++;this.pathBudget=3;let p=this.player;for(let key of ['inv','dodgeCooldown','attackCooldown','actionTime','slow'])p[key]=Math.max(0,p[key]-dt);if(p.actionTime===0)p.action='idle';let f=norm(input.x,input.z);let mag=Math.min(1,Math.hypot(input.x,input.z));let speed=(input.run?balance.run:balance.walk)*(this.held&&itemDefs[this.held.type].heavy?.8:1)*(p.slow>0?.6:1)*this.life.speed(p);if(p.hidden)mag=0;if(p.dodge>0){p.dodge=Math.max(0,p.dodge-dt);let m=this.world.move(p,p.face.x*balance.dodge/balance.dodgeTime*dt,p.face.z*balance.dodge/balance.dodgeTime*dt);p.x=m.x;p.z=m.z;}else if(mag>.08){p.face=f;let m=this.world.move(p,f.x*speed*mag*dt,f.z*speed*mag*dt);if(zoneAt(m)==='infirmary'&&zoneAt(p)!=='infirmary'&&(this.level>1||this.chase.length)){this.toastCooldown('inf','先甩開追逐再來');}else{p.x=m.x;p.z=m.z;p.action=input.run?'run':'walk';this.movement+=speed*mag*dt;if(this.movement>1){this.movement=0;this.emit('move')}}}
 if(this.tutorial===3&&zoneAt(p)==='music_room')this.emit('visitMusic');
 if(p.attack){p.attack.age+=dt;if(p.attack.age>=.12&&!p.attack.resolved){let a=p.attack;a.resolved=true;let candidates=this.npcs.filter(n=>n.active&&n.hp>0&&distance(n,p)<a.reach+.35&&this.world.visible(p,n));let hit=0;for(let n of candidates){let f=norm(n.x-p.x,n.z-p.z);if(f.x*p.face.x+f.z*p.face.z<.6||hit>=3||a.hit.has(n.id))continue;a.hit.add(n.id);if(this.damageNPC(n,a.damage,a.id))hit++}for(let ob of this.props)if(distance(ob,p)<a.reach+.4&&this.world.visible(p,ob)){let f=norm(ob.x-p.x,ob.z-p.z);if(f.x*p.face.x+f.z*p.face.z<.5)continue;if(ob.type==='dummy'){this.emit('dummy',{item:a.item});continue}if(a.item==='drumstick'){this.emit('strikeProp',{id:ob.id,propType:ob.type,item:a.item});this.useItem()}ob.hp-=a.damage;if(ob.hp<=0&&!ob.broken){ob.broken=true;this.emit('propDamaged',{id:ob.id});this.notice('家具翻倒',6,'damage:'+ob.id)}}
 if(a.item==='badminton_racket')for(let i of this.objects.values())if(i.state==='airborne'&&['soft_parcel','basketball','chalk_eraser'].includes(i.type)&&distance(i,p)<2){i.vx=p.face.x*10;i.vz=p.face.z*10;i.owner=null;i.hit.clear();i.hits=0;i.flight='reflected:'+a.id;this.emit('reflect',{id:i.id})}}
 if(p.attack?.age>.35)p.attack=null}
 this.updateItems(dt);this.updateMicrophones();let ai=performance.now();this.dogs.tick(dt,input);this.life.tick(dt,input);this.updateNPCs(dt);this.aiMs=performance.now()-ai;this.updateSystems(dt);this.tickMs=performance.now()-begin;
 }
 toastCooldown(key:string,text:string){if((this.cooldowns.get('toast:'+key)||0)<this.time){this.cooldowns.set('toast:'+key,this.time+3);this.toast(text)}}
 updateItems(dt:number){for(let i of this.objects.values()){
 if(i.state==='held'||i.state==='worn'){let holder=i.owner===this.player.id?this.player:this.npcs.find(n=>n.id===i.owner);if(holder){i.x=holder.x;i.z=holder.z;i.y=i.state==='worn'?1.65:1.05}continue}
 if(i.state!=='airborne')continue;i.age+=dt;let next={x:i.x+(i.vx||0)*dt,z:i.z+(i.vz||0)*dt};let previous={x:i.x,z:i.z};if(!this.world.visible(previous,next)||Math.abs(next.x)>30||Math.abs(next.z)>24){i.vx=-(i.vx||0)*.25;i.vz=-(i.vz||0)*.25;}else{i.x=next.x;i.z=next.z}i.vy=(i.vy||0)-9.8*dt;i.y+=(i.vy||0)*dt;
 let enemy=i.flight?.startsWith('npc:');if(i.y<2&&i.y>-.1){if(enemy){if(distance(i,this.player)<.7&&!i.hit.has(this.player.id)){i.hit.add(this.player.id);let n=this.npcs.find(n=>i.flight.includes(n.id));if(n)this.damagePlayer(8,n)}}else if((itemDefs[i.type]?.throwDamage??5)>0)for(let n of this.npcs)if(n.active&&(n.hp>0||this.meeting.running)&&distance(i,n)<.65&&!i.hit.has(n.id)&&i.hits<(i.type==='basketball'?2:1)){i.hit.add(n.id);i.hits++;this.damageNPC(n,itemDefs[i.type]?.throwDamage??5,i.flight,true)}
 if(i.type==='basketball')for(let cone of this.objects.values())if(cone.type==='traffic_cone'&&!cone.broken&&distance(cone,i)<.8){cone.broken=true;cone.state='damaged';this.emit('coneDown',{id:cone.id,item:'basketball'},enemy?'system':this.player.id)}}
 const support=this.supportHeight(i);if(i.y<=support&&(i.vy||0)<=0){i.y=support;this.emit('land',{id:i.id,item:i.type},'system');if(i.type==='basketball'&&i.age<2.5&&Math.abs(i.vy||0)>1.5){i.vy=Math.abs(i.vy||0)*.5;i.vx*=.65;i.vz*=.65}else if(i.type==='spinning_top'&&i.age<6){i.vy=0;i.vx*=.9;i.vz*=.9;for(let n of this.npcs)if(n.active&&n.hp>0&&distance(n,i)<.7&&!i.hit.has(n.id)&&i.hits<3){i.hit.add(n.id);i.hits++;this.damageNPC(n,5,i.flight)}}else{Object.assign(i,{state:'settled',vx:0,vz:0,vy:0,rest:this.time});if(i.type==='exam_papers'){i.papers=[{x:i.x-.5,z:i.z+.3,taken:false},{x:i.x+.5,z:i.z+.3,taken:false},{x:i.x,z:i.z-.5,taken:false}];}const wasBroken=i.broken;i.broken=!i.type.startsWith('dog_')&&!['basketball','soft_parcel','wireless_microphone'].includes(i.type);if(i.broken&&!wasBroken)this.emit('itemBroken',{id:i.id},i.flight?.startsWith('npc:')?'system':this.player.id);if(i.type==='wireless_microphone')this.startBroadcast(i);this.checkDelivery(i);this.refreshColliders()}}
 if(i.age>8&&i.state==='airborne'){i.state='settled';i.y=0;i.rest=this.time;if(i.type==='wireless_microphone')this.startBroadcast(i)}
 }}
 moveNPC(n:NPC,target:Vec,dt:number,speed:number){speed*=this.life.speed(n);target=this.life.navigation(n,target);const approach=this.world.approach(target,n);if(n.target===target)n.target=approach;target=approach;if(distance(n,target)<.2)return;if(n.repath<=0&&this.pathBudget>0){n.path=this.world.path(n,target);n.repath=.5+this.rng.next()*.15;this.pathBudget--}let next=n.path[0]||target;if(distance(n,next)<.3){n.path.shift();next=n.path[0]||target}let f=norm(next.x-n.x,next.z-n.z);n.face=f;let p=this.world.move(n,f.x*speed*dt,f.z*speed*dt,.32);n.x=p.x;n.z=p.z;}
 updateNPCs(dt:number){let low=this.profile.settings.quality==='low';let budget=(low?16:20)-this.dogs.visible.filter(d=>d.active).length,studentMax=low?10:12;let priority=(n:NPC)=>n.role==='parent'?0:['Chase','Attack','Search','SoundInvestigate','CallTurn','Gather','Seat','Call','ScienceWalk','ScienceFeed','ScienceHit'].includes(n.state)?1:2;let sorted=[...this.npcs].sort((a,b)=>priority(a)-priority(b)||distance(a,this.player)-distance(b,this.player));let count=0,sc=0;for(let n of sorted){let forced=n.role==='parent'||['Chase','Search','Attack','SoundInvestigate','CallTurn','Gather','Seat','ScienceWalk','ScienceFeed','ScienceHit'].includes(n.state);n.active=(forced||distance(n,this.player)<24)&&count<budget&&(n.role!=='student'||sc<studentMax);if(n.active){count++;if(n.role==='student')sc++}}
 let chasingTeachers=0;for(let n of this.npcs){n.cooldown=Math.max(0,n.cooldown-dt);n.repath-=dt;n.contactCooldown=Math.max(0,n.contactCooldown);if(n.state==='Recover'){n.timer-=dt;if(n.timer<=0){n.hp=n.maxHp;n.cooldown=2;n.state=n.role==='parent'?'Leave':'Idle';n.called=n.called||n.role==='parent';this.emit('npcRecovered',{id:n.id},n.id)}continue}if(!n.active)continue;if(this.life.owns(n)||n.state==='LifePatrol')continue;if((n as any).dogControl?.remaining>0){n.attack=null;continue;}n.timer+=dt;if(n.role==='staff'&&['Chase','Attack'].includes(n.state)){if(chasingTeachers++>=2){n.state='Investigate';n.target={...n.lastSeen}}}
 const visible=this.sees(n);if(n.soundInvestigation){if(n.state!=='SoundInvestigate')this.finishSoundInvestigation(n);else if(n.soundInvestigation.resumeState==='Search'&&visible){this.finishSoundInvestigation(n);n.state='Chase';n.timer=0;}}if(n.role==='parent'||['Chase','Attack','Search'].includes(n.state)){if(visible){n.lastSeen={x:this.player.x,z:this.player.z};n.lost=0;if(n.state==='Search')n.state='Chase'}else{n.lost+=dt;if(n.lost>2&&['Chase','Attack'].includes(n.state)){n.state='Search';n.timer=0;n.target={...n.lastSeen};this.emit('search',{npc:n.id},n.id);if(this.attempt)this.attempt.meta.searchSeen=true}}}
 if(n.role==='staff'&&['principal','dean','guard_uncle'].includes(n.type)&&n.hp>0&&Math.floor(this.time*2)!==Math.floor((this.time-dt)*2)){let missing=[...this.objects.values()].find(i=>['laptop','principal_wig','principal_glasses','wall_clock'].includes(i.type)&&distance(n,i.home)<7&&distance(i,i.home)>2&&this.time-(this.cooldowns.get('missing:'+i.id)||-100)>20);if(missing){this.cooldowns.set('missing:'+missing.id,this.time);this.alert=Math.min(100,this.alert+6);this.reason='物品缺失被發現';n.state='Investigate';n.target={x:missing.x,z:missing.z};this.emit('missingFound',{id:missing.id},n.id);}}
 if(n.type==='principal'&&this.player.wig&&visible&&n.intro===0){n.intro=2;n.cooldown=2;n.state='Surprise';n.timer=0;this.toast('校長：這個髮型……有點眼熟。')}
 if(n.state==='Surprise'){if(n.timer>2){n.state='Chase';n.timer=0}continue}
 this.considerBroadcast(n);
 switch(n.state){
 case 'ScienceHit':if(n.timer>=.35){n.state='Chase';n.timer=0;}break;
 case 'Idle':if(n.timer>4+n.turns){n.state='Walk';n.timer=0;n.target={x:n.home.x+(this.rng.next()-.5)*4,z:n.home.z+(this.rng.next()-.5)*4}}break;
 case 'Walk':this.moveNPC(n,n.target,dt,1.2);if(distance(n,n.target)<.4){n.state='Idle';n.timer=0}break;
 case 'SoundInvestigate':{
 const investigation=n.soundInvestigation;
 if(!investigation||!this.broadcasts.has(investigation.itemId)){this.finishSoundInvestigation(n);break}
 if(distance(n,n.target)<.8)break;
 if(n.repath<=0&&this.pathBudget>0){this.pathBudget--;const path=this.world.path(n,n.target);if(!path.length||this.world.blocked(n.target,.32)){this.finishSoundInvestigation(n);break}n.path=path;n.repath=.6;}
 // Only follow validated waypoints; never fall back to a direct route through walls.
 if(!n.path.length){if(n.repath>0)n.repath=0;break}
 const next=n.path[0];if(distance(n,next)<.3){n.path.shift();break}
 const f=norm(next.x-n.x,next.z-n.z);n.face=f;const moved=this.world.move(n,f.x*2*dt,f.z*2*dt,.32);n.x=moved.x;n.z=moved.z;
 investigation.stuck=distance(n,investigation.last)<.005?investigation.stuck+dt:0;investigation.last={x:n.x,z:n.z};
 if(investigation.stuck>.6)this.finishSoundInvestigation(n);break;
 }
 case 'CallTurn':if(n.timer>=microphoneRules.turnSeconds){n.state='Gather';n.timer=0}break;
 case 'Investigate':this.moveNPC(n,n.target,dt,1.8);if(distance(n,n.target)<1&&n.timer>3){n.state=this.level>=2&&visible?'Chase':'Idle';n.timer=0}break;
 case 'Flee':{let f=norm(n.x-this.player.x,n.z-this.player.z);let target={x:Math.max(-29,Math.min(29,n.x+f.x*4)),z:Math.max(-23,Math.min(23,n.z+f.z*4))};if(distance(n,this.player)<5)this.moveNPC(n,target,dt,3.4);else if(n.callEligible&&!n.called&&this.time>=n.contactCooldown){n.state='Call';n.timer=0;}else if(n.timer>6){n.state='Idle';n.timer=0}break}
 case 'Call':if(n.hp>0&&n.timer>=2&&distance(n,this.player)>2){n.called=true;n.contactCooldown=this.time+90;this.queueParent(n.incident);this.emit('contactComplete',{npc:n.id,incident:n.incident},n.id);n.state='Flee';n.timer=0}break;
 case 'Tattle':this.moveNPC(n,n.target,dt,3);if(distance(n,n.target)<2){if((this.cooldowns.get('tattle:'+n.id)||0)<this.time){this.alert=Math.min(100,this.alert+8);this.cooldowns.set('tattle:'+n.id,this.time+30);this.emit('tattleComplete',{npc:n.id},n.id);}let dean=this.npcs.find(n=>n.type==='dean');dean.state='Chase';dean.lastSeen={...this.player};n.state='Idle';n.timer=0}break;
 case 'Film':n.face=norm(this.player.x-n.x,this.player.z-n.z);if(visible){n.film+=dt;if(n.film>=3){this.notice('學生拍攝完成',6,'film:'+n.id);n.state='Spectate';n.film=0}}else{if(n.film>0&&this.time-n.lastFilmEscape>=5){this.emit('filmEscape',{npc:n.id},n.id);n.lastFilmEscape=this.time;}n.state='Idle';n.film=0}break;
 case 'Spectate':case 'Mediate':{let d=distance(n,this.player);if(d<3){let f=norm(n.x-this.player.x,n.z-this.player.z);this.moveNPC(n,{x:n.x+f.x*2,z:n.z+f.z*2},dt,2)}else if(d>5&&d<10)this.moveNPC(n,this.player,dt,1.5);n.face=norm(this.player.x-n.x,this.player.z-n.z);if(n.timer>12){n.state='Idle';n.timer=0}break}
 case 'Help':{let down=this.npcs.find(x=>x.role==='student'&&x.hp===0&&distance(x,n)<5);if(down){this.moveNPC(n,down,dt,2);if(distance(n,down)<1)down.timer=Math.max(0,down.timer-dt)}else if(n.timer>2)n.state='Chase';break}
 case 'PickUp':{let item=[...this.objects.values()].filter(i=>!i.owner&&['settled','home'].includes(i.state)&&itemDefs[i.type].category.includes('portable')&&!i.pins.length&&distance(i,n)<5).sort((a,b)=>distance(a,n)-distance(b,n))[0];if(item){this.moveNPC(n,item,dt,2);if(distance(n,item)<(item.y>0?2:.7)&&this.world.visible(n,item)&&this.take(item.id,n.id)){n.state='ReturnItem';n.target={...item.home}}}else n.state='Idle';break}
 case 'ReturnItem':if(n.item){let i=this.objects.get(n.item);this.moveNPC(n,i.home,dt,2);if(distance(n,i.home)<1.8&&this.world.visible(n,i.home)){this.detach(i);Object.assign(i,{...i.home,state:'home',y:i.homeY||0,angle:i.homeAngle||0});n.state='Idle'}}else n.state='Idle';break;
 case 'Prank':if(n.timer>1){let prop=this.props.find(p=>!p.broken&&distance(p,n)<3);if(prop){prop.broken=true;this.emit('propDamaged',{id:prop.id},n.id)}n.state='Idle';n.timer=-25}break;
 case 'Gather':case 'Seat':this.moveNPC(n,n.target,dt,2);if(distance(n,n.target)<.5){if(n.state==='Seat')this.emit('seat',{id:n.id});n.state='Idle';n.timer=-30;}break;
 case 'Gate':if(n.timer>6)n.state='Idle';break;
 case 'Guard':this.moveNPC(n,n.home,dt,2.6);if(distance(n,n.home)<1.5){if(distance(n,this.player)<8&&visible)n.state='Chase';else if(n.timer>10)n.state='Leave'}break;
 case 'Cover':n.face=norm(this.player.x-n.x,this.player.z-n.z);if(n.timer>.9)n.state='Chase';break;
 case 'Clean':if(n.timer>3){n.state='Search';n.lost=3;n.target={...n.lastSeen};n.timer=0;this.emit('search',{npc:n.id},n.id)}break;
 case 'Search':this.moveNPC(n,n.target,dt,2);if(this.player.hidden&&this.player.hideWitness&&distance(n,this.player)<1.5){this.player.hidden=false;this.toast('藏點被看見了！');n.state='Chase'}if(n.timer>10){n.state=n.role==='parent'?'Leave':'Walk';n.target={...n.home};n.timer=0;this.emit('escape',{level:this.level},'system')}break;
 case 'Enter':this.moveNPC(n,n.lastSeen,dt,parentDefs[n.type]?.speed||3);if(distance(n,n.lastSeen)<4){n.state='Chase';n.lost=0;n.timer=0}break;
 case 'Leave':this.moveNPC(n,{x:0,z:24},dt,2.6);if(distance(n,{x:0,z:24})<1){this.releaseNPC(n);this.npcs=this.npcs.filter(x=>x!==n)}break;
 case 'Chase':{
 if(n.cooldown>0)break;if(n.type==='duo'){let partner=this.npcs.find(x=>x!==n&&x.group===n.group&&x.hp>0);if(partner&&distance(n,partner)<4&&Math.floor(this.time/2)%2===n.turns%2){n.state='Cover';n.timer=0;break}}if(n.type==='camper'&&distance(n,n.home)>8){n.lastSeen={...n.home};n.state='Search';n.timer=0;break}if(n.type==='protective'&&distance(n,n.home)>8){n.state='Guard';n.timer=0;break}if(n.type==='shop_aunt'&&distance(n,n.home)>9){n.state='Walk';n.target={...n.home};break}
 if(n.type==='neat'){let litter=[...this.objects.values()].find(i=>['exam_papers','trash_bin'].includes(i.type)&&['settled','damaged'].includes(i.state)&&distance(i,n)<5&&!n.cleaned.has(i.id));if(litter){n.cleaned.add(litter.id);n.state='Clean';n.timer=0;if(this.attempt)this.attempt.meta.cleanSeen=true;this.emit('cleanParent',{id:n.id},n.id);break}}
 if(n.type==='yoga'&&this.player.attack&&n.turns<2){let f=this.player.face,m=this.world.move(n,f.z*1.2,-f.x*1.2);n.x=m.x;n.z=m.z;n.turns++;n.cooldown=.5;break}
 let reach=['sports','pe_teacher'].includes(n.type)?4:['gardener','nagging','photographer','drama'].includes(n.type)?3:['shopping_bag','courier'].includes(n.type)?7:1.5;let d=distance(n,this.player);
 if(d<reach&&visible){n.state='Attack';n.timer=0;n.face=norm(this.player.x-n.x,this.player.z-n.z);n.attack={age:0,fired:false,origin:{x:this.player.x,z:this.player.z}};this.emit('windup',{npc:n.id,ability:n.ability},n.id)}else{let speed=n.role==='student'?(n.type==='athlete'?4:3):parentDefs[n.type]?.speed||3;if(this.npcs.some(x=>x.type==='whistle'&&x.state==='Chase'&&distance(x,n)<5))speed*=1.15;let target=visible?this.player:n.lastSeen;if(n.type==='runner'&&d<6)target={x:this.player.x+Math.sin(n.timer*2)*2,z:this.player.z+Math.cos(n.timer*2)*2};this.moveNPC(n,target,dt,speed)}break;}
 case 'Attack':{let a=n.attack;if(!a){n.state='Chase';break}a.age+=dt;let delay=n.type==='drama'?1.8:['armored','gardener','shopping_bag','courier','photographer','nagging'].includes(n.type)?.9:.55;
 if(a.age>=delay&&!a.fired){a.fired=true;let d=distance(n,this.player);if(['shopping_bag','courier'].includes(n.type))this.npcProjectile(n,n.type==='courier'?'cardboard_box':'soft_parcel');else if(n.type==='sports'||n.type==='pe_teacher'){let f=norm(a.origin.x-n.x,a.origin.z-n.z);let m=this.world.move(n,f.x*3,f.z*3);n.x=m.x;n.z=m.z;if(distance(n,this.player)<1.2)this.damagePlayer(10,n)}else if(d<(['gardener','nagging','photographer','drama'].includes(n.type)?3:1.8)&&this.world.visible(n,this.player)){this.damagePlayer(n.type==='armored'||n.type==='drama'?18:n.type==='spatula'?12:8,n);if(n.type==='nagging')this.player.slow=1;if(n.type==='photographer')this.player.slow=.3}}
 if(n.type==='spatula'&&a.age>.8&&a.age<1.4){let beat=Math.floor(a.age/.3);if(a.combo!==beat){a.combo=beat;if(distance(n,this.player)<1.7)this.damagePlayer(6,n)}}
 if(a.age>delay+(n.type==='spatula'?1.2:.65)){n.state='Chase';n.attack=null;n.cooldown=['armored','drama','yoga','courier'].includes(n.type)?2:1;n.turns=0}break}
 }
 }
 }
 releaseNPC(n:NPC){this.finishSoundInvestigation(n);for(const key of this.cooldowns.keys())if(key.startsWith('mic:'+n.id+':'))this.cooldowns.delete(key);this.previous.delete(n.id);if(n.item){let i=this.objects.get(n.item);this.detach(i);Object.assign(i,{x:n.x,z:n.z,y:0,state:'settled'})}}
 npcProjectile(n:NPC,type:string){if([...this.objects.values()].filter(i=>i.state==='airborne').length>=6)return;let pool=Array.from({length:6},(_,k)=>`npc-projectile:${type}:${k}`);let id=pool.find(id=>{let item=this.objects.get(id);return !item||!item.owner&&!item.pins.length&&item.state!=='airborne'});if(!id)return;let i=this.objects.get(id)||this.createItem(type,id,n);let f=norm(this.player.x-n.x,this.player.z-n.z);Object.assign(i,{x:n.x+f.x*.7,z:n.z+f.z*.7,y:1.2,state:'airborne',vx:f.x*7,vz:f.z*7,vy:2,age:0,flight:'npc:'+n.id+':'+(++this.seq),hits:0});i.hit.clear();this.emit('projectile',{id},n.id)}
 updateSystems(dt:number){for(let entry of [...this.pending])if(entry.at<=this.time){this.pending=this.pending.filter(x=>x!==entry);if(entry.session===this.session)this.emit(entry.type,entry.data,entry.type==='teach'?this.player.id:'system')}
 for(let queue of [...this.familyQueue])if(queue.at<=this.time&&this.parentCount()+parentDefs[queue.type].slotCost<=3){this.spawnParent(queue.type);this.familyQueue=this.familyQueue.filter(x=>x!==queue)}
 let seen=this.npcs.some(n=>n.active&&['Chase','Attack','Film'].includes(n.state)&&this.sees(n));if(this.time-this.lastTrouble>8&&!seen){let old=this.level,oldScore=this.alert;this.alert=Math.max(0,this.alert-dt*(this.player.action==='teach'&&this.level<=1?3:2));if(old!==this.level){this.emit('alertFall',{level:this.level},'system');if(this.attempt&&this.attempt.meta.maxParents>=2)this.emit('escape',{level:this.level},'system')}if(this.alert===0&&oldScore>0){this.emit('naturalCalm',{},'system');for(let n of this.npcs.filter(n=>n.role==='student')){n.incident='';n.called=false;n.retries=0;n.callEligible=false;}}}
 this.profile.serviceCooldown=Math.max(0,this.profile.serviceCooldown-dt);
 const a=this.attempt,s=this.step;if(a){let count=this.npcs.filter(n=>n.role==='parent'&&['Chase','Attack'].includes(n.state)).length;a.meta.maxParents=Math.max(a.meta.maxParents,count);a.meta.peakLevel=Math.max(a.meta.peakLevel||0,this.level);
 if(s.kind==='wearVisit'){let id=this.player.wig||this.player.glasses;let i=this.objects.get(id);if(i?.type===s.item&&zoneAt(this.player)===s.zone)this.emit('wearVisit',{item:i.type,zone:s.zone})}
 if(s.kind==='place'){let placed=0;let ids=[];for(let k=0;k<(s.count||1);k++){let target=destination(s,k);let i=s.item==='scene_table'?this.props.find(p=>p.type==='table'&&distance(p,target)<1.3):[...this.objects.values()].find(i=>i.type===s.item&&i.pins.includes(a.id)&&!i.owner&&!ids.includes(i.id)&&distance(i,target)<1.3);if(i){placed++;ids.push(i.id)}}if(placed>=(s.count||1)){a.meta.placeTime=(a.meta.placeTime||0)+dt;if(a.meta.placeTime>=2){a.count=(s.count||1);this.advance()}}else a.meta.placeTime=0}
 if(s.kind==='wigTrophy'){let wig=[...this.objects.values()].find(i=>i.type==='principal_wig'),trophy=[...this.objects.values()].find(i=>i.type==='trophy');if(wig&&!wig.owner&&distance(wig,trophy)<1.4&&zoneAt(this.player)!=='principal_room'){a.meta.wigTime=(a.meta.wigTime||0)+dt;if(a.meta.wigTime>2)this.emit('wigFound',{},'system')}}
 if(s.kind==='gather'){let members=this.npcs.filter(n=>n.role==='student'&&n.hp>0&&distance(n,locations.stage)<5&&a.meta.choristers?.includes(n.id));if(members.length>=6)this.emit('gathered',{count:members.length},'system')}
 }
 if(this.race){let checkpoints=[{x:-25,z:15},{x:-25,z:21},{x:-18,z:21},{x:-18,z:15}],r=this.race;if(r.checkpoint<4&&distance(this.player,checkpoints[r.checkpoint])<1.1){r.checkpoint++;this.toast('路點 '+r.checkpoint+'/4')}else if(r.checkpoint===4){if(this.player.action==='run')r.walkStart=null;else if(!r.walkStart)r.walkStart={...this.player};if(distance(this.player,{x:-21,z:15})<.9&&r.walkStart&&distance(r.walkStart,this.player)>2){this.race=null;this.emit('raceDone')}}}
 if(this.choir){let song=this.time-this.choir.start;this.choir.beat=Math.min(32,Math.floor(song/.75));if(song>=24){let hits=this.choir.hits;this.choir=null;this.emit('choirDone',{hits},'system');this.toast(`曲段完成，命中 ${hits}/8。失誤不阻止通關。`)}}
 if(this.player.wig&&zoneAt(this.player)==='principal_room'){let principal=this.npcs.find(n=>n.type==='principal');if(principal&&this.sees(principal))this.toastCooldown('wig','校長：我的髮型怎麼在老師頭上？')}
 // Zone restoration requires quiet, elapsed time, distance, invisibility, no held / worn / pinned entity.
 for(let z of ['classroom','music_room','staff_room','principal_room','courtyard','playground','gate','co_op','infirmary','corridor']){if(zoneAt(this.player)===z)this.zoneAway.delete(z);else if(!this.zoneAway.has(z))this.zoneAway.set(z,this.time);}
 for(let i of this.objects.values())if(['settled','damaged'].includes(i.state)&&!i.pins.length&&this.time-i.rest>45&&this.time-(this.zoneAway.get(i.zone)??this.time)>45&&distance(i,this.player)>24&&!this.cameraVisible(i)&&!this.chase.length&&this.level===0){this.stopBroadcast(i.id);i.microphoneThrow=undefined;Object.assign(i,{...i.home,state:'home',y:i.homeY||0,angle:i.homeAngle||0,broken:false,papers:undefined});this.refreshColliders();}
 for(let p of this.props)if(p.broken&&p.home&&!p.pins&&this.time-(this.zoneAway.get(p.zone)??this.time)>45&&distance(p,this.player)>24&&!this.cameraVisible(p)&&!this.chase.length&&this.level===0){Object.assign(p,p.home,{broken:false,hp:20});this.refreshColliders();}
 if(Math.floor(this.time/30)!==Math.floor((this.time-dt)/30))this.onSave();
 }
 assertOwnership(){let refs=[this.player.item,this.player.wig,this.player.glasses,...this.npcs.map(n=>n.item)].filter(Boolean);if(new Set(refs).size!==refs.length)throw Error('重複物件持有');for(let i of this.objects.values()){let owned=['held','worn'].includes(i.state);if(owned!==!!i.owner||owned&&!refs.includes(i.id))throw Error('物件狀態不一致 '+i.id)}return true}
}
