import type {Game,NPC,Item,Event} from './game';
import {lifeKinds,lifeNames,lifeAwards,lifeRules,LifeKind} from './life-data';
import {Vec,zoneAt} from './data';
import {distance,norm} from './world';
type Case={id:string,kind:LifeKind,seed:number,state:string,age:number,actors:string[],items:string[],points:Vec[],stage:number,stageTime:number,reported:boolean,recoveryHit:boolean,thief?:string,owner?:string,parent?:string,originalBroom?:string,swings:number,breakAt:number,warning:number,stuck:Record<string,number>,responses:number[],hostileParent:boolean};
export type Puddle=Vec&{id:string,age:number};
export class Life{
 cases:Case[]=[];puddles:Puddle[]=[];fragments:(Vec&{age:number})[]=[];alerts=new Map<string,number>();job:null|{kind:'eat'|'clean',id:string,time:number,start:Vec,hp:number}=null;caption='';captionUntil=0;queue:string[]=[];normalPatrol=0;normalPatrolWait=0;resetting=false;
 constructor(public g:Game){}
 get p(){return this.g.profile.life}get phase(){const t=this.p.clock%360;return t<60?'升旗':t<240?'自由活動':t<330?'午餐':'放學'}get flagRemaining(){return this.phase==='升旗'?60-this.p.clock%360:0}
 get alert(){return [...this.alerts.values()].reduce((a,b)=>a+b,0)}
 log(c:Case|null,reason:string,actor='system',target?:string,item?:string,kindOverride?:LifeKind){const location=this.g.npcs.find(n=>n.id===actor)||this.g.objects.get(item||'')||this.g.player;const row={incidentId:c?.id||(kindOverride==='milk'?item?.split(':spill:')[0]||'milk-cleanup':'meal:'+this.p.mealSerial),eventType:c?.kind||kindOverride||'lunch',sourceActorId:actor,targetActorId:target||null,itemInstanceId:item||null,zoneId:zoneAt(location),gameTime:this.p.clock,resolutionReason:reason};this.p.ledger.push(row);this.p.ledger=this.p.ledger.slice(-100);this.g.emit('lifeEvent',row,actor,target,item);return row}
 say(s:string){s=s.slice(0,28);if(this.captionUntil>this.p.clock){if(this.queue.length<4&&!this.queue.includes(s))this.queue.push(s);return}this.caption=s;this.captionUntil=this.p.clock+3;this.g.toast(s.replace(/：/g,' · '))}
 award(index:number){const id=lifeAwards[index];if(this.p.achievements.includes(id))return;this.p.achievements.push(id);this.say('生活紀念：'+id);this.g.onSave()}
 sync(){this.p.active=this.cases.map(c=>({alertContribution:this.alerts.get(c.id)||0,id:c.id,kind:c.kind,seed:c.seed,state:c.state,actors:[...c.actors],items:[...c.items],itemStates:c.items.map(id=>{const i=this.g.objects.get(id);return i?{id:i.id,owner:i.owner,state:i.state,x:i.x,z:i.z}:null}),originalBroom:c.originalBroom,age:c.age,stage:c.stage,thief:c.thief,owner:c.owner,responses:c.responses,reported:c.reported,recoveryHit:c.recoveryHit}));}
 reset(){const interrupted=this.p.active.length&&!this.cases.length;this.resetting=true;for(const c of [...this.cases])this.finish(c,false,'場景切換');this.resetting=false;this.cases=[];this.alerts.clear();this.job=null;this.puddles=[];this.fragments=[];this.queue=[];this.caption='';this.captionUntil=0;this.p.stomach=0;if(interrupted){for(const c of this.p.active)this.p.cooldowns[c.kind as LifeKind]=this.p.clock+(['theft','patrol','assembly'].includes(c.kind)?180:120);this.log(null,'讀檔：臨時事件安全結束，不授予紀念');}this.p.active=[];this.g.createItem('lunch_cart','life:lunch_cart',{x:-26.5,z:-19.4});this.g.createItem('mop','life:mop',{x:-10,z:-8.8});this.p.nextMain=Math.max(this.p.nextMain,this.p.clock+30);this.p.nextSide=Math.max(this.p.nextSide,this.p.clock+60);this.g.refreshColliders()}
 recover(){for(const i of [...this.g.objects.values()])if(/^life:\d+:/.test(i.id))this.g.removeItem(i.id);if(this.p.active.length){this.log(null,'讀檔：臨時事件安全結束，不授予紀念');this.p.active=[];}this.puddles=[];this.job=null;/* Meals retain their reserved result and playable-time cooldown. */}
 reserved(n:NPC){return this.cases.some(c=>c.actors.includes(n.id))}
 owns(n:NPC){return this.reserved(n)&&n.state.startsWith('Life')}
 available(n:NPC){return n.hp>0&&['Idle','Walk','LifePatrol'].includes(n.state)&&!n.item&&!n.soundInvestigation&&!n.incident&&!this.reserved(n)&&!this.g.attempt?.meta.choristers?.includes(n.id)&&!this.g.choir}
 next(seed:number){return (Math.imul(seed,1664525)+1013904223)>>>0}
 start(kind:LifeKind,seed=Math.floor(this.g.rng.next()*4294967296),options:{thief?:string}={}){
  if(kind==='lunch')return this.eat();if(this.g.meeting.running||!lifeKinds.includes(kind))return null;
  const main=['theft','patrol','assembly'].includes(kind),sides=this.cases.filter(c=>!['theft','patrol','assembly'].includes(c.kind));
  if(main&&this.cases.some(c=>['theft','patrol','assembly'].includes(c.kind))||!main&&sides.length>=2)return null;
  if(kind==='assembly'&&this.flagRemaining<25)return null;if(kind==='milk'&&this.puddles.length>=3)return null;
  if(kind==='theft'&&(this.g.parentCount()+this.g.familyQueue.length>=3))return null;
  const free=this.g.npcs.filter(n=>n.role==='student'&&this.available(n));const used=this.cases.flatMap(c=>c.actors).filter(id=>id.startsWith('student:')).length;
  const count=kind==='assembly'?3+1+seed%2:2;
  if(free.length<count||used+count>5)return null;
  let selected=free.slice().sort((a,b)=>((+a.id.split(':')[1]+seed)%37)-((+b.id.split(':')[1]+seed)%37)).slice(0,count);
  if(kind==='assembly'){const assembly=free.slice().sort((a,b)=>distance(a,{x:0,z:5})-distance(b,{x:0,z:5})).slice(0,3);const absent=free.filter(n=>!assembly.includes(n)).sort((a,b)=>distance(a,{x:-21,z:-18})-distance(b,{x:-21,z:-18})).slice(0,count-3);selected=[...assembly,...absent];}
  if(kind==='theft'){const thief=options.thief?free.find(n=>n.id===options.thief):undefined;const owner=thief?free.find(n=>n.friend===thief.id):free.find(n=>free.some(f=>f.id===n.friend));if(!owner)return null;const t=thief||free.find(n=>n.id===owner.friend);if(!t)return null;selected=[owner,t];}
  const teacher=this.g.npcs.find(n=>n.type==='patrol_teacher');if(['patrol','assembly'].includes(kind)&&(!teacher||!this.available(teacher)))return null;
  const gathering=kind==='patrol'?(seed%2?{x:9,z:-18}:{x:-8,z:-18}):kind==='baseball'?{x:-18,z:14}:kind==='milk'?{x:-17,z:-18}:{x:-18,z:-19};
  const points=selected.map((n,i)=>this.g.world.approach({x:gathering.x+(i%3)*1.1,z:gathering.z+Math.floor(i/3)*1.3},n));
  if(kind==='assembly'){for(let i=0;i<3;i++)points[i]=this.g.world.approach({x:-3+i*1.6,z:5});points[3]=this.g.world.approach({x:-22,z:-18});if(count===5)points[4]=this.g.world.approach({x:-19,z:-18});}
  if(points.some((p,i)=>this.g.world.blocked(p,.32)||!this.g.world.path(selected[i],p).length))return null;
  const c:Case={id:'life:'+ ++this.p.serial,kind,seed,state:'Scheduled',age:0,actors:selected.map(n=>n.id),items:[],points,stage:0,stageTime:0,reported:false,recoveryHit:false,swings:0,breakAt:3+seed%3,warning:0,stuck:{},responses:selected.map((_,i)=>(seed+i)%5),hostileParent:false};
  if(kind==='patrol'||kind==='assembly')c.actors.push(teacher!.id);
  if(kind==='theft'){c.owner=selected[0].id;c.thief=selected[1].id;const parent=this.g.addNPC('neat','parent',{x:0,z:24},c.id+':parent');parent.state='LifeQuestion';parent.called=true;parent.callEligible=false;c.parent=parent.id;c.actors.push(parent.id);this.alerts.set(c.id,8);const i=this.g.createItem('event_spinning_top',c.id+':top',points[0]);c.items.push(i.id);i.pins.push(c.id);}
  if(kind==='milk')c.items.push(this.g.createItem('milk_carton',c.id+':milk',points[0]).id);
  if(kind==='baseball'){c.items.push(this.g.createItem('orange',c.id+':orange',points[0]).id);const broom=[...this.g.objects.values()].find(i=>i.type==='broom'&&!i.owner&&!i.broken&&!i.pins.length&&['home','settled'].includes(i.state));if(broom){c.originalBroom=broom.id;c.items.push(broom.id);broom.pins.push(c.id);}else c.items.push(this.g.createItem('broom',c.id+':broom',points[1]).id);}
  for(const n of selected){n.state='LifeWalk';n.path=[];n.repath=0;n.timer=0;}
  c.state='Preparing';this.cases.push(c);this.log(c,'預約完成');if(main)this.say(kind==='theft'?'同學：朋友借走了我的陀螺':kind==='assembly'?'集合有空位，校安老師準備找人':'角落有小煙霧，可以告知校安老師');this.sync();this.g.onSave();return c;
 }
 move(n:NPC,p:Vec,dt:number,c?:Case){if(distance(n,p)<.65){if(c)c.stuck[n.id]=0;return true;}const before={x:n.x,z:n.z};this.g.moveNPC(n,p,dt,n.state==='LifeEscort'?4.6:2.6);if(c){c.stuck[n.id]=distance(before,n)<.005?(c.stuck[n.id]||0)+dt:0;if(c.stuck[n.id]>5)this.finish(c,false,'路線中斷');}return distance(n,p)<.65}
 takeFor(c:Case,i:Item,n:NPC){this.g.detach(i);i.state='held';i.owner=n.id;n.item=i.id;i.flight=undefined;i.pins=[...new Set([...i.pins,c.id])];}
 finish(c:Case,success:boolean,reason:string){if(!this.cases.includes(c))return;c.state='Resolving';this.log(c,reason);this.alerts.delete(c.id);
  for(const id of c.items){const i=this.g.objects.get(id);if(!i)continue;i.pins=i.pins.filter(p=>p!==c.id);if(id===c.originalBroom){i.broken=false;if(i.owner===this.g.player.id)continue;this.g.detach(i);Object.assign(i,i.home,{y:i.homeY||0,state:'home',broken:false,flight:undefined});}else if(i.owner===this.g.player.id&&c.kind==='baseball'&&!this.resetting){i.pins=[];(i as any).lifeRetiredAt=this.p.clock;/* A picked orange/broom becomes an ordinary item; it is never cloned. */}else{if(i.owner===this.g.player.id)this.say('事件物品已交回；手中其他物品保留');this.g.removeItem(id);}}
  for(const id of c.actors){const n=this.g.npcs.find(n=>n.id===id);if(!n)continue;if(n.state.startsWith('Life')){n.state=n.role==='parent'?'Leave':'Idle';n.timer=0;n.path=[];n.repath=0;}if(n.id===c.parent&&!c.hostileParent&&n.hp>0){n.state='Leave';n.path=[];} }
  c.state=success?'Completed':'Cancelled';this.cases=this.cases.filter(e=>e!==c);this.p.cooldowns[c.kind]=this.p.clock+(['theft','patrol','assembly'].includes(c.kind)?180:120);if(['theft','patrol','assembly'].includes(c.kind))this.p.nextMain=this.p.clock+30;this.p.recent=[c.kind,...this.p.recent].slice(0,3);this.sync();this.g.refreshColliders();this.g.onSave();
 }
 hit(n:NPC,sourceActor=this.g.player.id){let first=false;for(const c of [...this.cases]){if(!c.actors.includes(n.id))continue;if(c.kind==='theft'){if(n.id===c.parent&&sourceActor===this.g.player.id)c.hostileParent=true;const i=this.g.objects.get(c.items[0]);if(n.id===c.thief&&i?.owner===n.id){this.g.detach(i);Object.assign(i,{x:n.x,z:n.z,y:0,state:'settled',flight:undefined});first=!c.recoveryHit;c.recoveryHit=true;n.callEligible=false;n.called=true;this.say('陀螺掉出來了！請交還失主');this.log(c,'recoveryHit',sourceActor,n.id,i.id);this.sync();}else this.log(c,'普通受擊',sourceActor,n.id);}else{this.say('生活事件中斷；先處理受擊');this.finish(c,false,'人物受擊');}}return first;}
 capture(e:Event){if(this.g.meeting.running)return;if(e.type==='take'){for(const c of [...this.cases])if(c.kind==='baseball'&&c.items.includes(e.data.id)){this.say('棒球練習收工；沒有替代球棒');this.finish(c,false,'玩家取走道具');}}
  if(e.type==='use'&&['recorder','triangle','castanets'].includes(e.data.item))this.warn();
  if(e.type==='recover')this.p.stomach=0;if(e.type==='playerHit')this.job=null;
 }
 warn(){for(const c of this.cases)if(['patrol','assembly'].includes(c.kind)&&c.stage===1&&c.warning<=0&&c.points.some(p=>distance(p,this.g.player)<5)){c.warning=10;c.stageTime=Math.max(c.stageTime,-3);(c as any).hiddenUntil=c.age+3;this.say('學生藏起小物：是老師來了嗎？');this.log(c,'樂器造成短暫誤警報',this.g.player.id);}}
 targets(){if(this.g.meeting.running)return [];const out:any[]=[{id:'life:eat',type:'life',label:this.phase==='午餐'?'吃營養午餐（E）':'吃午餐 · 餐車仍開放',x:-25.4,z:-19.4}];if(this.g.held?.type==='mop')for(const p of this.puddles)out.push({...p,type:'life',label:'拖把清理牛奶（E）'});
  const teacher=this.g.npcs.find(n=>n.type==='patrol_teacher');if(teacher&&teacher.hp>0)out.push({id:'life:report',type:'life',label:'向校安老師告知情況（E）',x:teacher.x,z:teacher.z});
  for(const c of this.cases){if(c.kind==='theft'&&c.stage>=1){const owner=this.g.npcs.find(n=>n.id===c.owner);if(owner)out.push({id:c.id+':return',type:'life',priority:this.g.held?.id===c.items[0]?0:3,label:this.g.held?.id===c.items[0]?'交還同一顆陀螺（E）':'失主：朋友剛才拿走了陀螺',x:owner.x,z:owner.z});}if(c.kind==='patrol'&&c.stage===1)out.push({id:c.id+':evidence',type:'life',label:'查看受限制小物（E）',...c.points[0]});}return out;}
 interact(id:string){if(id==='life:eat'){this.eat();return;}if(id==='life:report'){const c=this.cases.find(c=>['patrol','assembly'].includes(c.kind));const t=this.g.npcs.find(n=>n.type==='patrol_teacher');if(!c||!t||!this.owns(t)){this.say('校安老師：有狀況再告訴我');return;}c.reported=true;this.log(c,'玩家告知情況',this.g.player.id,t.id);this.say('校安老師：我走過去確認');return;}
  const puddle=this.puddles.find(p=>p.id===id);if(puddle){if(this.g.held?.type!=='mop')return;this.job={kind:'clean',id,time:0,start:{x:this.g.player.x,z:this.g.player.z},hp:this.g.player.hp};this.g.player.action='Clean';return;}
  const c=this.cases.find(c=>id.startsWith(c.id+':'));if(!c)return;if(id.endsWith(':evidence')){this.say('校園受限制物品；請告知校安老師');return;}if(id.endsWith(':return')){const i=this.g.objects.get(c.items[0]);if(i?.owner!==this.g.player.id){this.say('失主指向朋友：他說借一下');return;}this.g.detach(i);Object.assign(i,c.points[0],{y:0,state:'settled'});this.completeTheft(c);}}
 eat(abnormal?:boolean){if(this.g.meeting.running||this.p.mealCooldown>0||this.job){this.say('午餐冷卻中，稍後再來');return false;}if(distance(this.g.player,{x:-25.4,z:-19.4})>2.5)return false;if(!this.p.pendingMeal){const seed=this.next(this.next(this.g.rosterSeed^Math.imul(this.p.mealSerial+1,2654435761)));this.p.pendingMeal={seed,abnormal:abnormal??seed/4294967296<.1};this.g.onSave();}this.job={kind:'eat',id:'meal',time:0,start:{x:this.g.player.x,z:this.g.player.z},hp:this.g.player.hp};this.g.player.action='eat';return true;}
 completeTheft(c:Case,actor=this.g.player.id){this.say('原來只是借一下；陀螺已交還');if(c.recoveryHit&&(actor===this.g.player.id||this.p.ledger.some(e=>e.incidentId===c.id&&e.resolutionReason==='recoveryHit'&&e.sourceActorId===this.g.player.id)))this.award(3);this.log(c,'同一物品交還',actor,c.owner,c.items[0]);this.finish(c,true,'失物已交還');}
 speed(p:Vec){return (p===this.g.player&&this.p.stomach>0?.85:1)*(this.puddles.some(v=>v.age>=60&&distance(v,p)<1.2)?.9:1)}
 navigation(n:NPC,target:Vec){if(!['Idle','Walk','LifePatrol'].includes(n.state))return target;const p=this.puddles.find(p=>p.age>=30&&distance(n,p)<3&&distance(target,p)>1.8);if(!p)return target;const v=norm(target.x-n.x,target.z-n.z),toward=(p.x-n.x)*v.x+(p.z-n.z)*v.z;if(toward<0||Math.abs((p.x-n.x)*v.z-(p.z-n.z)*v.x)>1.1)return target;const choices=[{x:p.x-v.z*1.7,z:p.z+v.x*1.7},{x:p.x+v.z*1.7,z:p.z-v.x*1.7}];return choices.find(q=>!this.g.world.blocked(q,.38))||target;}
 tick(dt:number,input:{x:number,z:number}){
  this.p.clock+=dt;for(const i of [...this.g.objects.values()])if((i as any).lifeRetiredAt!==undefined&&i.owner!==this.g.player.id&&this.p.clock-(i as any).lifeRetiredAt>20)this.g.removeItem(i.id);this.p.mealCooldown=Math.max(0,this.p.mealCooldown-dt);this.p.stomach=Math.max(0,this.p.stomach-dt);if(this.captionUntil<=this.p.clock&&this.queue.length)this.say(this.queue.shift()!);
  if(this.job){const j=this.job;if(Math.hypot(input.x,input.z)>.08||distance(j.start,this.g.player)>.15||this.g.player.hp<j.hp||this.g.player.attack){this.job=null;this.say('動作中斷，可以稍後再試');}else{j.time+=dt;this.g.player.action=j.kind==='eat'?'eat':'Clean';this.g.player.actionTime=.2;if(j.time>=(j.kind==='eat'?1:1.5)){this.job=null;if(j.kind==='eat'){this.g.player.hp=Math.min(100,this.g.player.hp+20);const abnormal=this.p.pendingMeal!.abnormal;this.p.pendingMeal=null;this.p.mealSerial++;this.p.mealCooldown=90;if(abnormal){this.p.stomach=15;this.award(0);this.say('肚子提出異議：我想先走慢一點');}else this.say('午餐補充體力，今天也辛苦了');this.log(null,abnormal?'午餐提出異議':'午餐完成',this.g.player.id);}else{const p=this.puddles.find(p=>p.id===j.id);if(p){if(p.age>=30)this.award(1);this.puddles=this.puddles.filter(v=>v!==p);this.log(null,'牛奶清理完成',this.g.player.id,undefined,p.id,'milk');this.say('拖把清理完成；走廊又清爽了');}}this.g.onSave();}}}
  for(const p of this.puddles){const age=p.age;p.age+=dt;if(age<30&&p.age>=30)this.say('牛奶變酸了，拖把可以清理');if(age<60&&p.age>=60)this.say('牛奶有味道了，走近會慢一點');}for(const n of this.g.npcs)(n as any).lifeOdor=['Idle','Walk','LifePatrol'].includes(n.state)&&this.puddles.some(p=>p.age>=30&&distance(p,n)<2);const expired=this.puddles.filter(p=>p.age>=120);if(expired.length)this.say('值日清潔完成，牛奶漬消失了');this.puddles=this.puddles.filter(p=>p.age<120);this.fragments.forEach(f=>f.age+=dt);this.fragments=this.fragments.filter(f=>f.age<20);
  for(const c of [...this.cases])this.tickCase(c,dt);this.sync();this.patrol(dt);
  if(this.p.clock>=this.p.nextMain){this.p.nextMain=this.p.clock+30;const pool=(this.phase==='升旗'?['assembly']:['theft','patrol']) as LifeKind[];const eligible=pool.filter(k=>(this.p.cooldowns[k]||0)<=this.p.clock);const weighted=eligible.flatMap(k=>Array(this.p.recent.includes(k)?1:3).fill(k));if(weighted.length)this.start(weighted[Math.floor(this.g.rng.next()*weighted.length)]);}
  if(this.p.clock>=this.p.nextSide){this.p.nextSide=this.p.clock+60;const kinds=(this.phase==='午餐'?['milk','baseball','milk']:['milk','baseball']) as LifeKind[];const pool=kinds.filter(k=>(this.p.cooldowns[k]||0)<=this.p.clock);if(pool.length)this.start(pool[Math.floor(this.g.rng.next()*pool.length)]);}
 }
 tickCase(c:Case,dt:number){c.age+=dt;c.stageTime+=dt;c.warning=Math.max(0,c.warning-dt);const actors=c.actors.map(id=>this.g.npcs.find(n=>n.id===id));if(actors.some(n=>!n)||c.items.some(id=>!this.g.objects.has(id))){this.finish(c,false,'人物或物品不可用');return;}const ns=actors as NPC[];const students=ns.filter(n=>n.role==='student');const teacher=ns.find(n=>n.type==='patrol_teacher');
  if(c.kind==='assembly'&&this.phase!=='升旗'){this.say('本輪集合已結束');this.finish(c,false,'升旗階段結束');return;}
  if(c.age>=(c.kind==='baseball'?45:90)){this.say(c.kind==='theft'?'失物已由導師安全收回':'巡查中斷；事件安全結束');this.finish(c,false,'期限結束');return;}
  if(c.stage===0){let ready=true;students.forEach((n,i)=>{if(!this.owns(n)||!this.move(n,c.points[i],dt,c))ready=false;});if(!this.cases.includes(c))return;if(!ready)return;c.stage=1;c.state='Active';c.stageTime=0;students.forEach((n,i)=>{n.state=c.kind==='assembly'&&i>=3?'LifePhone':c.kind==='theft'&&i===0?'LifePoint':'LifeIdle';n.face={x:0,z:1};});if(teacher){teacher.state='LifeInspect';teacher.path=[];teacher.repath=0;}
   if(c.kind==='theft'){const thief=students[1],i=this.g.objects.get(c.items[0])!;this.takeFor(c,i,thief);this.say('失主：我的朋友剛剛把陀螺拿走了');this.log(c,'朋友取走可見的同一顆陀螺',thief.id,c.owner,i.id);}
   if(c.kind==='baseball')this.takeFor(c,this.g.objects.get(c.items[1])!,students[1]);if(c.kind==='milk')this.takeFor(c,this.g.objects.get(c.items[0])!,students[0]);this.sync();return;}
  if(c.kind==='milk'){if(c.stageTime<2){students[0].state='LifeThrow';return;}const i=this.g.objects.get(c.items[0])!;this.g.detach(i);Object.assign(i,c.points[1],{state:'settled',y:0});for(let k=0;k<Math.min(2,3-this.puddles.length);k++)this.puddles.push({id:c.id+':spill:'+k,x:c.points[1].x+k*.8,z:c.points[1].z+.6,age:0});this.say('牛奶落地；拿拖把可以清理');this.log(c,'學生牛奶灑落',students[0].id,undefined,i.id);this.finish(c,true,'牛奶交由場景管理');return;}
  if(c.kind==='baseball'){const i=this.g.objects.get(c.items[0])!;const t=c.stageTime%4/4;i.x=c.points[0].x+(c.points[1].x-c.points[0].x)*t;i.z=c.points[0].z+(c.points[1].z-c.points[0].z)*t;i.y=.8+Math.sin(t*Math.PI)*.7;students[0].state='LifeThrow';students[1].state=t>.6?'LifeSwing':'LifeIdle';if(Math.floor(c.stageTime/4)>c.swings){c.swings++;if(c.swings===c.breakAt){const broom=this.g.objects.get(c.items[1])!;broom.broken=true;this.g.emit('lifeCrack',{},students[1].id);this.fragments=[{...c.points[1],age:0},{x:c.points[1].x+.5,z:c.points[1].z,age:0}];this.say('喀！掃把：我沒有報名棒球隊');if(distance(this.g.player,c.points[1])<8&&this.g.world.visible(this.g.player,c.points[1]))this.award(2);this.log(c,'掃把折斷',students[1].id,undefined,broom.id);this.finish(c,true,'棒球練習結束');}}return;}
  if(c.kind==='theft'){const thief=this.g.npcs.find(n=>n.id===c.thief)!;const parent=this.g.npcs.find(n=>n.id===c.parent)!;const i=this.g.objects.get(c.items[0])!;if(this.owns(parent)&&this.move(parent,thief,dt,c)&&i.owner===thief.id){if(c.stageTime>10){/* Neutral, event-authored recovery hit: never attributed to the player. */const first=this.hit(thief,parent.id);thief.hp=Math.max(0,thief.hp-5);thief.state=thief.hp?'LifeSurprise':'Recover';thief.timer=8;(thief as any).flashUntil=this.g.time+.22;this.g.emit('CombatResolved',{damage:5,npc:thief.id,projectile:false,recoveryHit:first},parent.id,thief.id,i.id);this.log(c,first?'家長請求歸還並輕碰':'家長詢問',parent.id,thief.id,i.id);this.say('家長：先把借來的東西還回去');}}
   if(i.owner!==this.g.player.id&&i.owner!==thief.id&&c.stageTime>14&&distance(parent,i)<2){this.completeTheft(c,parent.id);}return;}
  if(teacher&&!this.owns(teacher)){this.finish(c,false,'校安老師有優先工作');return;}
  if(c.kind==='patrol'||c.kind==='assembly'){const target=c.kind==='assembly'?c.points[3]:c.points[0];if(c.stage===1){if(!c.reported&&c.stageTime<8)return;if(!this.move(teacher!,target,dt,c))return;c.stage=2;c.stageTime=0;teacher!.state='LifeInspect';students.forEach((n,i)=>n.state=c.kind==='patrol'?'LifeHide':i<3?'LifeIdle':['LifeCover','LifeUrgent','LifeWord','LifePoint','LifeLate'][c.responses[i]]);if(c.kind==='assembly')this.g.emit('lifePhone',{},students[3].id);this.say(c.kind==='patrol'?'校安老師：受限制物品先收起來':'校安老師：打完了？');this.log(c,'校安老師實際到場',teacher!.id);this.sync();return;}
   if(c.stage===2){if(c.stageTime<(c.kind==='assembly'&&c.responses.slice(3).includes(4)?3:1))return;if(c.kind==='assembly'){const responses=['我以為今天室內升旗。','剩三十秒，真的剩三十秒！','這是英語單字遊戲。','他昨天就說今天要躲這裡。','補一下！'];this.say(responses[c.responses[3]]);this.say('學生：輸了。老師：現在去升旗。');}else this.say('學生：我們只是在做科展……');c.stage=3;c.stageTime=0;students.forEach(n=>{n.state='LifeEscort';n.path=[];n.repath=0;});this.sync();return;}
   if(c.stage===3){let done=true;students.forEach((n,i)=>{const p=this.g.world.approach(c.kind==='assembly'?{x:-3+i*1.5,z:5}:{x:-3+i*1.3,z:-10.8},n);if(!this.move(n,p,dt,c))done=false;});this.move(teacher!,this.g.world.approach({x:2,z:c.kind==='assembly'?5:-10.8},teacher!),dt,c);if(done){if(c.reported)this.award(c.kind==='patrol'?4:5);this.say(c.kind==='assembly'?'同學回到升旗隊伍；妳可以自由走動':'巡查完成，回到正常校園生活');this.finish(c,true,'實際到場並完成帶回');}else if(c.kind==='assembly'&&c.stageTime>10){this.say('集合路線中斷，本輪安全結束');this.finish(c,false,'帶回超過十秒');}}}
 }
 patrol(dt:number){const t=this.g.npcs.find(n=>n.type==='patrol_teacher');if(!t||this.reserved(t)||t.hp<=0||!['Idle','Walk','LifePatrol'].includes(t.state)||t.soundInvestigation||this.g.chase.includes(t))return;const route=[{x:1,z:-10},{x:-13,z:-16},{x:-8,z:-16.5},{x:8,z:-16.5},{x:0,z:0}];t.state='LifePatrol';this.normalPatrolWait=Math.max(0,this.normalPatrolWait-dt);if(this.normalPatrolWait>0)return;if(this.move(t,this.g.world.approach(route[this.normalPatrol],t),dt)){this.normalPatrol=(this.normalPatrol+1)%route.length;this.normalPatrolWait=3;}}
 visuals(){const out:{type:string,x:number,z:number,y:number,angle?:number}[]=[];for(const p of this.puddles)out.push({type:p.age<30?'milk_fresh':p.age<60?'milk_sour':'milk_stinky',x:p.x,z:p.z,y:.055});for(const f of this.fragments)out.push({type:'broken_broom_parts',x:f.x,z:f.z,y:.12});if(this.p.stomach>0)out.push({type:'stomach_icon',x:this.g.player.x,z:this.g.player.z,y:2});for(const c of this.cases){if(c.stage<1)continue;if(c.kind==='patrol'&&c.stage<3){if(((c as any).hiddenUntil||0)<c.age)out.push({type:'restricted_item_evidence',...c.points[0],y:.9});if(c.stage===1&&((c as any).hiddenUntil||0)<c.age)for(let i=0;i<2;i++)out.push({type:'life_smoke',x:c.points[0].x+i*.4,z:c.points[0].z,y:1.4+Math.sin(c.age)*.1});}if(c.kind==='assembly'&&c.stage<3&&((c as any).hiddenUntil||0)<c.age)for(let i=3;i<c.points.length;i++){const n=this.g.npcs.find(n=>n.id===c.actors[i]);if(n&&!(c.stage===2&&c.responses[i]===0))out.push({type:c.stage===2&&c.responses[i]===2?'student_phone_win':'student_phone',x:n.x,z:n.z+.35,y:1.1});}}return out;}
 context(){return `${this.phase} · ${Math.ceil(360-this.p.clock%360)}秒至新一輪`+(this.cases.length?' · '+this.cases.map(c=>lifeNames[c.kind]).join('／'):'');}
}
