import './style.css';
import {Game} from './game';import {Renderer} from './render';import {Input} from './input';import {AudioEngine} from './audio';import {UI} from './ui';import {SaveStore} from './save';
const app=document.querySelector('#app');app.innerHTML=`<main id="game"><canvas id="world" aria-label="東山校園3D沙盒"></canvas><div class="hud"><div id="health-vignette" aria-hidden="true" hidden></div><div id="hit-feedback" aria-hidden="true"></div><div class="top-left"><div class="school-brand">東山 <span>校園大騷動</span></div><div class="status-card"><div class="hp-line"><span>開心導師</span><b id="hp-text">100 / 100</b></div><div class="hp-track"><div id="hp-bar"></div></div><div class="alert-line"><b id="alert-text">警戒 0</b><span id="alert-circles"></span></div><small id="alert-reason">校園一切正常</small><small id="meeting-ready"></small><small id="health-warning" role="status" hidden></small></div></div><div class="top-right"><span id="points" class="point-pill">20 點</span><button id="dogs-entry" aria-label="校狗">校狗</button><button id="map" aria-label="校園地圖">⌖</button><button id="menu" aria-label="暫停">Ⅱ</button></div><div class="quest"><button id="quest-toggle" aria-expanded="true" aria-controls="quest-body" aria-label="收合今日提示"><span class="eyebrow"><span class="quest-caption">TODAY AT DONGSHAN</span><span id="zone">導師辦公室</span></span><span id="quest-chevron" aria-hidden="true">△</span></button><div id="quest-body"><h3 id="quest-title">今天，想做點什麼？</h3><p id="quest-detail"></p><button id="skip">跳過教學</button></div></div><div class="side-nav"><button id="tasks"><span>☷</span>待辦</button><button id="calendar"><span>▦</span>行事曆</button></div><div id="meeting-controls" hidden><button id="meeting-use">特殊互動 F</button><button id="meeting-leave">離席</button></div><div id="meeting-display" hidden></div><div id="arrival" hidden></div><div id="beat" hidden></div><div id="speech" hidden></div><div id="microphone-speech" role="status" hidden></div><div id="toast" role="status" aria-live="polite"></div><div class="bottom-info"><span id="held">空手・從容</span><button id="actions">動作</button><span id="context">靠近物品或人物</span></div><div class="controls"><div id="joystick" aria-label="移動搖桿"><div id="knob"></div></div><div class="action-cluster"><button id="drop" hidden aria-label="放下手中物品 R">↓<small>放下 R</small></button><button id="throw" hidden>↗<small>投擲 Q</small></button><button id="conduct" hidden>♫<small>指揮 Enter</small></button><button id="dodge">↝<small>閃避 K</small></button><button id="attack">✦<small>揮打 J</small></button><button id="interact">✋<small>互動 E</small></button></div></div><pre id="debug-hud" hidden></pre><small id="save-warning"></small></div><div id="modal"></div></main>`;
const store=new SaveStore();const game=new Game(store.load(),6477);let render:Renderer;try{render=new Renderer(document.querySelector('#world'),game)}catch(e){app.innerHTML='<div class="compat"><h1>需要 WebGL 2 支援</h1><p>此瀏覽器未能啟動真正3D畫面。請開啟硬體加速或改用支援WebGL的瀏覽器。</p><pre></pre></div>';document.querySelector('pre').textContent=e.message;throw e}
game.cameraVisible=p=>render.inView(p);
 const input=new Input(document.querySelector('#world'),document.querySelector('#joystick'),document.querySelector('#knob'));const audio=new AudioEngine(game);const ui=new UI(game,render,input,audio,store);document.querySelector('#skip').addEventListener('click',()=>game.finishTutorial());
document.querySelector('#meeting-use').addEventListener('click',()=>game.meeting.secondary());document.querySelector('#meeting-leave').addEventListener('click',()=>game.meeting.leave());
let last=performance.now(),acc=0;function loop(now:number){let delta=(now-last)/1000;last=now;let elapsed=Math.min(.133,delta);if(!ui.paused){acc+=elapsed;let steps=0;while(acc>=1/30&&steps++<4){game.tick(1/30,input.movement());acc-=1/30}if(steps>=4)acc=0;}else acc=0;render.frame(delta,ui.started&&!ui.paused,ui.paused?1:acc/(1/30));ui.update(elapsed);requestAnimationFrame(loop)}requestAnimationFrame(loop);
let departing=false;window.addEventListener('pageshow',e=>{if(e.persisted){departing=false;store.resume()}});
ui.onPause=()=>{acc=0};document.addEventListener('visibilitychange',()=>{if(document.hidden&&!departing){input.clear();audio.pause();if(ui.started)ui.open('pause');store.save(game.profile)}});window.addEventListener('blur',()=>{input.clear();if(ui.started)ui.open('pause')});window.addEventListener('pagehide',e=>{departing=true;store.save(game.profile);store.dispose();audio.pause();if(!e.persisted)audio.dispose()});let canvas=document.querySelector('#world');canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();render.ctxLost=true;store.save(game.profile);ui.open('pause');ui.toast('3D繪圖中斷，已暫停並儲存。等待恢復或重新載入。')});canvas.addEventListener('webglcontextrestored',()=>{render.ctxLost=false;render.lastSession=-1;ui.toast('3D畫面已恢復，按繼續遊玩')});
if(import.meta.env.DEV)(window as any).__dongshan={game,render,input,audio,ui,store};
