import type {Game,NPC,Item,Event} from './game';
import {itemDefs,chapters} from './data';
import {World,distance,norm} from './world';
import {modules,selectModules,MeetingArchive} from './meeting-data';
export type MeetingPhase='CAMPUS'|'ENTERING'|'OPENING'|'ACTIVE'|'ENDING'|'RETURNING';
export class Meeting{
 phase:MeetingPhase='CAMPUS';seed=0;id='';selected:string[]=[];elapsed=0;phaseTime=0;chaos=0;events:Event[]=[];speech='';speechUntil=0;queue:string[]=[];nextSpeech=0;done=new Set<string>();hits=new Set<string>();downs=new Map<string,number>();downIds=new Set<string>();interruptions=0;downed=0;host='';sleepId='';snapshot:any;origin:any;timers=new Map<string,number>();votes=new Map<string,number>();changedVote=false;voteResult:string[]=[];papers:string[]=[];water:{x:number,z:number}[]=[];projectorPage=0;cards:string[]=[];airMode=-1;airSeen=new Set<number>();boardMusic=false;agenda=0;fold:any=null;idle=0;elegant=0;musicUntil=0;musicReturning=false;endReason='';requested='';activity='';testHold=false;guest:string|undefined;
 constructor(public g:Game){}
 get running(){return this.phase!=='CAMPUS'}
 start(seed?:number,selected?:string[],guest?:string){if(this.running)return false;const g=this.g,p=g.profile.meeting;if(p.cooldown>0&&seed===undefined)return false;this.seed=seed??Math.floor(g.rng.next()*4294967296);this.selected=selected??selectModules(this.seed,p.history,p.seen);if(this.selected.some(id=>!modules.some(m=>m.id===id)))throw Error('未知橋段');this.id=`meeting:${++p.serial}:${this.seed}`;this.activity=g.mode==='normal'?chapters[p.records.length%4].id:g.mode;this.guest=guest??((this.seed&1)?'shop_aunt':'guard_uncle');this.origin={item:g.player.item,wig:g.player.wig,glasses:g.player.glasses,items:[...g.objects.values()].filter(i=>i.owner===g.player.id).map(i=>({...i,hit:[...i.hit]}))};
 this.snapshot={world:g.world,layout:g.layout,objects:g.objects,npcs:g.npcs,props:g.props,player:{...g.player},time:g.time,previous:g.previous,broadcasts:g.broadcasts,microphoneCall:g.microphoneCall,pending:g.pending,familyQueue:g.familyQueue,cooldowns:g.cooldowns,attempt:g.attempt,race:g.race,choir:g.choir,alert:g.alert,reason:g.reason};
 this.phase='ENTERING';this.phaseTime=0;this.elapsed=0;this.chaos=0;this.events=[];this.queue=[];this.speech='';this.speechUntil=0;this.nextSpeech=0;this.done.clear();this.hits.clear();this.downs.clear();this.downIds.clear();this.timers.clear();this.votes.clear();this.airSeen.clear();this.interruptions=0;this.downed=0;this.papers=[];this.water=[];this.projectorPage=0;this.boardMusic=false;this.agenda=0;this.fold=null;this.idle=0;this.elegant=0;this.musicUntil=0;this.musicReturning=false;this.endReason='';this.requested='';this.changedVote=false;this.testHold=false;this.checkpoint();g.onSave();return true;}
 checkpoint(){const p=this.g.profile.meeting;p.pending={id:this.id,seed:this.seed,selected:[...this.selected],activity:this.activity,phase:this.phase,elapsed:this.elapsed,chaos:this.chaos,origin:this.origin,cast:this.g.npcs.filter(n=>n.id.startsWith('meeting:')).map(n=>n.label),interruptions:this.interruptions,downed:this.downed};}
 setup(){const g=this.g;g.world=new World();g.world.walls=[{id:'meeting-back',x:0,z:0,w:12,d:.25,wall:true},{id:'meeting-left',x:-6,z:5,w:.25,d:10,wall:true},{id:'meeting-right',x:6,z:5,w:.25,d:10,wall:true},{id:'meeting-front-l',x:-3.8,z:10,w:4.4,d:.25,wall:true},{id:'meeting-front-r',x:3.8,z:10,w:4.4,d:.25,wall:true}];g.layout={furniture:[{id:'meeting-table',type:'work_desk',zone:'meeting_room',x:0,z:4.4,w:2.2,d:4.8,h:.9,angle:0,solid:true,top:.95},{id:'meeting-evidence',type:'counter',zone:'meeting_room',x:-4.5,z:3.8,w:1,d:3,h:.7,angle:0,solid:true,top:.75},{id:'meeting-files',type:'file_cabinet',zone:'meeting_room',x:4.9,z:1.3,w:1.2,d:.6,h:1.5,angle:0,solid:true}],placements:{},propPositions:{},signs:[{text:'校事會議大混亂',x:0,z:.25,y:2,size:4},{text:chapters.find(c=>c.id===this.activity)?.label||'校園事件',x:-4,z:.5,y:1.6,size:2},{text:'離席 ↓',x:0,z:9.6,y:.3,size:2}]};g.objects=new Map();g.npcs=[];g.props=[];g.previous=new Map();g.broadcasts=new Map();g.microphoneCall=null;g.pending=[];g.familyQueue=[];g.cooldowns=new Map();g.attempt=null;g.race=null;g.choir=null;g.alert=0;g.reason='可以搗亂，也可以隨時離席';
 const seats=[{x:0,z:1.3},{x:-2,z:3.1},{x:2,z:3.1},{x:2,z:6.3}];const cast=[['principal','主席'],['spatula','家長代表'],['dean','紀錄委員'],[this.selected.includes('guest_mediator')?this.guest!:'patrol_teacher',this.selected.includes('guest_mediator')?(this.guest==='shop_aunt'?'合作社阿姨':'警衛伯伯'):'秩序委員']];cast.forEach(([type,label],k)=>{const n=g.addNPC(type,k===1?'parent':'staff',seats[k],`meeting:${k}`);Object.assign(n,{label,hp:3,maxHp:3,state:'Seated',active:true});this.votes.set(n.id,(this.seed+k)%3);this.spawn('office_chair',`chair:${k}`,seats[k].x,seats[k].z+(k===0?-.8:.95),0);});this.host=g.npcs[0].id;this.sleepId=g.npcs[1+(this.seed%2)].id;
 const base=[['meeting_report','report',-4.35,2.8],['folder','folder',-4.35,4],['meeting_gavel','gavel',-.6,2],['meeting_name','name',.7,2],['wireless_microphone','mic',-.7,6.4]];for(const [type,id,x,z] of base)this.spawn(type as string,id as string,x as number,z as number);
 let k=0;for(const mod of this.selected){for(const type of modules.find(m=>m.id===mod)!.tools){if(type==='meeting_report')continue;const count=type==='meeting_vote'?4:type==='coffee_cup'?3:type==='meeting_stamp'?3:1;for(let c=0;c<count;c++){const pos=type==='meeting_vote'?{x:seats[c].x+(c===1?.9:c===0?0:-.9),z:seats[c].z}: {x:-4.35+(k%2)*8.6,z:5+(Math.floor(k/2)%3)*.8};const evidenceType=mod==='reenactment'?(g.profile.meeting.campusEvents.filter(e=>['textbook','badminton_racket','music_stand'].includes(e.itemTypeId)).at(-1)?.itemTypeId||type):type;const i=this.spawn(evidenceType,`${mod}:${c}`,pos.x,pos.z,type==='meeting_vote'?.98:.75);(i as any).module=mod;if(type==='meeting_vote')(i as any).vote=(this.seed+c)%3;k++;}}}
 if(this.selected.includes('printer')||this.selected.includes('tea_spill'))g.props.push({id:'meeting-tray',type:'tray',label:'檔案盤',x:4.25,z:4,w:.55,d:.4,hp:10,broken:false});
 for(const old of this.origin.items){const original=this.snapshot.objects.get(old.id);g.objects.set(original.id,original);original.x=-4.35;original.z=2.4;original.y=.75;original.state=original.id===this.origin.item?'settled':'worn';original.owner=original.id===this.origin.item?null:g.player.id;}
 Object.assign(g.player,{x:0,z:8,hp:100,item:null,attack:null,attackCooldown:0,inv:0,hidden:false,dodge:0,action:'idle'});g.refreshColliders();g.session++;
 this.cards=g.profile.meeting.campusEvents.filter(e=>g.profile.meeting.campusClock-(e.campusTime??e.timestamp)<=300).slice(-3).map(e=>e.text);if(!this.cards.length)this.cards=['請說明本次校園事件'];this.cards.push('感謝聆聽，敬請指教');this.say('主席：可以搗亂，也可以隨時離席。');this.queue.push('紀錄委員：請一次一人發言。');this.phase='OPENING';this.phaseTime=0;this.checkpoint();g.onSave();}
 spawn(type:string,id:string,x:number,z:number,y=.98){const i=this.g.createItem(type,`${this.id}:${id}`,{x,z,y});(i as any).meetingOnly=true;return i;}
 say(text:string){this.queue.push(text.slice(0,38));if(this.queue.length>4)this.queue.shift();}
 award(id:string){if(this.done.has(id))return;this.done.add(id);this.chaos=Math.min(100,this.chaos+8);this.g.emit('meetingFeature',{module:id});}
 title(t:string){if(!this.g.profile.meeting.titles.includes(t)){this.g.profile.meeting.titles.push(t);this.g.onSave();}}
 capture(e:Event){Object.assign(e,{kind:e.type,sourceActorId:e.actorId,targetType:e.targetId?'actor':'item',itemTypeId:e.data.item||this.g.held?.type,gameTime:this.elapsed,activityDay:this.activity});this.events.push(e);if(this.events.length>60)this.events.shift();if(this.events.length>=12)this.title('紀錄追不上本人');const i=e.data.id?this.g.objects.get(e.data.id):null;const mod=(i as any)?.module;
 if(e.type==='CombatResolved'&&e.data.projectile&&this.selected.includes('cross_talk')){const thrown=[...this.g.objects.values()].find(i=>i.flight===e.sourceId);if(thrown&&['folder','meeting_report'].includes(thrown.type)){this.chain();this.award('cross_talk');}}
 if(e.type==='take'){const key='take:'+e.data.id;if(!this.done.has(key)){this.done.add(key);this.chaos=Math.min(100,this.chaos+2);}if(mod==='printer'){this.say('紀錄委員：缺紙，請稍候。');this.react('Collect',2);this.award('printer');}}
 if(['push','pushItem'].includes(e.type)){this.furnitureScore(e.data.id);}
 if(['swing','throw'].includes(e.type)&&this.selected.includes('reenactment')&&this.elapsed>=8&&(this.g.held?.id.includes('reenactment')||e.data.id?.includes('reenactment')||e.data.item==='folder'||e.data.item===[...this.g.objects.values()].find(i=>(i as any).module==='reenactment')?.type)){this.award('reenactment');this.say('主席：示範到這裡就好。');this.react('Surprise',1);}
 if(e.type==='throw'&&(i as any)?.plane){this.award('paper_planes');this.title('證據飛走了');i.vx!*=.7;i.vz!*=.7;i.vy=2.2;this.react('Watching',1);}
 if(e.type==='land'&&i){if(i.type==='wireless_microphone')this.react('Listening',1);if(mod==='tea_spill')this.spill(i);if(mod==='bell'&&!this.done.has('bell-land:'+i.id)){this.done.add('bell-land:'+i.id);this.react('Listening',1);this.g.emit('instrument',{item:'triangle'});}if(this.selected.includes('cross_talk')&&['folder','meeting_report'].includes(i.type)&&this.g.npcs.some(n=>distance(n,i)<1.5)){this.chain();this.award('cross_talk');}}
 }
 furnitureScore(id:string){if((this.timers.get('furniture:'+id)||0)>this.elapsed)return;this.timers.set('furniture:'+id,this.elapsed+3);this.chaos=Math.min(100,this.chaos+3);}
 interrupt(force=false){if(!force&&!this.g.npcs.some(n=>n.state==='Speaking'&&n.hp>0))return false;if((this.timers.get('interrupt')||0)>this.elapsed)return;this.timers.set('interrupt',this.elapsed+3);this.interruptions++;this.chaos=Math.min(100,this.chaos+3);if(this.interruptions>=5)this.title('議程粉碎機');return true;}
 hit(n:NPC,source:string,projectile:boolean){if(this.phase!=='ACTIVE'||!this.g.npcs.includes(n))return false;const key=source+':'+n.id;if(this.hits.has(key))return false;this.hits.add(key);if(this.hits.size>200)this.hits.delete(this.hits.values().next().value!);const old=n.state;if(['Speaking','Voting','Coordinating'].includes(old))this.interrupt(true);if(old==='Sleeping'){this.timers.set('sleep',this.elapsed+12);this.award('sleepy_member');this.say('委員：我同意剛才的決議！');}if(old==='Coordinating'&&this.selected.includes('guest_mediator'))this.award('guest_mediator');this.g.emit('CombatResolved',{damage:projectile?2:1,npc:n.id,projectile},this.g.player.id,n.id,source);this.chaos=Math.min(100,this.chaos+6);n.attack=null;(n as any).flashUntil=this.elapsed+.22;const f=norm(n.x-this.g.player.x,n.z-this.g.player.z);const p=this.g.world.move(n,f.x*(n.hp<=0?.18:.65),f.z*(n.hp<=0?.18:.65),.32);n.x=p.x;n.z=p.z;
 if(n.hp>0){n.hp=Math.max(0,n.hp-(projectile?2:1));if(n.hp===0){n.state='Recover';n.timer=3;(n as any).downAt=this.elapsed;this.downed++;this.downIds.add(n.id);if(this.elapsed-(this.downs.get(n.id)??-100)>=6){this.downs.set(n.id,this.elapsed);this.chaos=Math.min(100,this.chaos+10);}this.g.emit('NPCDowned',{npc:n.id},this.g.player.id,n.id,source);if(this.downIds.size===this.g.npcs.length)this.title('全員暫時離席');}else{n.state='hit';n.timer=.35;}}
 else n.timer=Math.min(Math.max(n.timer,.3),Math.max(0,5-(this.elapsed-(n as any).downAt)));if(n.id==='meeting:1'&&n.hp>0)(n as any).retaliate=this.elapsed+1;this.fold=null;return true;}
 react(state:string,seconds:number,ids?:string[]){for(const n of this.g.npcs)if(n.hp>0&&n.state!=='hit'&&(!ids||ids.includes(n.id))){n.state=state;n.timer=seconds;}}
 chain(){if(this.g.npcs.every(n=>n.hp<=0))return;this.react('Speaking',4);this.say('家長代表：我還有一點補充。');this.say('主席：請依照議程進行。');this.say('紀錄委員：請一次一人發言。');}
 spill(i:Item){if(this.done.has('spill:'+i.id))return;this.done.add('spill:'+i.id);this.water.push({x:i.x,z:i.z});if(this.water.length>2)this.water.shift();this.react('Protecting',4);this.say('委員：先保護檔案，不是茶杯。');this.award('tea_spill');}
 context(){const g=this.g,i=g.held,mod=(i as any)?.module;if(i){if(i.type==='meeting_report'&&this.selected.includes('paper_planes')&&!(i as any).plane)return '折紙飛機';const labels:any={projector:'切換投影',bell:'敲響鈴／三角鐵',voting:'切換表決牌',conducting:'開始指揮',musical_chairs:'播放／停止旋律',stamps:'近距離蓋章',aircon:'切換冷氣'};if(mod==='stamps'&&!g.npcs.some(n=>distance(n,g.player)<=1.2))return '';if(labels[mod])return labels[mod];if(i.type==='wireless_microphone')return '擴音打斷';if(this.selected.includes('sleepy_member')&&['triangle','castanets'].includes(i.type))return '近距離叫醒';}if(distance(g.player,{x:4.5,z:7.8})<1.8&&this.selected.includes('whiteboard'))return '翻白板／調整議程';return '';}
 secondary(){if(this.phase==='OPENING')this.activate();if(this.phase!=='ACTIVE')return false;const g=this.g,i=g.held,mod=(i as any)?.module;const key=mod||i?.type||'whiteboard';const cool:any={projector:1,bell:3,voting:.4,conducting:8,musical_chairs:10,stamps:2,aircon:4,whiteboard:3};if(!this.context()||((this.timers.get('use:'+key)||0)>this.elapsed&&!(mod==='musical_chairs'&&this.musicUntil>this.elapsed)))return false;this.timers.set('use:'+key,this.elapsed+(cool[key]||3));
 if(i?.type==='meeting_report'&&this.selected.includes('paper_planes')&&!(i as any).plane){this.fold={id:i.id,until:this.elapsed+.4};g.player.action='pickup';g.player.actionTime=.4;return true;}
 if(i?.type==='wireless_microphone'){this.interrupt();this.react('Listening',1);this.g.emit('instrument',{item:'triangle'});return true;}
 switch(mod){case 'projector':this.projectorPage=(this.projectorPage+1)%this.cards.length;if(this.elapsed>=(this.timers.get('projector-complaint')||0)){this.say('委員：請回到上一頁。');this.timers.set('projector-complaint',this.elapsed+6);}this.react('Watching',1);if(this.projectorPage===this.cards.length-1)this.award(mod);break;
 case 'bell':this.g.emit('instrument',{item:'triangle'});if(this.interrupt())this.award(mod);this.react('Listening',1);this.wake();break;
 case 'voting':(i as any).vote=(((i as any).vote||0)+1)%3;this.changedVote=true;this.say('表決牌：'+['同意','不同意','提前下班'][(i as any).vote]);break;
 case 'conducting':this.react('Following',3,g.npcs.filter(n=>n.hp>0).slice(0,3).map(n=>n.id));if(g.npcs.some(n=>n.state==='Following')){this.award(mod);this.title('教學從未停止');}g.emit('conduct');this.say('主席：老師，請坐下。');break;
 case 'musical_chairs':if(this.musicUntil>this.elapsed){this.musicUntil=0;this.musicReturning=true;this.timers.set('use:musical_chairs',this.elapsed+10);}else{this.musicUntil=this.elapsed+4;this.musicReturning=false;this.react('MusicWalk',4,g.npcs.filter(n=>n.hp>0).slice(0,3).map(n=>n.id));g.emit('instrument',{item:'recorder'});}break;
 case 'stamps':{const n=g.npcs.filter(n=>distance(n,g.player)<=1.2).sort((a,b)=>distance(a,g.player)-distance(b,g.player))[0];if(n){(n as any).stampUntil=this.elapsed+6;(n as any).stamp=['請訂正','字跡待加強','發言過長'][+i.id.split(':').at(-1)%3];this.react('Collect',1,[n.id]);this.award(mod);if(n.id==='meeting:0')this.title('主席請訂正');this.say(n.label+'：'+(n as any).stamp);}break;}
 case 'aircon':this.airMode=(this.airMode+1)%3;this.airSeen.add(this.airMode);this.timers.set('air-end',this.elapsed+5);this.react(['Cold','Hot','Protecting'][this.airMode],5);this.say('委員：'+['太冷了，請調整。','檔案可以當扇子嗎？','請按住桌上的紙。'][this.airMode]);this.award(mod);if(this.airSeen.size===3)this.title('空調由我決定');break;
 default:if(i&&['triangle','castanets'].includes(i.type)){this.wake();g.emit('instrument',{item:i.type});}else if(this.selected.includes('whiteboard')){if(!this.boardMusic){this.boardMusic=true;this.award('whiteboard');this.title('教學從未停止');this.say('主席：接下來討論……四分音符？');}else{this.agenda=(this.agenda+1)%3;this.boardMusic=false;this.say(this.agenda===1?'主席：先散場，再說明事件？':'主席：請依照議程進行。');}this.react('Watching',1);}break;}
 return true;}
 wake(){const n=this.g.npcs.find(n=>n.id===this.sleepId);if(n?.state==='Sleeping'&&distance(n,this.g.player)<2){n.state='Surprise';n.timer=1;this.timers.set('sleep',this.elapsed+12);this.award('sleepy_member');this.say('委員：我同意剛才的決議！');}}
 activate(){this.phase='ACTIVE';this.phaseTime=0;this.g.player.hp=100;this.checkpoint();this.g.onSave();}
 vote(){const g=this.g;this.voteResult=g.npcs.map(n=>{const slot={x:n.home.x+(n.id==='meeting:1'?.9:n.id==='meeting:0'?0:-.9),z:n.home.z};const i=[...g.objects.values()].filter(i=>i.type==='meeting_vote'&&i.state!=='held'&&i.state!=='airborne'&&distance(i,slot)<.65).sort((a,b)=>distance(a,slot)-distance(b,slot))[0];return i?['同意','不同意','提前下班'][(i as any).vote]:'找不到表決牌';});this.react('Voting',2);this.say('表決：'+this.voteResult.join('／'));if(this.changedVote)this.award('voting');if(this.voteResult.every(v=>v==='提前下班'))this.title('全票透過離席');if(this.voteResult.filter(v=>v==='提前下班').length>2)this.say('主席：議題是不是拿錯了？');}
 tick(dt:number,input:{x:number,z:number,run:boolean}){const g=this.g,p=g.player;this.phaseTime+=dt;g.stats.ticks++;if(this.phase==='ENTERING'){if(this.phaseTime>=.35){try{this.setup();}catch(error){this.endReason='載入中斷';this.finish();g.toast('會議載入中斷，已安全返回。');}}return;}
 if(this.phase==='OPENING'){this.g.time+=dt;if(this.phaseTime>=2||Math.hypot(input.x,input.z)>.08||p.attack)this.activate();else{this.dialogue();return;}}
 if(this.phase==='ENDING'){this.g.time+=dt;this.dialogue();if(this.phaseTime>=1.5||Math.hypot(input.x,input.z)>.08)this.finish();return;}
 if(this.phase!=='ACTIVE')return;this.elapsed+=dt;g.time+=dt;g.pathBudget=4;g.previous.set(p.id,{x:p.x,z:p.z});for(const n of g.npcs)g.previous.set(n.id,{x:n.x,z:n.z});for(const i of g.objects.values())g.previous.set(i.id,{x:i.x,z:i.z});for(const key of ['inv','attackCooldown','dodgeCooldown','actionTime','slow'])p[key]=Math.max(0,p[key]-dt);if(!p.actionTime)p.action='idle';const mag=Math.min(1,Math.hypot(input.x,input.z));if(mag>.08){const f=norm(input.x,input.z);p.face=f;const pos=g.world.move(p,f.x*mag*(input.run?4.6:3.2)*dt,f.z*mag*(input.run?4.6:3.2)*dt);p.x=pos.x;p.z=pos.z;p.action=input.run?'run':'walk';}
 if(p.dodge>0){p.dodge=Math.max(0,p.dodge-dt);const pos=g.world.move(p,p.face.x*8*dt,p.face.z*8*dt);p.x=pos.x;p.z=pos.z;}
 if(p.attack){const a=p.attack;a.age+=dt;if(a.age>=.12&&!a.resolved){a.resolved=true;for(const n of g.npcs){const f=norm(n.x-p.x,n.z-p.z);if(distance(n,p)<a.reach+.35&&f.x*p.face.x+f.z*p.face.z>=.6&&g.world.visible(p,n))g.damageNPC(n,a.damage,a.id);}for(const i of g.objects.values())if(distance(i,p)<a.reach+.4&&(i as any).module==='tea_spill')this.spill(i);for(const prop of g.props)if(distance(prop,p)<a.reach+.4){this.furnitureScore(prop.id);this.react('Collect',2,['meeting:2']);if(this.selected.includes('printer'))this.award('printer');if(this.selected.includes('tea_spill')){const cup=[...g.objects.values()].find(i=>(i as any).module==='tea_spill');if(cup)this.spill(cup);}}}if(a.age>.35)p.attack=null;}
 g.updateItems(dt);g.updateMicrophones();for(const i of g.objects.values())if(i.state==='airborne'&&i.y<1.5)for(const prop of g.props)if(distance(i,prop)<.7&&!i.hit.has(prop.id)&&i.hits===0){i.hit.add(prop.id);this.furnitureScore(prop.id);this.react('Collect',2,['meeting:2']);if(this.selected.includes('printer'))this.award('printer');}if(this.fold){if(g.held?.id!==this.fold.id)this.fold=null;else if(this.elapsed>=this.fold.until){(g.held as any).plane=true;this.fold=null;g.emit('meetingFold',{id:g.held.id});}}
 for(const n of g.npcs){n.active=true;n.repath-=dt;n.timer-=dt;if(n.hp<=0){if(n.timer<=0){n.hp=3;n.state='Seated';n.timer=2;g.emit('npcRecovered',{id:n.id},n.id);}continue;}if(n.state==='hit'){if(n.timer<=0){n.state='Seated';n.timer=2;}continue;}if(n.state==='MusicWalk')g.moveNPC(n,{x:n.home.x+(n.home.x<0?-.8:.8),z:n.home.z+.8},dt,1.2);if(this.musicReturning&&n.state==='MusicWalk'){const chair=[...g.objects.values()].find(i=>i.id.endsWith('chair:'+n.id.split(':').at(-1)));if(chair&&distance(chair,chair.home)>1){n.state='FindingChair';n.timer=2;this.award('musical_chairs');this.say('委員：我的椅子呢？');}else{g.moveNPC(n,n.home,dt,1.2);if(distance(n,n.home)<.3){n.state='Seated';n.timer=2;}}}else if(n.timer<=0&&n.state!=='MusicWalk'){if(n.state==='Sleeping')this.timers.set('sleep',this.elapsed+12);n.state='Seated';n.timer=3;}
 if((n as any).retaliate&&this.elapsed>(n as any).retaliate){(n as any).retaliate=0;if(distance(n,p)<1.4)g.damagePlayer(4,n);}
 }
 if(this.musicUntil&&this.elapsed>=this.musicUntil){this.musicUntil=0;this.musicReturning=true;this.timers.set('use:musical_chairs',this.elapsed+10);}
 const host=g.npcs.find(n=>n.id===this.host);if(!host||host.hp===0){const next=g.npcs.find(n=>n.hp>0);if(next&&next.id!==this.host){this.host=next.id;this.say(next.label+'：那我先代理。');}}else if(g.npcs[0].hp>0&&this.host!=='meeting:0'){this.host='meeting:0';this.say('主席：我們依照議程進行。');}
 if(p.z>9.7)this.requested='自行離席';if(this.musicUntil>this.elapsed&&this.elapsed>=(this.timers.get('music-note')||0)){this.timers.set('music-note',this.elapsed+.5);this.g.emit('meetingMusic',{frequency:[261.63,329.63,349.23,293.66,392,329.63,293.66,261.63][Math.floor(this.elapsed*2)%8]});}this.auto();this.dialogue();if(this.timers.has('air-end')&&this.elapsed>this.timers.get('air-end')!)this.airMode=-1;this.idle=mag>.08||p.attack?0:this.idle+dt;if(this.idle>1.5&&this.elegant<2&&this.elapsed>(this.elegant+1)*12){this.elegant++;p.action='pickup';p.actionTime=.6;this.say('女導師整齊放好一張紙。');}
 if(Math.floor(this.elapsed)!==Math.floor(this.elapsed-dt)){this.checkpoint();g.onSave();}
 const reason=p.hp<=0?'再倒地':this.requested||(!this.testHold&&this.chaos>=100?'失控值滿':!this.testHold&&this.elapsed>=75?'時間到':'');if(reason)this.end(reason);
 }
 dialogue(){if(this.g.time>=this.nextSpeech&&this.queue.length){this.speech=this.queue.shift()!;this.speechUntil=this.g.time+2;this.nextSpeech=this.g.time+1.2;this.g.toast(this.speech);}if(this.g.time>this.speechUntil)this.speech='';}
 auto(){if(this.g.npcs.every(n=>n.hp<=0))return;if(this.elapsed>=(this.timers.get('core-talk')||.5)){this.timers.set('core-talk',this.elapsed+6);const n=this.g.npcs.find(n=>n.id===this.host);if(n&&n.hp>0&&['Seated','Standing'].includes(n.state)){this.react('Speaking',1.5,[n.id]);this.say(n.label+'：請依照議程進行。');this.g.emit('meetingGavel',{hasGavel:[...this.g.objects.values()].some(i=>i.type==='meeting_gavel'&&i.state!=='held')});}}for(const [id,first,cool] of [['reenactment',8,999],['cross_talk',10,18],['tea_spill',12,999],['voting',14,20],['printer',9,6],['guest_mediator',16,10],['sleepy_member',10,18]] as [string,number,number][]){if(!this.selected.includes(id)||this.elapsed<(this.timers.get('auto:'+id)??first)||(this.timers.get('global')||0)>this.elapsed)continue;this.timers.set('auto:'+id,this.elapsed+cool);this.timers.set('global',this.elapsed+1.2);if(id==='reenactment'){const evidence=[...this.g.objects.values()].find(i=>(i as any).module==='reenactment');this.say('主席：請用'+(itemDefs[evidence?.type||'folder'].label)+'示範。');this.react('Speaking',2);}if(id==='cross_talk')this.chain();if(id==='tea_spill'){this.react('Drinking',2);this.say('委員：喝口水再討論。');}if(id==='voting')this.vote();if(id==='printer'){if([...this.g.objects.values()].some(i=>(i as any).module==='printer'&&i.state!=='held')){const last=this.events.at(-1);this.papers.push(last?.type==='CombatResolved'?'委員受到波及':last?.type==='NPCDowned'?'紀錄委員暫時離席':last?.type==='take'?'受詢人拿走'+(itemDefs[last.data.item]?.label||'物品'):last?.type==='throw'?'受詢人投擲'+(itemDefs[last.data.item]?.label||'物品'):'主席要求記錄');this.g.emit('meetingPrint');if(this.papers.length>4)this.papers.shift();this.react('Recording',1,['meeting:2']);}}
 if(id==='guest_mediator'){const n=this.g.npcs[3];if(n.hp>0&&n.state!=='hit'){this.react('Coordinating',2,[n.id]);if(n.type==='shop_aunt'&&!this.done.has('snack')){this.done.add('snack');this.say([...this.g.objects.values()].some(i=>i.type==='trash_bin')?'合作社阿姨：這個是合作社的，誰拿來的？':'合作社阿姨：事情處理完再吃。');}else if(n.type==='guard_uncle'){const chair=[...this.g.objects.values()].find(i=>i.type==='office_chair'&&distance(i,i.home)>1&&!this.g.npcs.some(n=>distance(n,i)<.7)&&distance(this.g.player,i)>1);if(chair){Object.assign(chair,chair.home);this.g.refreshColliders();}this.say('警衛伯伯：請把椅子放好。');}}}
 if(id==='sleepy_member'){const n=this.g.npcs.find(n=>n.id===this.sleepId)!;if(n.hp>0&&n.state!=='hit'&&this.elapsed>=(this.timers.get('sleep')||0)){n.state='Sleeping';n.timer=4+this.seed%5;}}}}
 leave(){if(this.phase==='ENDING'){this.finish();return;}if(this.phase==='OPENING')this.activate();if(this.phase==='ACTIVE')this.requested='自行離席';}
 end(reason:string){if(this.phase!=='ACTIVE')return;this.endReason=reason;this.phase='ENDING';this.phaseTime=0;this.g.player.attack=null;this.queue=[];this.say(reason==='再倒地'?'委員：先送保健室。':'主席：本次會議另擇日期。');this.checkpoint();this.g.onSave();}
 finish(){if(!this.snapshot)return;this.phase='RETURNING';const g=this.g,s=this.snapshot;const record:MeetingArchive={id:this.id,seed:this.seed,modules:[...this.selected],cast:g.npcs.filter(n=>n.id.startsWith('meeting:')).map(n=>n.label),seconds:Math.round(this.elapsed),reason:this.endReason,chaos:this.chaos,interruptions:this.interruptions,downed:this.downed,lines:[`本次會議進行 ${Math.round(this.elapsed)} 秒。`,`發言遭打斷 ${this.interruptions} 次，委員跌坐 ${this.downed} 次。`,`散場原因：${this.endReason}。`,['下次改用線上會議。','另成立小組檢討本次會議。','請先找回木槌，再擇期討論。'][this.seed%3]]};const progress=g.profile.meeting;if(!progress.records.some(r=>r.id===record.id))progress.records.push(record);progress.records=progress.records.slice(-20);progress.history=[...progress.history,this.selected].slice(-3);progress.seen=[...new Set([...progress.seen,...this.selected])];
 g.stopAllBroadcasts();Object.assign(g,{world:s.world,layout:s.layout,objects:s.objects,npcs:s.npcs,props:s.props,time:s.time,previous:s.previous,broadcasts:new Map(),microphoneCall:null,pending:s.pending,familyQueue:[],cooldowns:s.cooldowns,attempt:s.attempt,race:s.race,choir:s.choir,alert:15,reason:'會議散場，請從容返回校園'});Object.assign(g.player,s.player,{x:0,z:this.endReason==='再倒地'?-19:-13,hp:100,inv:8,attack:null,hidden:false,action:'idle',attackCooldown:0});for(const old of this.origin.items){const i=g.objects.get(old.id);if(i)Object.assign(i,old,{hit:new Set(old.hit),x:g.player.x,z:g.player.z});}for(const n of g.npcs){if(['Chase','Search','Attack','SoundInvestigate'].includes(n.state)){n.state='Idle';n.attack=null;n.path=[];n.lost=0;n.soundInvestigation=undefined;}}g.refreshColliders();g.session++;this.phase='CAMPUS';progress.cooldown=300;progress.pending=null;this.snapshot=null;this.queue=[];this.events=[];this.hits.clear();this.timers.clear();this.water=[];this.papers=[];this.fold=null;this.votes.clear();this.downs.clear();this.downIds.clear();this.airSeen.clear();this.done.clear();g.onSave();g.toast(record.lines.join(' '));}
}
