import {LifeProgress,emptyLife,validateLife} from './life-data';
import {DogsProgress,emptyDogs,validateDogs} from './dogs-data';
import {KnockdownCodex,emptyCodex,validateCodex} from './knockdowns';
import {MeetingProgress,emptyMeeting,validateMeeting} from './meeting-data';
import {missions,chapters,cosmetics,titles} from './data';
export type Profile={life:LifeProgress,dogs:DogsProgress,version:number,meeting:MeetingProgress,knockdownCodex:KnockdownCodex,points:number,ownedCosmetics:string[],equipped:string[],titleIds:string[],tutorialFlags:string[],completedMissionIds:string[],completedChapters:string[],rewardLedger:string[],bestRatings:Record<string,string>,statistics:Record<string,number>,photoCards:any[],serviceCooldown:number,lastMode:string,settings:{quality:string,music:number,sfx:number,mute:boolean,lowMotion:boolean,assist:boolean},revision:number};
export const fresh=():Profile=>({version:1,life:emptyLife(),dogs:emptyDogs(),meeting:emptyMeeting(),knockdownCodex:emptyCodex(),points:20,ownedCosmetics:[],equipped:[],titleIds:[],tutorialFlags:[],completedMissionIds:[],completedChapters:[],rewardLedger:[],bestRatings:{},statistics:{},photoCards:[],serviceCooldown:0,lastMode:'normal',settings:{quality:'auto',music:.35,sfx:.5,mute:false,lowMotion:false,assist:false},revision:0});
export function validateSave(data:any):Profile{if(!data||data.version!==1)throw Error('存檔版本不支援');for(let k of ['points','serviceCooldown','revision'])if(!Number.isFinite(data[k])||data[k]<0||data[k]>1e9)throw Error('存檔數值無效');let ids={ownedCosmetics:cosmetics.map(x=>x.id),equipped:cosmetics.map(x=>x.id),titleIds:titles,tutorialFlags:['done'],completedMissionIds:missions.map(x=>x.id),completedChapters:chapters.map(x=>x.id),rewardLedger:[...missions.map(x=>x.id),...chapters.map(x=>'chapter:'+x.id),'tutorial']};for(let [key,valid] of Object.entries(ids)){if(!Array.isArray(data[key])||data[key].length>200||data[key].some(x=>!valid.includes(x))||new Set(data[key]).size!==data[key].length)throw Error('存檔內容 ID 無效：'+key);}
if(data.equipped.some(x=>!data.ownedCosmetics.includes(x)))throw Error('外觀未購買');if(!['normal',...chapters.map(c=>c.id)].includes(data.lastMode))throw Error('活動 ID 無效');if(!data.settings||!['auto','low','standard'].includes(data.settings.quality)||['music','sfx'].some(k=>!Number.isFinite(data.settings[k])||data.settings[k]<0||data.settings[k]>1)||['mute','lowMotion','assist'].some(k=>typeof data.settings[k]!=='boolean'))throw Error('設定無效');if(!Array.isArray(data.photoCards)||data.photoCards.length>12||data.photoCards.some(x=>JSON.stringify(x).length>40000))throw Error('紀念卡超過限制');if(typeof data.statistics!=='object'||Object.values(data.statistics).some(x=>typeof x!=='number'||!Number.isFinite(x)||x<0))throw Error('統計無效');if(typeof data.bestRatings!=='object'||Object.entries(data.bestRatings).some(([k,v])=>!missions.some(m=>m.id===k)||!['完成','金牌','練習'].includes(v as string)))throw Error('評級無效');return {...structuredClone(data),life:validateLife(data.life),dogs:validateDogs(data.dogs),meeting:validateMeeting(data.meeting),knockdownCodex:validateCodex(data.knockdownCodex)}}
export function reward(p:Profile,id:string,points:number){if(p.rewardLedger.includes(id))return false;p.rewardLedger.push(id);p.points+=points;return true}
export function purchase(p:Profile,id:string){const item=cosmetics.find(c=>c.id===id);if(!item||p.points<item.price||p.ownedCosmetics.includes(id))return false;p.points-=item.price;p.ownedCosmetics.push(id);return true}
export class SaveStore{
 key='dongshan-campus-v1';lease='dongshan-campus-writer';id=Math.random().toString(36).slice(2);readOnly=false;error='';timer:any;
 constructor(){this.claim();this.timer=setInterval(()=>this.claim(false),5000)}
 claim(force=false){try{let old=JSON.parse(localStorage.getItem(this.lease)||'null');if(force||!old||old.id===this.id||old.expires<Date.now()){localStorage.setItem(this.lease,JSON.stringify({id:this.id,expires:Date.now()+12000}));this.readOnly=false}else this.readOnly=true}catch{this.error='儲存空間不可用，請匯出進度'}}
 load(){try{let raw=localStorage.getItem(this.key);return raw?validateSave(JSON.parse(raw)):fresh()}catch(e){this.error='未載入無效存檔：'+e.message;return fresh()}}
 save(p:Profile){this.claim(false);if(this.readOnly){this.error='另一分頁正在寫入；此頁暫不儲存，可接管';return false}try{p.revision++;localStorage.setItem(this.key,JSON.stringify(p));this.error='';return true}catch{this.error='存檔寫入失敗，遊戲可繼續，請匯出';return false}}
 dispose(){clearInterval(this.timer);try{let old=JSON.parse(localStorage.getItem(this.lease)||'null');if(old?.id===this.id)localStorage.removeItem(this.lease)}catch{}}
}
