import {dogPortrait} from './dog-portraits';
import {lifeAwards} from './life-data';
import {dogIds,dogNames,dogQuests,stage} from './dogs-data';
import {staff} from './data';
import {modules} from './meeting-data';
import {codexEntries,CodexGroup} from './knockdowns';
import {Game} from './game';
import {Renderer} from './render';
import {Input} from './input';
import {spaceButtons} from './button-spacing';
import {healthState} from './feedback';
import {AudioEngine} from './audio';
import {SaveStore,validateSave,fresh} from './save';
import {missions,chapters,students,parents,zones,cosmetics,items,itemDefs,destination,center,locations,zoneAt} from './data';
const $=(s:string)=>document.querySelector(s) as HTMLElement;
const esc=(s:any)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class UI{
 hitLabels:{x:number,z:number,start:number,damage:number}[]=[];
 questCollapsed=false;questContent='';codexTab:CodexGroup='students';paused=true;started=false;modal='';lastFocus:HTMLElement|null=null;hudClock=0;debug=false;toastUntil=0;onPause=(v:boolean)=>{};
 constructor(public game:Game,public render:Renderer,public input:Input,public audio:AudioEngine,public store:SaveStore){
 game.onToast=(s,dog)=>this.toast(s,dog);game.onSave=()=>store.save(game.profile);game.listeners.push(e=>{if(e.type==='CombatResolved'&&e.actorId===game.player.id){const n=game.npcs.find(n=>n.id===e.targetId||n.id===e.data.npc);if(n){this.hitLabels.push({x:n.x,z:n.z,start:game.time,damage:e.data.damage});this.hitLabels=this.hitLabels.slice(-8)}}if(e.type==='reset'){this.hitLabels=[];this.toastUntil=0;$('#speech').hidden=true;$('#toast').classList.remove('visible');}if(e.type==='rescue')setTimeout(()=>this.open('report'),0)});
 this.input.onAction=a=>this.action(a);this.input.onPause=()=>this.paused?this.close():this.open('pause');this.input.onAim=(x,y)=>render.aim(x,y);this.input.onSelect=(x,y)=>render.aim(x,y,true);
 $('#quest-toggle').addEventListener('click',()=>this.setQuestCollapsed(!this.questCollapsed));
 $('#quest-toggle').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')e.stopPropagation()});
 $('.quest').addEventListener('click',e=>{if(!(e.target as HTMLElement).closest('button'))this.setQuestCollapsed(!this.questCollapsed)});
 const layout=()=>{const hud=$('.hud'),r=hud.getBoundingClientRect();const extra=['#meeting-ready','#health-warning'].map(s=>{const e=$(s);return e.hidden?0:e.getBoundingClientRect().height+parseFloat(getComputedStyle(e).marginTop)}).reduce((a,b)=>a+b,0);hud.style.setProperty('--status-extra',extra+'px');hud.style.setProperty('--status-bottom',($('.top-left').getBoundingClientRect().bottom-r.top)+'px');hud.style.setProperty('--quest-card-height',$('.quest').getBoundingClientRect().height+'px')};const observer=new ResizeObserver(layout);observer.observe($('.top-left'));observer.observe($('.quest'));window.addEventListener('resize',layout);layout();
 $('#dogs-entry').addEventListener('click',()=>this.open('dogs'));$('#menu').addEventListener('click',()=>this.open('pause'));$('#tasks').addEventListener('click',()=>this.open('missions'));$('#calendar').addEventListener('click',()=>this.open('calendar'));$('#map').addEventListener('click',()=>this.open('map'));$('#actions').addEventListener('click',()=>this.open('actions',false));
 input.bindButton($('#attack'),'attack');input.bindButton($('#dodge'),'dodge');input.bindButton($('#throw'),'throw');input.bindButton($('#drop'),'drop');input.bindButton($('#conduct'),'conduct');input.bindButton($('#interact'),'interact',()=>this.open('actions',false));
 $('#modal').addEventListener('click',e=>{let b=(e.target as HTMLElement).closest('[data-action]') as HTMLElement;if(b)this.click(b.dataset.action,b.dataset.id,b.dataset.value)});
 $('#modal').addEventListener('keydown',e=>{if(e.key==='Tab'){let nodes=[...$('#modal').querySelectorAll<HTMLElement>('button:not(:disabled),input,select,a[href]')];let first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){last?.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first?.focus();e.preventDefault()}}});this.open('start');
 }
 pause(v:boolean){this.paused=v;this.input.enabled=!v&&!this.modal;this.input.clear();if(v)this.audio.pause();else this.audio.resume();this.onPause(v)}
 close(){if(!this.started)return;$('#modal').hidden=true;this.modal='';this.pause(false);this.lastFocus?.focus()}
 open(name:string,pause=true){if(this.game.meeting.running&&!['pause','actions','settings','help','meetingRecords','save','dogs'].includes(name)){this.toast('請先離席，再操作校園選單。');return;}this.lastFocus=document.activeElement as HTMLElement;this.modal=name;this.input.enabled=false;this.input.clear();if(pause)this.pause(true);$('#modal').hidden=false;let content=this.content(name);$('#modal').innerHTML=`<section class="panel ${name==='start'?'welcome':''}" role="dialog" aria-modal="true" aria-label="${esc(name==='start'?'開始遊戲':'遊戲選單')}">${content}</section>`;spaceButtons($('#modal'));setTimeout(()=>$('#modal').querySelector<HTMLElement>('button')?.focus(),0)}
 header(eyebrow:string,title:string){return `<header class="panel-head"><div><span class="eyebrow">${eyebrow}</span><h2>${title}</h2></div>${this.started?'<button class="icon-btn" data-action="close" aria-label="關閉">✕</button>':''}</header>`}
 button(label:string,action:string,id='',cls=''){return `<button class="${cls}" data-action="${action}" data-id="${esc(id)}">${label}</button>`}
 content(name:string):string{let g=this.game,p=g.profile;if(name==='pause'&&g.meeting.running)return this.header('SCHOOL MEETING','會議暫停')+`<div class=menu-grid>${this.button('繼續遊玩','close')}${this.button('離席','meetingLeave')}${this.button('會議紀錄冊','open','meetingRecords')}${this.button('設定','open','settings')}${this.button('操作說明','open','help')}</div>`;
 switch(name){case 'start':return `<div class="brand-mark">東山 <span>校園日常 / 異常</span></div><span class="eyebrow">AN ORDINARY DAY, ALMOST.</span><h1>東山校園<br><em>大騷動</em><span class="title-dot">。</span></h1><p class="intro">今天的老師，一如往常地端莊。<br>今天的校園，就不一定了。</p><div class="welcome-actions">${this.button('進入校園　↗','start','','primary')}${this.button('操作說明','help')}</div><p class="fine">v1.3.1 校事會議更容易登場，校狗新增笑臉提示；六種生活事件持續上演。<br>歡迎回到校園，一起發現今天的小插曲！</p>`;
 case 'dogs':return this.dogPanel();
 case 'meetingRecords':return this.header('MEETING MINUTES','會議紀錄冊')+`<p>${g.profile.meeting.titles.map(esc).join(' ・ ')||'尚未收藏稱號'}</p><div class=task-list>${[...g.profile.meeting.records].reverse().map(r=>`<article class=task-card><div><h3>${esc(r.reason)} · ${r.seconds}秒</h3><p>${r.lines.map(esc).join('<br>')}</p><small>seed ${r.seed} · ${r.modules.map(id=>esc(modules.find(m=>m.id===id)?.label||'會議橋段')).join(' / ')}</small></div></article>`).join('')||'<p>尚未開會。</p>'}</div>`;
 case 'pause':return this.header('TAKE A BREATH','課間休息')+`<div class="menu-grid">${this.button('繼續遊玩 ↗','close','','primary')}${this.button('今日待辦 · 24任務','open','missions')}${this.button('校園行事曆 · 4活動','open','calendar')}${this.button('校園地圖','open','map')}${this.button('校園生活','open','life')}${this.button('人物圖鑑','open','codex')}${this.button('道具說明','open','items')}${this.button('擊倒圖鑑','open','knockdowns')}${this.button('會議紀錄冊','open','meetingRecords')}${this.button('收藏與紀念卡','open','collection')}${this.button('音訊／畫質設定','open','settings')}${this.button('操作說明','open','help')}${this.button('存檔管理','open','save')}${this.button('重看教學','tutorial')}${this.button('重開平靜校園','confirmReset')}${import.meta.env.DEV?this.button('開發驗證面板','open','debug'):''}</div><p class="fine">${esc(this.store.error||'儲存長期进度；重新進入從平靜校園開始。')}</p>`;
 case 'missions':{g.emit('openTasks');let list=missions.filter(m=>m.mode===g.mode);return this.header('TODAY’S TO-DO',g.mode==='normal'?'今日待辦':chapters.find(c=>c.id===g.mode).label+'任務')+`<p class="muted">一次追蹤一項。可取消、免費重試；首通領點，重玩記錄評級。</p>${g.attempt?`<div class="active-task"><b>${missionName(g)}</b><p>${g.step.text}</p>${this.button('取消追蹤','cancelTask')}${this.button('重置任務物件','resetItems')}</div>`:''}<div class="task-list">${list.map(m=>`<article class="task-card"><div><span class="eyebrow">${m.category} · ${p.completedMissionIds.includes(m.id)?'已完成／重玩不給點':`首通 ${m.reward} 點`}</span><h3>${m.label}</h3><p>${m.steps.map(s=>esc(s.text)).join(' → ')}</p></div>${this.button(g.attempt?.mission===m.id?'追蹤中':p.completedMissionIds.includes(m.id)?'再試一次':'開始','task',m.id,g.attempt?.mission===m.id?'selected':'')}</article>`).join('')}</div>`;}
 case 'calendar':return this.header('SCHOOL CALENDAR','校園行事曆')+`<p class="muted">切換會重置當前校園、結束追逐；保留已完成與收藏。</p><div class="calendar-list">${[{id:'normal',label:'平常的一天',description:'自由探索與24項今日待辦。'},...chapters].map((c,i)=>`<article class="calendar-card"><span class="chapter-num">0${i}</span><div><h3>${c.label}</h3><p>${c.description}</p><small>${c.id==='normal'?'全部基礎玩法立即開放':`${missions.filter(m=>m.mode===c.id&&p.completedMissionIds.includes(m.id)).length}/4 完成`}</small></div>${this.button(g.mode===c.id?'目前活動':'進入','modeConfirm',c.id)}</article>`).join('')}</div>`;
 case 'settings':return this.header('MAKE YOURSELF COMFORTABLE','設定')+`<div class="settings"><label>畫質 <select id="quality">${['auto','low','standard'].map((v,i)=>`<option value="${v}" ${p.settings.quality===v?'selected':''}>${['自適應','Low · 輕量','Standard · 標準'][i]}</option>`).join('')}</select></label><label>音樂 <input id="music" type="range" min="0" max="100" value="${p.settings.music*100}"></label><label>音效 <input id="sfx" type="range" min="0" max="100" value="${p.settings.sfx*100}"></label><label><input id="mute" type="checkbox" ${p.settings.mute?'checked':''}>靜音（所有目標仍可完成）</label><label><input id="lowMotion" type="checkbox" ${p.settings.lowMotion?'checked':''}>減少動態效果</label><label><input id="assist" type="checkbox" ${p.settings.assist?'checked':''}>指揮輔助：±350ms</label>${this.button('儲存設定','settings','','primary')}${this.button('完整聲音試聽頁 ↗','soundTest')}</div><p class="fine">Low：DPR≤1，活躍人物≤16。${esc(this.audio.fail)}</p>`;
 case 'help':return this.header('A VERY COMPOSED TEACHER','操作說明')+`<div class="help"><p>左下搖桿移動，推深快跑。右下揮打、閃避與互動；拿物後可投擲。長按互動可選動作，或按「動作」。</p><dl><dt>WASD／方向鍵</dt><dd>依畫面方向移動；Shift 快跑</dd><dt>J／滑鼠左鍵</dt><dd>揮打（滑鼠決定面向）</dd><dt>K／空白鍵</dt><dd>短距閃避，不能穿牆</dd><dt>E／Q／R</dt><dd>互動／投擲／放下</dd><dt>F／Enter</dt><dd>點名／合唱指揮</dd><dt>Esc</dt><dd>暫停與繼續</dd></dl><p>一次拿一件；假髮與眼鏡各一個裝飾槽。黃色圈是任務交付／定位位置，在圈旁互動或放下。歸還需帶回原位置。推椅子時，站在椅子後面。</p><p>藏點：走廊工具間、教室講臺後。若被目擊躲入，家長會搜查。警戒消退需先甩開視線；進保健室不會清通緝。平靜時校護免費恢復。</p><p>校園無線麥克風：一般日於音樂教室，活動日於舞臺器材位置。手持時從「動作」使用10m擴音點名（共用12秒冷卻）；投擲落地產生3秒廣播誘餌，拿回即停，普通放下不啟動。追逐者仍看見老師、目擊投擲或需護子時不受吸引，聲音不能穿牆；靜音也有效。</p><p>人物跌坐後會恢復；沒有永久傷亡。任務物件卡住可從待辦按「重置任務物件」。</p></div>`;
 case 'actions':{if(g.meeting.running)return this.header('SCHOOL MEETING','會議動作')+`<div class=menu-grid>${g.meeting.context()?this.button(g.meeting.context(),'meetingUse'):''}${g.held?this.button('放下','gameAction','drop'):''}${g.nearest()?.itemType==='office_chair'?this.button('推動椅子','pushTarget'):''}${this.button('離席','meetingLeave')}</div><p>J 揮打／Q 投擲／F 特殊互動。攻擊保持原功能。</p>`;let target=g.nearest(),held=g.held;return this.header('WHAT WOULD YOU LIKE TO DO?','老師的動作')+`<p class="muted">最近：${esc(target?.label||'沒有目標')}　手持：${esc(held?itemDefs[held.type].label:'空手')}</p><div class="menu-grid">${target?this.button('互動 '+target.label,'interactTarget'):''}${g.life.targets().filter(t=>distanceUI(t,g.player)<2.5&&g.world.visible(t,g.player)).map(t=>this.button(t.label,'lifeInteract',t.id)).join('')}${this.button(held?.type==='wireless_microphone'?'擴音點名（10m／共用12秒冷卻）':'點名（6m／12秒冷卻）','gameAction','roll')}${held?this.button('放下／交付','gameAction','drop'):''}${held&&held.type!=='wireless_microphone'?this.button('使用：演奏／碼錶／清掃','gameAction','useHeld'):''}${held&&itemDefs[held.type].category.includes('wearable')?this.button('戴上','gameAction','wear'):''}${g.player.wig||g.player.glasses?this.button('取下頭部裝飾','gameAction','unwear'):''}${held||g.player.wig||g.player.glasses?this.button('歸還原位','gameAction','returnHeld'):''}${target?.itemType&&itemDefs[target.itemType].category.includes('pushable')?this.button('推動','pushTarget'):''}${target?.itemType&&itemDefs[target.itemType].category.includes('fixed')?this.button(target.itemType==='piano'?'亂按鋼琴':'咖啡機噴泡沫','messTarget'):''}${target?.itemType&&target.broken?this.button('扶起／整理物件','restoreTarget'):''}${zoneAt(g.player)==='classroom'?this.button('假裝上課','teach'):''}</div>${held?.type==='wireless_microphone'?'<p>請注意廣播。老師目前非常冷靜。<br>擴音點名：10m可聽見的平靜學生，與一般點名共用12秒冷卻。投擲落地播放3秒誘餌；目擊投擲或仍看見老師的追逐者不受騙。拿回即停止；普通放下不廣播。</p>':''}<p class="fine">這個選單仍讓人物行動；真正休息請用暫停。</p>`;}
 case 'shop':return this.header('CO-OP, OPEN FOR BUSINESS','合作社')+`<div class="balance">校園點數 <strong>${p.points}</strong></div><article class="task-card"><div><h3>涼茶 · 10點</h3><p>立即飲用恢復30體力；五秒冷卻。</p></div><button data-action="drink" ${p.points<10&&g.attempt?.mission!=='q21'?'disabled':''}>購買</button></article><div class="task-list">${cosmetics.map(c=>`<article class="task-card"><div><h3>${c.label}</h3><p>純外觀 · ${c.price}點</p></div><button data-action="cosmetic" data-id="${c.id}" ${p.ownedCosmetics.includes(c.id)||p.points<c.price?'disabled':''}>${p.ownedCosmetics.includes(c.id)?'已收藏':'購買'}</button></article>`).join('')}</div>${this.button('專用狗零食 · 5點（'+p.dogs.treats+'/20）','buyTreat')}${this.button('平靜服務：整理商品 +10點','service') }<p class="fine">${p.serviceCooldown>0?`服務冷卻 ${Math.ceil(p.serviceCooldown/60)} 分鐘`:'服務可領取，遊戲在線十分鐘冷卻'}</p>`;
 case 'map':return this.header('A SMALL CAMPUS, MANY POSSIBILITIES','校園地圖')+`<svg class="campus-map" viewBox="-33 -27 66 54" role="img" aria-label="校園與玩家任務位置">${zones.map(z=>`<rect x="${z.x1}" y="${z.z1}" width="${z.x2-z.x1}" height="${z.z2-z.z1}" rx=".6"/><text x="${(z.x1+z.x2)/2}" y="${(z.z1+z.z2)/2}">${z.label}</text>`).join('')}<circle class="player-dot" cx="${g.player.x}" cy="${g.player.z}" r="1"/>${this.mapTargets().map(t=>`<circle class="goal-dot" cx="${t.x}" cy="${t.z}" r=".8"/>`).join('')}</svg><p class="fine">綠點：老師　黃點：目標／任務物件。${g.notes.map(esc).join(' ')}</p>`;
 case 'knockdowns':{
 const group=this.codexTab,records=p.knockdownCodex[group];
 const entries=codexEntries[group].filter(e=>group!=='objects'||records[e.id]);
 return this.header('CAMPUS INCIDENT COLLECTION','擊倒圖鑑')+`<p class="muted">記錄老師實際造成的暈眩與破損，跨活動、重新開啟皆保留。人物稍後會恢復；家具扶好不會刪除紀錄。</p><div class="codex-tabs" role="group" aria-label="圖鑑分類">${(['students','parents','objects'] as const).map((tab,i)=>`<button data-action="codexTab" data-id="${tab}" aria-pressed="${group===tab}" class="${group===tab?'selected':''}">${['學生','家長','物品'][i]} · ${Object.keys(p.knockdownCodex[tab]).length}</button>`).join('')}</div><p>已記錄 ${Object.keys(records).length} 種 · 共 ${Object.values(records).reduce((a,b)=>a+b,0)} 次</p><div class="codex-grid incident-codex">${entries.map(e=>`<article class="${records[e.id]?'discovered':'undiscovered'}" data-codex-id="${esc(e.id)}">${this.thumbnail(e.id,group==='objects'?'item':group==='students'?'student':'parent')}<h4>${esc(e.label)}</h4><p>${records[e.id]?esc(e.description):'尚未記錄'}</p><small>${records[e.id]?`${group==='objects'?'破損':'暈眩'} ${records[e.id]} 次`:'未解鎖'}</small></article>`).join('')||'<p>還沒有物品破損紀錄。翻倒家具、垃圾桶，或投擲物品落地破損時會加入。</p>'}</div><p class="fine">從本次更新起記錄；舊存檔僅有總次數，無法還原過往的個別種類。學生惡作劇與活動預設破損不列入。</p>`;
 }
 case 'items':return this.header('PLEASE RETURN AFTER USE',`道具說明 · ${items.length}種`)+`<div class="codex-grid">${items.map(i=>`<article data-item-id="${i.id}">${this.thumbnail(i.id,'item')}<h4>${esc(i.label)}</h4><p>${esc(i.description||(i.category.includes('fixed')?'固定互動；不能拿取或投擲。':'依情境選單拿取、放下、使用或歸還。'))}</p><small>揮打 ${i.damage} ／ 投擲 ${i.throwDamage} · ${i.heavy?'重型':'輕型／固定'}</small>${i.id==='wireless_microphone'?'<p>一般校園：音樂教室樂器收納臺；活動日：中庭舞臺右側器材位置。手持後「動作」→擴音點名（10m，與點名共用12秒冷卻）；Q／投擲落地廣播3秒，引附近可聽見且願意調查者。追逐仍看見老師或目擊投擲者不受騙，護子／重要任務優先。相同人物與麥克風30秒調查冷卻。拿回、歸還、重置即停止，普通放下不啟動。靜音也有效。</p>':''}</article>`).join('')}</div>`;
 case 'codex':return this.header('EVERYONE HAS THEIR OWN WAY','校園人物圖鑑')+`<h3>十二種學生</h3><div class="codex-grid">${students.map(s=>`<article>${this.thumbnail(s.id,students.includes(s as any)?'student':'parent')}<h4>${s.label}</h4><p>${s.description}</p></article>`).join('')}</div><h3>十九種家長</h3><div class="codex-grid">${parents.map(s=>`<article>${this.thumbnail(s.id,students.includes(s as any)?'student':'parent')}<h4>${s.label}</h4><p>${s.description}</p><small>${s.tier} · 占 ${s.slotCost} 名額</small></article>`).join('')}</div><h3>校園職員與兩位新朋友</h3><div class=codex-grid>${staff.map(s=>`<article>${this.thumbnail(s.id,'staff')}<h4>${s.label}</h4></article>`).join('')}${dogIds.map(id=>`<article>${this.thumbnail(id,'dog')}<h4>${dogNames[id]}</h4><p>${stage(p.dogs.dogs[id].affinity)} · ${p.dogs.dogs[id].affinity}/100</p><p>${p.dogs.dogs[id].collected?(id==='dog_lion'?'LION 將你列為正式巡邏夥伴':'馬尼認為你是專職摸摸人員'):''}</p></article>`).join('')}</div>`;
 case 'life':return this.header('CAMPUS LIFE','校園生活')+`<p>${esc(g.life.context())}</p><p>靠近餐車按 E 吃午餐；拿拖把靠近牛奶漬按 E 清理；向校安老師按 E 告知情況；拿起失物陀螺後靠近失主按 E 歸還。移動或受擊會中斷用餐與清理。</p><p>午餐冷卻 ${Math.ceil(p.life.mealCooldown)}秒 · 肚子提出異議 ${Math.ceil(p.life.stomach)}秒</p><div class="menu-grid">${lifeAwards.map(a=>`<p>${p.life.achievements.includes(a)?'✓':'○'} ${esc(a)}</p>`).join('')}</div><p class="fine">所有人物沿用普通受擊；LION 與馬尼只接受校狗互動。暫停與會議期間，生活事件時鐘也會停下。</p>`;
 case 'collection':return this.header('LITTLE MEMORIES','收藏與稱號')+`<h3>校園生活紀念 · ${p.life.achievements.length}/6</h3><p>${p.life.achievements.map(esc).join(' · ')||'觀察、告知與歸還，留下生活紀念。'}</p><h3>外觀（保留黃色洋裝與鮑伯頭）</h3><div class="menu-grid">${cosmetics.filter(c=>p.ownedCosmetics.includes(c.id)).map(c=>this.button((p.equipped.includes(c.id)?'✓ ':'')+c.label,'equip',c.id)).join('')||'<p>合作社有六種純外觀收藏。</p>'}</div><h3>稱號 · ${p.titleIds.length}/12</h3><p>${p.titleIds.map(esc).join(' · ')||'完成任務獲得稱號。'}</p><h3>合照紀念卡（程式構圖）</h3><div class="photo-grid">${p.photoCards.map((c,i)=>`<div class="photo-card"><span>${c.wig?'🟤':c.glasses?'👓':'♫'}　${c.broom?'╱':'♩'}</span><b>東山・第${i+1}張合照</b><p>${c.students}學生 / ${c.visitors}家長<br>${c.wig?'假髮版 ':''}${c.glasses?'眼鏡版 ':''}${c.broom?'掃把版':''}</p></div>`).join('')||'<p>親師日完成合照，可留下構圖紀念卡。</p>'}</div>`;
 case 'report':return this.header('INCIDENT REPORT','保健室事件報告')+`<div class="report-grid">${Object.entries(g.lastReport||g.report).filter(([k])=>['damage','downed','parents','maxAlert'].includes(k)).map(([k,v])=>`<article><b>${v}</b><span>${({damage:'家具翻倒',downed:'人物暈眩',parents:'追逐家長',maxAlert:'最高警戒'})[k]}</span></article>`).join('')}</div><p>體力 ${Math.ceil(g.player.hp)}/100。倒地救援已結束當次事件；任務可免費重試，長期紀錄保留。</p>`;
 case 'save':return this.header('KEEP THE MEMORIES','存檔管理')+`<p>只儲存長期紀錄。匯入前驗證版本與 ID，損壞檔不覆蓋。</p><div class="menu-grid">${this.button('立即儲存','saveNow')}${this.button('匯出 JSON','export')}${this.button('匯入 JSON','import')}${this.button('接管其他分頁寫入','takeover')}${this.button('清除進度（確認）','clearConfirm')}</div><input type="file" id="importFile" accept="application/json,.json" hidden><p class="fine">${esc(this.store.error||'本地存檔就緒')} · revision ${p.revision}</p>`;
 case 'debug':return this.header('DEVELOPMENT ONLY','可重現驗證')+`<p>Seed ${g.rosterSeed} · ${g.assertOwnership()?'物件身份正常':''}</p><div class="menu-grid">${zones.map(z=>this.button('到 '+z.label,'teleport',z.id)).join('')}</div><h3>家長型別（仍受3名額限制）</h3><div class="menu-grid">${parents.map(p=>this.button(p.label,'spawn',p.id)).join('')}</div><h3>警戒</h3>${[0,20,40,65,90].map(v=>this.button(String(v),'alert',String(v))).join('')}${this.button('恢復／清場','devReset')}${this.button('效能 HUD 開關','debugHUD')}<pre>${esc(JSON.stringify(this.render.measure(),null,2))}</pre><p>目前任務事件：</p><pre>${esc(JSON.stringify(g.eventLog.slice(-12),null,2))}</pre>`;
 case 'timeQuestion':return this.header('LOOK AT THE CLOCK','時間到了嗎？')+`<p>黑板：考試時間24分鐘，已過12分鐘，剩餘12分鐘。</p>${[6,12,24].map(n=>this.button(n+'分鐘','answer',String(n))).join('')}`;
 default:if(name.startsWith('dialog:')){let n=g.npcs.find(n=>n.id===name.slice(7));return this.header('LET’S TALK',n.label+'的經歷')+`<p>${({timid:'老師，刚剛的聲音好大。',fighter:'老師，不能一直用揮打解決問題。',tattletale:'我要把今天的事告訴主任。'})[n.type]||'老師，今天的校園有點混亂。'}</p><div class="menu-grid">${['說明事實','一本正經的荒謬解釋','結束談話'].map((t,i)=>`<button data-action="respond" data-id="${n.id}" data-value="${i}">${t}</button>`).join('')}</div>`}return this.header('CONFIRM','確認')+`<p>${name.startsWith('mode:')?'切換活動會重置當前場景並取消未完成任務。':name==='clearConfirm'?'清除本地長期紀錄，無法撤銷。':'重開平靜校園，未完成任務可重新接取。'}</p>${this.button('確認','confirm',name,'primary')}${this.button('取消','open','pause')}`;
 }}
 thumbnail(id:string,role:string){return `<img class="codex-thumb" alt="${esc(id)} 遊戲模型" src="${this.render.thumbnail(id,role)}">`}
 dogPanel(){const g=this.game,p=g.profile.dogs;return this.header('TWO CAMPUS FRIENDS','校狗 · LION 與馬尼')+`<p>零食 ${p.treats}/20 · 共享協助冷卻 ${Math.ceil(p.assistCooldown)} 秒。摸摸 E；攻擊 J 始終保持揮打。</p>${dogIds.map(id=>{const d=g.dogs.actor(id),v=p.dogs[id];return `<article class=dog-status>${this.thumbnail(id,'dog')}<h3>${dogNames[id]} · ${v.affinity}/100</h3><p>${stage(v.affinity)} · ${g.meeting.running?(g.dogs.observer===id?'會議旁聽席':'校園安全等待'):zones.find(z=>z.id===zoneAt(d))?.label||'共用走廊'} · ${esc(d.state)}</p><p>跟隨：45好感 ／ 協助：75好感。摸摸 ${Math.ceil(v.cooldowns.pet)}s、零食 ${Math.ceil(v.cooldowns.treat)}s、玩球 ${Math.ceil(v.cooldowns.ball)}s。</p><div class=menu-grid>${[['pet','摸摸'],['treat','給零食'],['play','玩球'],['follow','跟我來'],['rest','回去休息'],['assist','請牠幫忙']].map(([act,label])=>this.button(label,'dogAction',id+':'+act)).join('')}</div></article>`}).join('')}<h3>協助目標：${esc(g.npcs.find(n=>n.id===g.dogs.selectedTarget)?.label||'尚未選取')}</h3><p>先點選畫面中的敵對成人，或在下方確認名字，再請狗幫忙。</p><div class=menu-grid>${g.npcs.filter(n=>g.dogs.validTarget(n)&&distanceUI(n,g.player)<8&&this.render.inView(n)&&g.world.visible(g.player,n)).map(n=>this.button(n.label,'dogTarget',n.id,n.id===g.dogs.selectedTarget?'selected':'')).join('')||'附近沒有有效敵對成人。'}</div><h3>理化老師的小任務</h3><p>找辦公室／餵狗角附近的老師接取及交付。${p.activeQuest?esc(dogQuests.find(q=>q.id===p.activeQuest)?.label):'尚未追蹤校狗任務'}</p>${p.activeQuest?`<p>${(()=>{const q=dogQuests.find(q=>q.id===p.activeQuest)!;return 'item' in q?'取物：'+(zones.find(z=>z.id===zoneAt(q.home))?.label||'中庭')+'（地圖黃點）。取回後帶到餵狗角黃色圈，按 E 定位，再向老師交付。':'在餵狗角附近選「跟我來」，陪走到'+(q.dog==='dog_lion'?'操場入口':'音樂教室外')+'的黃色圈，再向老師交付。';})()}</p>`:''}<div class=menu-grid>${dogQuests.map(q=>this.button((p.dogs[q.dog].completed.includes(q.id)?'✓ ':'')+q.label,'dogQuest',q.id)).join('')}${this.button('向老師交付','dogDeliver')}${this.button('任務物件安全歸位','dogReset')}</div><p>${p.achievements.map(esc).join(' · ')||'和校狗一起留下新回憶。'}</p>`;}
 mapTargets(){let g=this.game,s=g.step;const q=dogQuests.find(q=>q.id===g.profile.dogs.activeQuest);if(q)return 'item' in q?[q.home,q.goal]:[{x:8,z:11},q.goal];if(!s)return[];if(['deliver','place','wearVisit'].includes(s.kind))return Array.from({length:s.count||1},(_,k)=>destination(s,k));if(s.kind==='gather')return this.game.npcs.filter(n=>this.game.attempt.meta.choristers.includes(n.id)).map(n=>({x:n.x,z:n.z}));if(s.kind==='return'){let i=[...g.objects.values()].find(i=>i.type===s.item);return i?[i.home]:[]}return [...g.objects.values()].filter(i=>i.pins.includes(g.attempt.id)).map(i=>({x:i.x,z:i.z}))}
 action(action:string){if(!this.started||this.modal)return;let g=this.game;switch(action){case 'attack':g.attack();break;case 'dodge':g.dodge();break;case 'throw':g.throwItem();break;case 'drop':g.drop();break;case 'roll':g.rollCall();break;case 'conduct':g.conduct();break;case 'interact':this.handleResult(g.interact());break}}
 handleResult(result:any){if(typeof result==='string'&&['missions','shop','report','timeQuestion','dogs'].includes(result))this.open(result,false);else if(result?.dialog)this.open('dialog:'+result.dialog,false)}
 async click(action:string,id='',value=''){let g=this.game;switch(action){case 'codexTab':if(['students','parents','objects'].includes(id)){this.codexTab=id as CodexGroup;this.open('knockdowns')}break;case 'close':this.close();break;case 'start':await this.audio.unlock();this.started=true;this.close();if(!g.profile.tutorialFlags.includes('done')){g.startTutorial();this.toast(g.tutorialText())}break;case 'open':this.open(id);break;case 'task':g.startMission(id);this.close();break;case 'cancelTask':g.cancelMission();this.open('missions');break;case 'resetItems':g.resetObjectiveItems();this.open('missions');break;case 'tutorial':g.startTutorial();this.close();break;case 'skipTutorial':g.finishTutorial();break;case 'modeConfirm':this.open('mode:'+id);break;case 'confirmReset':this.open('resetConfirm');break;case 'clearConfirm':this.open('clearConfirm');break;case 'confirm':if(id==='clearConfirm'){g.profile=fresh();g.reset('normal');this.store.save(g.profile)}else g.reset(id.startsWith('mode:')?id.slice(5):g.mode,id.startsWith('mode:'));this.close();break;
 case 'settings':for(let k of ['mute','lowMotion','assist'])g.profile.settings[k]=($('#'+k) as HTMLInputElement).checked;for(let k of ['music','sfx'])g.profile.settings[k]=+($('#'+k) as HTMLInputElement).value/100;g.profile.settings.quality=($('#quality') as HTMLSelectElement).value;this.audio.configure();this.render.resize();this.store.save(g.profile);this.toast('設定已儲存');break;case 'soundTest':window.open('./soundtest.html','_blank','noopener');break;
 case 'meetingUse':this.close();g.meeting.secondary();break;case 'meetingLeave':this.close();g.meeting.leave();break;
 case 'lifeInteract':{this.close();const target=g.life.targets().find(t=>t.id===id&&distanceUI(t,g.player)<2.5&&g.world.visible(t,g.player));if(target)g.life.interact(target.id);break;}case 'gameAction':this.close();g.interact(undefined,id);break;case 'interactTarget':this.close();this.handleResult(g.interact());break;case 'pushTarget':this.close();g.interact(g.nearest(),'push');break;case 'messTarget':this.close();g.interact(g.nearest(),'mess');break;case 'restoreTarget':this.close();g.interact(g.nearest(),'restore');break;case 'teach':this.close();g.teach();break;
 case 'drink':if(g.buyDrink())this.toast('涼茶恢復30體力');else this.toast('點數不足或飲用冷卻中');this.open('shop',false);break;case 'cosmetic':g.buyCosmetic(id);this.open('shop',false);break;case 'buyTreat':g.dogs.buyTreat();this.open('shop',false);break;case 'dogQuest':g.dogs.quest(id);this.open('dogs');break;case 'dogReset':g.dogs.resetQuest();this.open('dogs');break;case 'dogDeliver':g.dogs.checkDelivery();this.open('dogs');break;case 'dogAction':{const [dog,act]=id.split(':');this.close();if(act==='pet')g.dogs.pet(dog as any);if(act==='treat')g.dogs.treat(dog as any);if(act==='play')g.dogs.play(dog as any);if(act==='follow')g.dogs.follow(dog as any);if(act==='rest'){g.dogs.cancel(g.dogs.actor(dog));g.dogs.p.companion=null;}if(act==='assist')g.dogs.assist(dog as any);break;}case 'dogTarget':g.dogs.select(id);this.open('dogs');break;case 'service':this.toast(g.service()?'整理完成 +10點':'平靜且冷卻結束才可服務');this.open('shop',false);break;case 'equip':if(g.profile.equipped.includes(id))g.profile.equipped=g.profile.equipped.filter(x=>x!==id);else{let category=id.split('_')[0];g.profile.equipped=g.profile.equipped.filter(x=>x.split('_')[0]!==category);g.profile.equipped.push(id)}this.store.save(g.profile);this.open('collection');break;
 case 'respond':g.respond(id,+value);this.close();break;case 'answer':g.emit('answerTime',{correct:+id===12});this.toast(+id===12?'正確，還有12分鐘。':'再看一次黑板：剩餘12分鐘。');if(+id===12)this.close();break;
 case 'saveNow':this.store.save(g.profile);this.open('save');break;case 'export':{let blob=new Blob([JSON.stringify(g.profile,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='dongshan-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);break}case 'import':{let file=$('#importFile') as HTMLInputElement;file.onchange=async()=>{try{let f=file.files[0];if(f.size>600000)throw Error('檔案過大');let p=validateSave(JSON.parse(await f.text()));g.profile=p;g.reset('normal');this.store.save(p);this.audio.configure();this.toast('匯入成功');this.open('save')}catch(e){this.toast('匯入失敗，原存檔保留：'+e.message)}};file.click();break}case 'takeover':this.store.claim(true);this.store.save(g.profile);this.open('save');break;
 case 'teleport':Object.assign(g.player,center(id));this.close();break;case 'spawn':this.toast(g.spawnParent(id)?'家長已從校門入場':'3名額預算不足');this.close();break;case 'alert':g.alert=+id;g.lastTrouble=g.time;this.close();break;case 'devReset':g.reset(g.mode);this.open('debug');break;case 'debugHUD':this.debug=!this.debug;this.close();break;}}
 toast(s:string,dog?:{id:string,gain:number}){let speech=$('#speech');speech.hidden=!s.includes('：')&&!/^(各位|我們|這是|請不要|物品)/.test(s);if(!speech.hidden)speech.textContent=s;const toast=$('#toast'),text=document.createElement('span');text.className='toast-text';text.textContent=s;toast.replaceChildren(text);const showDog=!!dog&&dog.gain>0&&['dog_lion','dog_mani'].includes(dog.id);toast.classList.toggle('toast-dog',showDog);if(showDog){const face=document.createElement('span');face.className='toast-dog-face';face.innerHTML=dogPortrait(dog!.id);toast.prepend(face);speech.hidden=true;}if(!speech.hidden)$('#toast').classList.remove('visible');else $('#toast').classList.add('visible');this.toastUntil=performance.now()+(showDog?3000:4000)}
 setQuestCollapsed(collapsed:boolean){
 this.questCollapsed=collapsed;$('.quest').classList.toggle('is-collapsed',collapsed);$('#quest-body').hidden=collapsed;
 $('#quest-toggle').setAttribute('aria-expanded',String(!collapsed));$('#quest-toggle').setAttribute('aria-label',collapsed?'展開今日提示':'收合今日提示');$('#quest-chevron').textContent=collapsed?'▽':'△';
 }
 updateFeedback(){
  const g=this.game,state=healthState(g.player.hp),low=state!=='normal',still=g.profile.settings.lowMotion||matchMedia("(prefers-reduced-motion: reduce)").matches||this.paused;
  $('.status-card').dataset.health=state;$('.hud').classList.toggle('feedback-still',still);
  $('#health-vignette').hidden=!low||!this.started;$('#health-vignette').dataset.health=state;
  const warning=$('#health-warning');warning.hidden=!low;const text=state==='critical'?'危急！先拉開距離':'血量偏低 · 先找掩護';if(warning.textContent!==text)warning.textContent=text;
  this.hitLabels=this.hitLabels.filter(h=>g.time-h.start<.65&&g.time>=h.start);
  $('#hit-feedback').innerHTML=this.hitLabels.map(h=>{const age=g.time-h.start,pos=this.render.project(h,1.9);return `<span class="hit-label" style="left:${pos.x}px;top:${pos.y-(still?0:age*35)}px;opacity:${Math.min(1,(.65-age)/.2)}">命中 −${h.damage}</span>`}).join('');
 }
 updateQuest(){
 const g=this.game,title=g.tutorial>=0?'日常差事教學':g.attempt?missionName(g):'今天，想做點什麼？';
 const detail=g.tutorial>=0?g.tutorialText():g.step?`${g.step.text}　${g.attempt.count}/${g.step.count||1}`:'探索校園，或從今日待辦選一件差事。';
 // Movement and countdown ticks do not undo a deliberate collapse.
 const signature=JSON.stringify([g.session,g.tutorial,g.attempt?.id,g.attempt?.step,title,detail]);
 if(signature!==this.questContent){this.questContent=signature;$('#quest-title').textContent=title;$('#quest-detail').textContent=detail;$('#skip').hidden=g.tutorial<0;this.setQuestCollapsed(false)}
 }
 update(dt:number){let g=this.game,p=g.player;this.hudClock+=dt;if(this.hudClock<.1)return;this.hudClock=0;$('#hp-text').textContent=Math.ceil(p.hp)+' / 100';($('#hp-bar') as HTMLElement).style.width=p.hp+'%';$('#alert-text').textContent='警戒 '+g.level;$('#alert-circles').innerHTML=Array.from({length:4},(_,i)=>`<i class="${i<g.level?'lit':''}"></i>`).join('');$('#alert-reason').textContent=g.reason;$('#held').textContent=g.held?itemDefs[g.held.type].label:'空手・從容';$('#zone').textContent=zones.find(z=>z.id===zoneAt(p))?.label||'共用走廊';$('#points').textContent=g.profile.points+' 點';this.updateQuest();if(g.meeting.running){$('#zone').textContent='校事會議';$('#quest-title').textContent=`失控 ${g.meeting.chaos}/100 · 剩餘 ${Math.max(0,Math.ceil(75-g.meeting.elapsed))}秒`;$('#quest-detail').textContent=g.meeting.context()||'可以搗亂，也可以隨時離席';$('#alert-text').textContent=`失控 ${g.meeting.chaos}/100`;$('#alert-reason').textContent=`剩餘 ${Math.max(0,Math.ceil(75-g.meeting.elapsed))}秒 · `+`${g.meeting.selected.length} 種橋段`;$('#quest-detail').textContent=g.meeting.context()||g.meeting.selected.map(id=>modules.find(m=>m.id===id)?.label).join('／');}$('#world').style.opacity=g.meeting.phase==='ENTERING'?'0.15':'1';$('#meeting-controls').hidden=!g.meeting.running;$('.side-nav').hidden=g.meeting.running;$('#meeting-use').textContent=g.meeting.context()||'靠近特殊道具';($('#meeting-use') as HTMLButtonElement).disabled=!g.meeting.context();$('#meeting-display').hidden=!g.meeting.running;$('#meeting-display').textContent=g.meeting.selected.includes('projector')?'投影：'+g.meeting.cards[g.meeting.projectorPage]:g.meeting.selected.includes('whiteboard')?'白板：'+(g.meeting.boardMusic?'♩ ♪ ♫ 四分音符':['說明／討論／決議','決議／說明／討論','討論／決議／說明'][g.meeting.agenda]):'';$('#throw').hidden=!g.held;$('#drop').hidden=!g.held;$('#meeting-ready').textContent=g.meeting.triggerStatus();$('#meeting-ready').hidden=g.meeting.running;$('#conduct').hidden=!g.choir;$('#actions').textContent=p.hidden?'離開藏點':'動作';let n=g.nearest();$('#context').textContent=p.hidden?'互動：離開藏點':n?'互動 · '+n.label:'靠近物品或人物';$('#arrival').textContent=g.familyQueue.length?`${parentDefsLabel(g.familyQueue[0].type)}到校 · ${Math.max(0,Math.ceil(g.familyQueue[0].at-g.time))}s`:'';$('#arrival').hidden=!g.familyQueue.length;if(!g.meeting.running){$('#zone').textContent+=' · '+g.life.phase;if(!g.attempt&&g.tutorial<0)$('#quest-detail').textContent=g.life.context();$('#alert-reason').textContent=g.reason+(g.life.p.stomach>0?' · 肚子提出異議 '+Math.ceil(g.life.p.stomach)+'秒':'');}
 if(g.choir){let song=g.time-g.choir.start,beat=song/.75;let next=[3,7,11,15,19,23,27,31].find(b=>b>=beat-.35);$('#beat').hidden=false;$('#beat').innerHTML=`<span>第 ${Math.min(32,Math.floor(beat)+1)} / 32 拍　${g.choir.hits}/8命中</span><div class="beat-ring" style="transform:scale(${next===undefined?1:Math.min(2,Math.max(.6,1+(next-beat)*.35))})"></div><b>${next!==undefined&&Math.abs(next-beat)<.35?'現在！':'跟著收圈'}</b>`}else $('#beat').hidden=true;
 this.updateFeedback();
 const signals=g.microphoneSignals().filter(s=>this.render.inView(s)&&Math.hypot(s.x-p.x,s.z-p.z)<12),signal=signals.find(s=>s.kind==='call')||signals[0],micSpeech=$('#microphone-speech');micSpeech.hidden=!signal;if(signal){const pos=this.render.project(signal,signal.kind==='call'?2.6:1);micSpeech.textContent=signal.text;micSpeech.style.left=Math.min(innerWidth-110,Math.max(110,pos.x))+'px';micSpeech.style.top=Math.min(innerHeight-40,Math.max(30,pos.y))+'px'}
 if(performance.now()>this.toastUntil){$('#toast').classList.remove('visible');$('#speech').hidden=true}else if(!$('#speech').hidden){let pos=this.render.project(p);$('#speech').style.left=Math.min(innerWidth-115,Math.max(115,pos.x))+'px';$('#speech').style.top=Math.max(24,pos.y)+'px';}$('#debug-hud').hidden=!this.debug;if(this.debug)$('#debug-hud').textContent=JSON.stringify({...this.render.measure(),voices:this.audio.voices.size,musicVoices:this.audio.musicVoices.size,save:this.store.error},null,2);if(this.store.error)$('#save-warning').textContent=this.store.error;}
}
function missionName(g:Game){return missions.find(m=>m.id===g.attempt.mission)?.label||''}function parentDefsLabel(id:string){return parents.find(p=>p.id===id)?.label+'家長'}

function distanceUI(a:{x:number,z:number},b:{x:number,z:number}){return Math.hypot(a.x-b.x,a.z-b.z)}
